(rule
  (targets
    alectryon.css
    alectryon.js
    docutils_basic.css
    pygments.css
    tutorial.html
  )
  (mode (promote (until-clean)))
  (deps
     tutorial.v
     (package coq-osiris)
  )
  (action
    (run alectryon-custom
         --long-line-threshold 80
         -R ../theories osiris
         tutorial.v
    )
  )
)
