(* This file has been generated by Osiris. Do not edit. *)

From osiris Require Import osiris.

Definition __fun0 :=
  AnonFun "v" (
    deco "(v.x * v.x) + (v.y * v.y)" (
      EIntAdd (
        deco "(v.x * v.x)" (
          EIntMul (deco "v.x" (ERecordAccess (deco "v" (EPath [ "v" ])) 0%Z)) (
            deco "v.x" (ERecordAccess (deco "v" (EPath [ "v" ])) 0%Z)
          )
        )
      ) (
        deco "(v.y * v.y)" (
          EIntMul (deco "v.y" (ERecordAccess (deco "v" (EPath [ "v" ])) 1%Z)) (
            deco "v.y" (ERecordAccess (deco "v" (EPath [ "v" ])) 1%Z)
          )
        )
      )
    )
  ).

Definition __fun1 :=
  AnonFun "x" (
    deco "v.x <- x" (
      ERecordSet (deco "v" (EPath [ "v" ])) 0%Z (deco "x" (EPath [ "x" ]))
    )
  ).

Definition __fun2 := AnonFun "v" (EAnonFun __fun1).

Definition __main :=
  MStruct [
    ILet [
      Binding (PVar "vec") (
        deco "{ x = 1; y = 1 }" (
          ERecord Mut [
            deco "1" (EInt 1);
            deco "1" (EInt 1)
          ]
        )
      )
    ];
    ILet [
      Binding (PVar "length") (
        deco "v = (v.x * v.x) + (v.y * v.y)" (EAnonFun __fun0)
      )
    ];
    ILet [
      Binding (PVar "update_x") (deco "v x = v.x <- x" (EAnonFun __fun2))
    ]
  ].

