(lang dune 3.8)
(generate_opam_files true)
(package
  (name osiris)
  (authors
    "François Pottier"
    "Arnaud Daby-Seesaram"
    "Remy Seassau"
  )
  (maintainers
    "François Pottier"
  )
  (homepage https://gitlab.inria.fr/fpottier/osiris/)
  (bug_reports francois.pottier@inria.fr)
  (synopsis "Osiris translates OCaml to Coq for verification")
  (depends
    ocaml
    dune
    (ocaml-compiler-libs (= 4.14.1))
    pprint
    base
    csexp
  )
)
