pages:
  script:
    - mkdir public
    - cp -r rocq-osiris/tutorial/* public
  artifacts:
    paths:
      # The folder that contains the files to be exposed at the Page URL
      - public
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
      changes:
      - rocq-osiris/tutorial/*