open Printf
open Fail
let say = Settings.say
let concat, is_relative, remove_extension =
  Filename.(concat, is_relative, remove_extension)
open FilenameExtra
open SysExtra

(* -------------------------------------------------------------------------- *)

(* Reading a .cmt file and extracting the typed tree. *)

(* https://github.com/ocaml/ocaml/blob/trunk/file_formats/cmt_format.mli *)

let read_cmt cmt_file : Typedtree.structure =
  assert (is_absolute cmt_file);
  match Cmt_format.read_cmt cmt_file with
  | exception Cmt_format.(Error (Not_a_typedtree _))
  | exception Cmi_format.(Error (Not_an_interface _)) ->
      fail "Invalid .cmt file: %s\n" cmt_file
  | infos ->
      let { cmt_annots; _ } : Cmt_format.cmt_infos = infos in
      match cmt_annots with
      | Cmt_format.Implementation t ->
          t
      | _ ->
          fail "This .cmt file does not contain a typed tree: %s\n" cmt_file

(* -------------------------------------------------------------------------- *)

let print out_file doc =
  ensure_parent_directory_exists out_file;
  let f = open_out out_file in
  fprintf f "(* This file has been generated by Osiris. Do not edit. *)\n\n";
  fprintf f "From osiris Require Import osiris.\n\n";
  let ribbon = 1.0
  and width = 80 in
  PPrint.ToChannel.pretty ribbon width f doc;
  fprintf f "\n(* Done. *)%!";
  close_out f

(* -------------------------------------------------------------------------- *)

(* Main code of the translator. *)

let translate_one_file module_name out_file cmt_file =
  assert (is_absolute cmt_file);
  assert (is_absolute out_file);

  (* Read the .cmt file, which contains a typed OCaml AST. *)
  let u : Typedtree.structure = read_cmt cmt_file in

  (* Convert this typed OCaml AST to an Osiris AST. *)
  let m = "_" ^ module_name in (* TODO revisit or document this convention *)
  let u : Syntax.mexpr = Translate.unit u in

  let u : Coq.expression = Coqify.module_expression u in
  let def : Coq.def = { lhs = m; rhs = u } in
  let defs = Chop.chop def in
  let doc = Pp.print_defs defs in

  (* Finally, pretty-print the generated definitions into the output file
     provided on the command line. *)
  print out_file doc

(* -------------------------------------------------------------------------- *)

(* The path of the output file (.v) is computed based on the path of the
   source file (.ml). The latter is relative to the dune root directory.
   It typically begins with something like [_build/default/], so we chop
   the first two segments of it. *)

let output_file_path ml_file =
  assert (is_relative ml_file);
  ml_file
  |> remove_extension                        (* remove [.ml] or [.ml-gen] *)
  |> add_suffix ".v"                         (* add [.v] *)
  |> drop 2
  |> concat Settings.out                     (* make this an absolute path *)
  |> map_basename (add_prefix Settings.mark) (* add mark to file name *)

(* -------------------------------------------------------------------------- *)

(* Obtain a table of the modules in this project. *)

let table =
  Dune.describe Settings.root

let process m =
  say "Processing module: %s\n" m;
  (* Find its .ml file, relative to the dune root directory. *)
  let ml_file = Dune.impl m table in
  (* Find its .cmt file, relative to the dune root directory. *)
  let cmt_file = Dune.cmt m table in
  say "    .cmt file: %s\n" cmt_file;
  (* Construct the absolute path of the input (.cmt) file. *)
  let cmt_file = concat Settings.root cmt_file in
  (* Construct the absolute path of the output (.v) file. *)
  let v_file = output_file_path ml_file in
  say "  output file: %s\n" v_file;
  (* Translate this file. *)
  translate_one_file m v_file cmt_file

let () =
  (* Check the list of modules that was passed on the command line. *)
  match Settings.modules with
  | `All ->
      (* Process all modules. *)
      Dune.M.iter (fun m _ -> process m) table
  | `Modules ms ->
      (* Process only the modules named on the command line. *)
      List.iter process ms
