open Printf
open Fail
let say = Settings.say
let concat, is_relative, remove_extension =
  Filename.(concat, is_relative, remove_extension)
open FilenameExtra
open SysExtra

(* -------------------------------------------------------------------------- *)

(* Reading a .cmt file and extracting the typed tree. *)

(* https://github.com/ocaml/ocaml/blob/trunk/file_formats/cmt_format.mli *)

let read_cmt cmt_file : Typedtree.structure =
  assert (is_absolute cmt_file);
  match Cmt_format.read_cmt cmt_file with
  | exception Cmt_format.(Error (Not_a_typedtree _))
  | exception Cmi_format.(Error (Not_an_interface _)) ->
      fail "Invalid .cmt file: %s\n" cmt_file
  | infos ->
      let { cmt_annots; _ } : Cmt_format.cmt_infos = infos in
      match cmt_annots with
      | Cmt_format.Implementation t ->
          t
      | _ ->
          fail "This .cmt file does not contain a typed tree: %s\n" cmt_file

(* -------------------------------------------------------------------------- *)

let print out_file doc_graph =
  ensure_parent_directory_exists out_file;
  let f = open_out out_file in
  fprintf f "(* This file has been generated by Osiris. Do not edit. *)\n\n";
  fprintf f "From osiris Require Import osiris.\n\n";
  let ribbon = 1.0
  and width = 80 in
  let print doc = PPrint.ToChannel.pretty ribbon width f doc in
  DAG.to_list doc_graph |> List.iter print;
  fprintf f "\n(* Done. *)%!";
  close_out f

(* -------------------------------------------------------------------------- *)

(* Main code of the translator. *)

let translate_one_file module_name out_file cmt_file =
  assert (is_absolute cmt_file);
  assert (is_absolute out_file);

  let typedtree = read_cmt cmt_file in

  (* Convert the typedtree into an Osiris AST. The structure of the program is
     unchanged. The only two differences between the Coq and OCaml versions of
     the Osiris ASTs are:
     - the OCaml AST contains an additional constructor for module-expressions,
       expressions, etc. to represent parts of the AST which will be put in
       different top-level Coq edfinitions.
     - while the Coq AST contains several ad-hoc lists, the OCaml AST does not:
       native lists are used every time.
       This will also help with the translation: one can then use the syntactic
       sugar defined in [theories/lang/sugar.v]. *)
  let oast = Translate.typedtree ("_" ^ module_name) typedtree in

  (* Break down the AST into pieces according to the user-specified
     splitting-strategy.
     Current supported strategies are:
     - NoSplit
     Soon to be added strategies are:
     - SplitTopLevelBindings
     - SplitSubModules
     - ...
     It should be possible to apply several splitting strategies in a row:
     to pass [-split-top-level -split-sub-modules] to the command line should:
     1. split on top-level bindings
     2. in every pieces, split on sub-modules

     Note: the order in which the arguments are provided might influence the
           end-result (eg. the final definitions might appear in a different
           order).
           Therefore, once a strategy is chosen for a file which git tracks, it
           should not be changed unless necessary as it might produce large
           unnecessary diffs.

     It is the function [split] that will choose names for the auxiliary
     definitions. *)
  let dag = Split.split Settings.splitting_strategy oast in

  (* [Preprint.definition_of_ast] provides a translation that works in a similar
     manner than the first translator:
     converts the AST into:
     - [EPlain s], which should be seen as a plain string [s] to print in the
       final document
     - [EConstr (c, [e1; ...; en])], which should be printed as
       [c (e1) ... (en)] in the final document.
     - [EList (c; [e1; ...; en])], which did not exist in the first translator.
       It should be printed as [c [e1; ...; en]], which is useful to use
       syntactic sugar. *)
  let dag =
    let open Syntax in
    DAG.map (fun def ->
      let (t, m) = Preprint.definition_of_ast def.rhs in
      def.lhs, t, m
    ) dag
  in

  let dag = Pp.pretty_printer dag in

  (* Finally, pretty-print the generated definitions into the output file
     provided on the command line.
     This pretty-printer is similar of that of the first translator, except that
     it should also print [EList _].
   *)
  print out_file dag

(* -------------------------------------------------------------------------- *)

(* The path of the output file (.v) is computed based on the path of the
   source file (.ml). The latter is relative to the dune root directory.
   It typically begins with something like [_build/default/], so we chop
   the first two segments of it. *)

let output_file_path ml_file =
  assert (is_relative ml_file);
  ml_file
  |> remove_extension                        (* remove [.ml] or [.ml-gen] *)
  |> add_suffix ".v"                         (* add [.v] *)
  |> drop 2
  |> concat Settings.out                     (* make this an absolute path *)
  |> map_basename (add_prefix Settings.mark) (* add mark to file name *)

(* -------------------------------------------------------------------------- *)

(* Obtain a table of the modules in this project. *)

let table =
  Dune.describe Settings.root

let process m =
  say "Processing module: %s\n" m;
  (* Find its .ml file, relative to the dune root directory. *)
  let ml_file = Dune.impl m table in
  (* Find its .cmt file, relative to the dune root directory. *)
  let cmt_file = Dune.cmt m table in
  say "    .cmt file: %s\n" cmt_file;
  (* Construct the absolute path of the input (.cmt) file. *)
  let cmt_file = concat Settings.root cmt_file in
  (* Construct the absolute path of the output (.v) file. *)
  let v_file = output_file_path ml_file in
  say "  output file: %s\n" v_file;
  (* Translate this file. *)
  translate_one_file m v_file cmt_file

let () =
  (* Check the list of modules that was passed on the command line. *)
  match Settings.modules with
  | `All ->
      (* Process all modules. *)
      Dune.M.iter (fun m _ -> process m) table
  | `Modules ms ->
      (* Process only the modules named on the command line. *)
      List.iter process ms
