open Printf
open Fail
let say = Settings.say
let concat, is_relative, remove_extension =
  Filename.(concat, is_relative, remove_extension)
open FilenameExtra
open SysExtra

(* -------------------------------------------------------------------------- *)

(* Reading a .cmt file and extracting the typed tree. *)

(* https://github.com/ocaml/ocaml/blob/trunk/file_formats/cmt_format.mli *)

let read (cmt_file : filename) : Typedtree.structure =
  assert (is_absolute cmt_file);
  let open Cmt_format in
  match read_cmt cmt_file with
  | exception Cmt_format.(Error (Not_a_typedtree _))
  | exception Cmi_format.(Error (Not_an_interface _)) ->
      fail "Invalid .cmt file: %s\n" cmt_file
  | { cmt_annots; _ } ->
      match cmt_annots with
      | Implementation t ->
          t
      | _ ->
          fail "This .cmt file does not contain a typed tree: %s\n" cmt_file

(* -------------------------------------------------------------------------- *)

(* Writing a series of definitions to a Coq file. *)

let print (out_file : filename) (defs : Coq.defs) =
  ensure_parent_directory_exists out_file;
  let f = open_out out_file in
  fprintf f "(* This file has been generated by Osiris. Do not edit. *)\n\n";
  fprintf f "From osiris Require Import osiris.\n\n";
  let ribbon = 1.0
  and width = 80 in
  PPrint.ToChannel.pretty ribbon width f (Print.defs defs);
  close_out f

(* -------------------------------------------------------------------------- *)

(* Translating one file. *)

module Translate = Translate.Make(Settings)

let translate ml_file cmt_file out_file =
  assert (is_absolute ml_file);
  assert (is_absolute cmt_file);
  assert (is_absolute out_file);

  (* Read the .ml file, which contains the OCaml source code.
     This is used only for decorations, which carry substrings
     extracted out of the source code.  *)
  let osource : string option =
    if Settings.decorate then Some (IO.read_whole_file ml_file) else None
  in

  (* Read the .cmt file, which contains a typed OCaml AST. *)
  let u : Typedtree.structure = read cmt_file in

  (* Convert this typed OCaml AST to an Osiris AST. *)
  let u : Syntax.mexpr = Translate.unit osource u in

  let u : Coq.expression = Coqify.module_expression u in
  let def : Coq.def = Coq.{ lhs = "__main"; rhs = u } in
  let defs = Cut.cut def in

  (* Finally, pretty-print the generated definitions into the output file
     provided on the command line. *)
  print out_file defs

(* -------------------------------------------------------------------------- *)

(* The path of the output file (.v) is computed based on the path of the
   source file (.ml). The latter is relative to the dune root directory.
   It typically begins with something like [_build/default/], so we drop
   its first two segments. *)

let output_file_path ml_file =
  assert (is_relative ml_file);
  ml_file
  |> remove_extension                        (* remove [.ml] or [.ml-gen] *)
  |> add_suffix ".v"                         (* add [.v] *)
  |> drop 2                                  (* drop first two segments *)
  |> concat Settings.out                     (* make this an absolute path *)
  |> map_basename (add_prefix Settings.mark) (* add mark to file name *)

(* -------------------------------------------------------------------------- *)

(* Obtain a table of the modules in this project. *)

let table =
  Dune.describe Settings.root

(* -------------------------------------------------------------------------- *)

(* Processing one module. *)

let process m =
  say "Processing module: %s\n" m;
  (* Find the [.ml] file, relative to the dune root directory. *)
  let ml_file = Dune.impl m table in
  (* Find the [.cmt] file, relative to the dune root directory. *)
  let cmt_file = Dune.cmt m table in
  say "    .cmt file: %s\n" cmt_file;
  (* Construct the absolute path of the output [.v] file. *)
  let v_file = output_file_path ml_file in
  say "  output file: %s\n" v_file;
  (* Construct the absolute path of the input [.ml] file. *)
  let ml_file = concat Settings.root ml_file in
  (* Construct the absolute path of the input [.cmt] file. *)
  let cmt_file = concat Settings.root cmt_file in
  (* Translate this file. *)
  translate ml_file cmt_file v_file

(* -------------------------------------------------------------------------- *)

(* Main. *)

let () =
  (* Check the list of modules that was passed on the command line. *)
  match Settings.modules with
  | `All ->
      (* Process all modules. *)
      Dune.M.iter (fun m _ -> process m) table
  | `Modules ms ->
      (* Process only the modules named on the command line. *)
      List.iter process ms
