(executable
  (package osiris-interpreter)
  (public_name osiris-interpreter)
  (name interp)
  (flags :standard "-w" "A-40-41-42-44-45")
  (libraries translatorlib extracted)
)

(rocq.theory
  (package osiris-interpreter)
  (name osiris.interp)
  (generate_project_file)
  (theories osiris osiris.stdlib)
)
