(rule
  (mode promote)
  (targets stateful.v)
  (deps    (:gen ../../../translator/bin/main.exe)
           (:src ../../ml/counter_examples/stateful.ml))
  (action
    (progn
      (run %{gen} -no-split -mode ml -ml %{src} -root ../../../../.. -out %{targets}))))

(rule
  (mode promote)
  (targets stateless.v)
  (deps    (:gen ../../../translator/bin/main.exe)
           (:src ../../ml/counter_examples/stateless.ml))
  (action
    (progn
      (run %{gen} -no-split -mode ml -ml %{src} -root ../../../../.. -out %{targets}))))

(rule
  (mode promote)
  (targets stateful_uc.v)
  (deps    (:gen ../../../translator/bin/main.exe)
           (:src ../../ml/counter_examples/stateful_uc.ml))
  (action
    (progn
      (run %{gen} -no-split -mode ml -ml %{src} -root ../../../../.. -out %{targets}))))

(rule
  (mode promote)
  (targets stateless_uc.v)
  (deps    (:gen ../../../translator/bin/main.exe)
           (:src ../../ml/counter_examples/stateless_uc.ml))
  (action
    (progn
      (run %{gen} -no-split -mode ml -ml %{src} -root ../../../../.. -out %{targets}))))
