From iris.proofmode Require Import base proofmode classes.
From iris.base_logic.lib Require Import fancy_updates.
From iris.bi Require Import weakestpre.
From iris.prelude Require Import options.
Import uPred.

From osiris Require Import osiris.
From osiris.libs Require Import
     Stdlib
     Stdlib.int
.

Local Notation VClo1 body :=
  (
    VClo EnvNil $
         AnonFun "x" $
         body (EVar "x")
  ).

Local Notation VClo2 body :=
  (
    VClo EnvNil $
         AnonFun "x" $
         EFun1Var "y" $
         (body (EVar "x") (EVar "y"))
  ).

Local Notation dummy := (VClo EnvNil $ AnonFun "_" EUnit).

Local Fixpoint EnvAppend η η' :=
  match η with
  | EnvNil => η'
  | EnvCons x v η =>
      EnvAppend η $ EnvCons x v η'
  end.
Local Infix ":::" := (EnvAppend).


Section ExternalsDef.
  (* This section describes the supported and yet to be supported external
     functions. *)

  (* ------------------------------------------------------------------------ *)
  (* Real external functions. *)

  (* None of them are supported yet. They are replaced by dummy values. *)
  Definition Externals__caml_format_int : val := dummy.
  Definition Externals__caml_hash : val := dummy.

  Definition externals_real : env :=
    EnvCons "caml_format_int" Externals__caml_format_int $
            EnvCons "caml_hash" Externals__caml_hash $
            EnvNil.

  (* ------------------------------------------------------------------------ *)
  (* Content of Externals used in [stdlib/int.ml]. *)

  Definition Externals__negint : val := VClo1 EIntNeg.
  Definition Externals__addint : val := VClo2 EIntAdd.
  Definition Externals__subint : val := VClo2 EIntSub.
  Definition Externals__mulint : val := VClo2 EIntMul.
  Definition Externals__divint : val := VClo2 EIntDiv.
  Definition Externals__modint : val := VClo2 EIntMod.
  Definition Externals__succint : val :=
    VClo1 (fun x => EIntAdd x (EInt 1)).
  Definition Externals__predint : val :=
    VClo1 (fun x => EIntSub x (EInt 1)).

  (* The following names are used in [stdlib/int.ml], but they are not supported
     yet: - %andint
          - %orint
          - %xorint
          - %lslint
          - %asrint
          - %lsrint
          - %floatofint
          - %intoffloat
          - caml_format_int
          - caml_hash
     They are replaced by a dummy function. *)
  Definition Externals__andint : val := dummy.
  Definition Externals__orint : val := dummy.
  Definition Externals__xorint : val := dummy.
  Definition Externals__lslint : val := dummy.
  Definition Externals__asrint : val := dummy.
  Definition Externals__lsrint : val := dummy.
  Definition Externals__floatofint : val := dummy.
  Definition Externals__intoffloat : val := dummy.

  Definition externals_int : env :=
        EnvCons "%negint" Externals__negint $
                EnvCons "%addint" Externals__addint $
                EnvCons "%subint" Externals__subint $
                EnvCons "%mulint" Externals__mulint $
                EnvCons "%divint" Externals__divint $
                EnvCons "%modint" Externals__modint $
                EnvCons "%succint" Externals__succint $
                EnvCons "%predint" Externals__predint $
                EnvCons "%andint" Externals__andint $
                EnvCons "%orint" Externals__orint $
                EnvCons "%xorint" Externals__xorint $
                EnvCons "%lslint" Externals__lslint $
                EnvCons "%asrint" Externals__asrint $
                EnvCons "%lsrint" Externals__lsrint $
                EnvCons "%floatofint" Externals__floatofint $
                EnvCons "%intoffloat" Externals__intoffloat $
                EnvNil.

  (* ------------------------------------------------------------------------ *)

  Definition Externals :=
    VStruct $
            externals_real :::
            externals_int
  .

  Definition HasExternals (η : env) : Prop :=
    lookup_name η "Externals" = Ret Externals.

End ExternalsDef.

(* -------------------------------------------------------------------------- *)

(* The file [libs/Stdlib/Stdlib.v] is *not* auto-generated by the translator yet
   yet, and the module Stdlib defined there does not see [Externals] defined
   above. Hence, we redefine [Stdlib] (or at least a big-enough fragment of it
   here. This should be safely removed once the translator is used on
   [Stdlib]. *)

Section StdlibDef.

  (* Basic arithmetic. *)

  Definition Stdlib__add := VClo2 EIntAdd.
  Definition Stdlib__sub := VClo2 EIntSub.
  Definition Stdlib__neg := VClo1 EIntNeg.
    Definition Stdlib__lt : val := VClo2 EOpLt.
    Definition Stdlib__le : val := VClo2 EOpLe.
    Definition Stdlib__gt : val := VClo2 EOpGt.
    Definition Stdlib__ge : val := VClo2 EOpGe.


  Definition stdlib_arith :=
    EnvCons "+" Stdlib__add $
            EnvCons "-" Stdlib__sub $
            EnvCons "<" Stdlib__lt $
            EnvCons "<=" Stdlib__le $
            EnvCons ">" Stdlib__gt $
            EnvCons ">=" Stdlib__ge $
            EnvCons "~-" Stdlib__neg $
            EnvNil.

  (* ------------------------------------------------------------------------ *)

  Definition Stdlib__lsr := VClo2 EIntAdd.

  Definition Stdlib__eq := VClo2 EOpEq.
  Definition Stdlib__ne : val := VClo2 EOpNe.
  Axiom Stdlib__compare : val.

  Definition stdlib_misc :=
    EnvCons "lsr" Stdlib__lsr $
            EnvCons "=" Stdlib__eq $
            EnvCons "<>" Stdlib__ne $
            EnvCons "compare" Stdlib__compare $
            EnvNil.

  (* ------------------------------------------------------------------------ *)

  Definition Stdlib :=
    VStruct $
            stdlib_arith :::
            stdlib_misc.

  Definition HasStdlib (η : env) : Prop :=
    lookup_name η "Stdlib" = Ret Stdlib.
End StdlibDef.

(* -------------------------------------------------------------------------- *)

Section int_spec.
  Context `{!osirisGS Σ}.

  Context (η : env).
  Context (Hexternals : HasExternals η).
  Context (Hstdlib : HasStdlib η).

  Definition dummy_spec (_ : val) : iProp Σ := □ emp%I.

  Definition int_constant (i : Z) (v : val) : iProp Σ := □ ⌜ v = #i⌝.

  Definition binop_helper (f : Z → Z → Z) (v : val) : iProp Σ :=
    □ ∀ (i : Z),
    WP call v #i {{
          λ v,
            ∀ (j : Z), WP call v #j {{ int_constant (f i j) }} }}.

  Definition monop_helper (f : Z → Z) (v : val) : iProp Σ :=
    □ ∀ (i : Z),
    WP call v #i {{ int_constant (f i) }}.

  Definition monop_helper' (f : Z → Z) (P : Z → iProp Σ) (v : val) : iProp Σ :=
    □ ∀ (i : Z),
    P i -∗
    WP call v #i {{ int_constant (f i) }}.

  Definition binop_helper' (f : Z → Z → Z)
             (Pi Pj : Z → iProp Σ)
             (v : val) : iProp Σ :=
    □ ∀ (i : Z),
    WP call v #i {{
          λ v,
            ∀ (j : Z),
            Pi i -∗ Pj j -∗
            WP call v #j {{ int_constant (f i j) }} }}.

  Definition representable' (i : Z) : iProp Σ := ⌜representable i⌝.
  Definition representable_nonO' (i : Z) : iProp Σ :=
    ⌜i <> 0%Z ∧ representable i⌝.

  Definition neg_spec (v : val) : iProp Σ :=
    □ ∀ (i : Z), WP call v #i {{ int_constant (-i) }}.

  Definition add_spec := binop_helper Z.add.
  Definition sub_spec := binop_helper Z.sub.
  Definition mul_spec := binop_helper Z.mul.

  Definition div_spec :=
    binop_helper' Z.quot representable' representable_nonO'.
  Definition rem_spec :=
    binop_helper' Z.rem representable' representable_nonO'.

  Definition succ_spec := monop_helper Z.succ.
  Definition pred_spec := monop_helper Z.pred.
  Definition abs_spec := monop_helper' Z.abs representable'.
  Definition max_int_spec := dummy_spec.
  Definition min_int_spec := dummy_spec.

  Definition Int_spec : @spec_env Σ :=
    [
      (* On Constants. *)
      ("zero", int_constant 0)         ;
      ("one", int_constant 1 )         ;
      ("minus_one", int_constant (-1)) ;

      (* On simple Arithmetic Operations. *)
      ("neg",     neg_spec)     ;
      ("add",     add_spec)     ;
      ("sub",     sub_spec)     ;
      ("mul",     mul_spec)     ;
      ("div",     div_spec)     ;
      ("rem",     rem_spec)     ;
      ("succ",    succ_spec)    ;
      ("pred",    pred_spec)    ;
      ("abs",     abs_spec)     ;
      ("max_int", max_int_spec) ;
      ("min_int", min_int_spec)


      (* TODO: Logical Operations. *)
      (* TODO: Shifts. *)
      (* TODO: Comparison. *)

      (* Will not be specified (at least yet):
         [to_float], [of_float], [format_int], [seeded_hash_param] *)
    ]
  .

  Lemma _Int_spec :
    ⊢ WP eval_mexpr η _Int {{ module_spec Int_spec }}.
  Proof using Hexternals Hstdlib osirisGS0 Σ η.

    Local Tactic Notation "specCst" constr(name) constr(spec) :=
      let id := fresh in
      oSpecify name spec id "#?"! ; first done.
    Local Tactic Notation "specBin" constr(sbname) constr(sbspec) :=
      let id := fresh in
      oSpecify sbname sbspec id "#?"! ;
      [ iIntros "!>"(?);
              @oCall unfold; iIntros(?);
        by @oCall unfold | ].
    Local Tactic Notation "specTrivial" constr(sbname) :=
      let id := fresh in
      oSpecify sbname dummy_spec id "#?"! ;
      first done.

    specCst "zero" (int_constant 0).
    specCst "one" (int_constant 1).
    specCst "minus_one" (int_constant (-1)).

    oSpecify "neg" neg_spec vneg "#?"!.
    { iIntros (i) "!>". by wp. }

    specBin "add" add_spec.
    specBin "sub" sub_spec.
    specBin "mul" mul_spec.

    (* TODO... *)
    oSpecify "div" div_spec vdiv "#Hdiv"!.
    { iIntros "!>" (i). @oCall unfold.
      iIntros (j Hi [Hj Hjnon0]). @oCall unfold.
      wp_bind.
      unfold check_div_by_zero.
      rewrite eq_repr_repr; try representable.
      replace (j =? 0) with false; last first.
      { symmetry; by rewrite Z.eqb_neq. }
      wp. iModIntro.
      iPureIntro.
      cbn;  f_equal.
      with_strategy transparent [divs] unfold divs.
      rewrite M.divs_repr_repr; first reflexivity;
        unfold representable in *; representable. }

    oSpecify "rem" rem_spec vrem "#Hrem"!.
    { iIntros"!>" (i). @oCall unfold.
      iIntros(j Hi [Hj HjnonO]). @oCall unfold.
      wp_bind.
      unfold check_div_by_zero.
      rewrite eq_repr_repr; try representable.
      replace (j =? 0) with false; last first.
      { symmetry; by rewrite Z.eqb_neq. }
      wp. iModIntro.
      iPureIntro.
      cbn;  f_equal.
      with_strategy transparent [mods] unfold mods.
      rewrite M.mods_repr_repr; first reflexivity;
        unfold representable in *; representable. }

    oSpecify "succ" succ_spec vsucc "#Hsucc"!.
    { iIntros"!>"(i). @oCall unfold.
      iIntros"!>". equality. }

    oSpecify "pred" pred_spec vpred "#Hpred"!.
    { iIntros"!>"(i). @oCall unfold.
      iIntros"!>". equality. }

    oSpecify "abs" abs_spec vabs "#Habs"!.
    { iIntros"!>"(i Hi). @oCall unfold.
      wp_bind; wp_continue.
      rewrite lt_repr_repr; try representable.
      destruct (Z.compare i 0)%Z eqn:E.
      { (* i = 0 *)
        apply Z.compare_eq in E as ->.
        wp. equality. }
      { unfold Z.ltb. rewrite E.
        wp.
        replace (Z.abs i) with (-i); first equality.
        rewrite Z.compare_lt_iff in E; lia. }
      { unfold Z.ltb. rewrite E.
        wp.
        replace (Z.abs i) with i; first equality.
        rewrite Z.compare_gt_iff in E; lia. } }

    (* FIXME: [max_int] is evaluated to 0! *)
    oSpecify "max_int" (int_constant 0) vmax_int "#Hmax_int"!; first done.
    iPoseProof "Hmax_int" as "->".
    specTrivial "min_int".

    (* TODO: Add these constructs as primitives in [expr]. *)
    specTrivial "logand".
    specTrivial "logor".
    specTrivial "logxor".
    specTrivial "lognot".
    specTrivial "shift_left".
    specTrivial "shift_right".
    specTrivial "shift_right_logical".

    (* TODO. *)
    specTrivial "equal".
    specTrivial "compare".
    specTrivial "min".
    specTrivial "max".

    specTrivial "to_float".
    specTrivial "of_float".
    specTrivial "format_int".
    specTrivial "to_string".
    specTrivial "seeded_hash_param".
    specTrivial "seeded_hash".
    specTrivial "hash".

    wp_module_spec.

  Admitted.
End int_spec.
