(coq.theory
  (package osiris)
  (theories osiris)
  (name test))

(rule
  (targets incr.v)
  (mode promote)
  (deps    (:gen ../../translator/bin/main.exe)
           (:src ../ml/incr.ml))
  (action
    (with-stdout-to
      %{targets}
      (progn
        (run %{ocamlc} -bin-annot %{src})
        (run %{gen} -ml %{src} -verbose)))))

(rule
  (targets arith.v)
  (mode promote)
  (deps    (:gen ../../translator/bin/main.exe)
           (:src ../ml/arith.ml))
  (action
    (with-stdout-to
      %{targets}
      (progn
        (run %{ocamlc} -bin-annot %{src})
        (run %{gen} -ml %{src} -verbose)))))

(rule
  (targets records.v)
  (mode promote)
  (deps    (:gen ../../translator/bin/main.exe)
           (:src ../ml/records.ml))
  (action
    (with-stdout-to
      %{targets}
      (progn
        (run %{ocamlc} -bin-annot %{src})
        (run %{gen} -ml %{src} -verbose)))))
