(coq.theory
  (package osiris)
  (theories osiris)
  (modules :standard \ efficiency)
  (name test))

(rule
  (targets incr.v)
  (mode promote)
  (deps    (:gen ../../translator/bin/main.exe)
           (:src ../ml/incr.ml))
  (action
    (ignore-stderr
      (with-stdout-to
        %{targets}
        (progn
          (run %{ocamlc} -bin-annot %{src})
          (run %{gen} -ml %{src} -verbose))))))

(rule
  (targets arith.v)
  (mode promote)
  (deps    (:gen ../../translator/bin/main.exe)
           (:src ../ml/arith.ml))
  (action
    (ignore-stderr
      (with-stdout-to
        %{targets}
        (progn
          (run %{ocamlc} -bin-annot %{src})
          (run %{gen} -ml %{src} -verbose))))))

(rule
  (targets records.v)
  (mode promote)
  (deps    (:gen ../../translator/bin/main.exe)
           (:src ../ml/records.ml))
  (action
    (ignore-stderr
      (with-stdout-to
        %{targets}
        (progn
          (run %{ocamlc} -bin-annot %{src})
          (run %{gen} -ml %{src} -verbose))))))
