(include_subdirs qualified)
(coq.theory
  (package osiris)
  (theories osiris osiris.libs)
  (name test))

(rule
  (targets incr.v)
  (mode promote)
  (deps    (:gen ../../translator/bin/main.exe)
           (:src ../ml/incr.ml))
  (action
    (progn
       (run %{ocamlc} -bin-annot %{src})
       (run %{gen} -mode cmt -cmt ../ml/incr.cmt -out %{targets}))))

(rule
  (targets arith.v)
  (mode promote)
  (deps    (:gen ../../translator/bin/main.exe)
           (:src ../ml/arith.ml))
  (action
    (progn
      (run %{ocamlc} -bin-annot %{src})
      (run %{gen} -mode cmt -cmt ../ml/arith.cmt -out %{targets}))))

(rule
  (targets splay.v)
  (mode promote)
  (deps    (:gen ../../translator/bin/main.exe)
           (:src ../ml/splay.ml))
  (action
    (progn
      (run %{ocamlc} -bin-annot %{src})
      (run %{gen} -mode cmt -cmt ../ml/splay.cmt -out %{targets}))))
