(* Arity-1 primitives *)
external neg     : int -> int            = "%negint"
external succ_   : int -> int            = "%succint"
external pred_   : int -> int            = "%predint"
external not_    : bool -> bool          = "%boolnot"
external arr_len : 'a array -> int       = "%array_length"

(* Arity-2 primitives *)
external add     : int -> int -> int     = "%addint"
external sub     : int -> int -> int     = "%subint"
external mul     : int -> int -> int     = "%mulint"
external div_    : int -> int -> int     = "%divint"
external mod_    : int -> int -> int     = "%modint"
external land_   : int -> int -> int     = "%andint"
external lor_    : int -> int -> int     = "%orint"
external lxor_   : int -> int -> int     = "%xorint"
external lsl_    : int -> int -> int     = "%lslint"
external lsr_    : int -> int -> int     = "%lsrint"
external asr_    : int -> int -> int     = "%asrint"
external eq_     : 'a -> 'a -> bool      = "%equal"
external ne_     : 'a -> 'a -> bool      = "%notequal"
external lt_     : 'a -> 'a -> bool      = "%lessthan"
external gt_     : 'a -> 'a -> bool      = "%greaterthan"
external le_     : 'a -> 'a -> bool      = "%lessequal"
external ge_     : 'a -> 'a -> bool      = "%greaterequal"
external phys_eq : 'a -> 'a -> bool      = "%eq"
external arr_get : 'a array -> int -> 'a = "%array_safe_get"
external arr_make : int -> 'a -> 'a array = "caml_array_make"

(* Arity-3 primitives *)
external arr_set : 'a array -> int -> 'a -> unit = "%array_safe_set"
