(rule
  (targets code.v)
  ; Do not promote for now. (mode promote)
  (deps    (:gen ../../../../translator/bin/main.exe)
           (:src ../../../ml/Stdlib/list.ml))
  (action
    (progn
      (run %{ocamlc} -bin-annot %{src})
      (run %{gen} -mode cmt -cmt ../../../ml/Stdlib/list.cmt -out %{targets}))))
