(* This file has been generated by Osiris. Do not edit. *)

From osiris Require Import osiris.

Definition __branches0 :=
  [
    Branch (CVal (PData "false" [])) (deco "0." (EFloat (0)%float));
    Branch (CVal (PData "true" [])) (deco "1." (EFloat (1)%float))
  ].

Definition __fun1 := AnonFunction __branches0.

Definition __branches2 :=
  [
    Branch (CVal (PData "false" [])) (deco """false""" (EString "false"));
    Branch (CVal (PData "true" [])) (deco """true""" (EString "true"))
  ].

Definition __fun3 := AnonFunction __branches2.

Definition __fun4 :=
  AnonFun "x" (
    deco "seeded_hash_param 10 100 seed x" (
      EApp (
        EApp (
          EApp (
            EApp (deco "seeded_hash_param" (EPath [ "seeded_hash_param" ])) (
              deco "10" (EInt 10)
            )
          ) (deco "100" (EInt 100))
        ) (deco "seed" (EPath [ "seed" ]))
      ) (deco "x" (EPath [ "x" ]))
    )
  ).

Definition __fun5 := AnonFun "seed" (EAnonFun __fun4).

Definition __fun6 :=
  AnonFun "x" (
    deco "seeded_hash_param 10 100 0 x" (
      EApp (
        EApp (
          EApp (
            EApp (deco "seeded_hash_param" (EPath [ "seeded_hash_param" ])) (
              deco "10" (EInt 10)
            )
          ) (deco "100" (EInt 100))
        ) (deco "0" (EInt 0))
      ) (deco "x" (EPath [ "x" ]))
    )
  ).

Definition __main :=
  MStruct [
    ILet [
      Binding (PAlias PAny "equal") (deco "( = )" (EPath [ "=" ]))
    ];
    ILet [
      Binding (PAlias PAny "compare") (
        deco "Stdlib.compare" (EPath [ "Stdlib"; "compare" ])
      )
    ];
    ILet [
      Binding (PVar "to_float") (
        deco "function false -> 0. | true -> 1." (EAnonFun __fun1)
      )
    ];
    ILet [
      Binding (PVar "to_string") (
        deco "function false ... true -> ""true""" (EAnonFun __fun3)
      )
    ];
    ILet [
      Binding (PVar "seeded_hash") (
        deco "seed x = seeded...m 10 100 seed x" (EAnonFun __fun5)
      )
    ];
    ILet [
      Binding (PVar "hash") (
        deco "x = seeded_hash_param 10 100 0 x" (EAnonFun __fun6)
      )
    ]
  ].

