(* This file has been generated by Osiris. Do not edit. *)

From osiris Require Import osiris.

Definition __branches0 :=
  [
    Branch (CVal (PData "Float16" [])) (deco "2" (EInt 2));
    Branch (CVal (PData "Float32" [])) (deco "4" (EInt 4));
    Branch (CVal (PData "Float64" [])) (deco "8" (EInt 8));
    Branch (CVal (PData "Int8_signed" [])) (deco "1" (EInt 1));
    Branch (CVal (PData "Int8_unsigned" [])) (deco "1" (EInt 1));
    Branch (CVal (PData "Int16_signed" [])) (deco "2" (EInt 2));
    Branch (CVal (PData "Int16_unsigned" [])) (deco "2" (EInt 2));
    Branch (CVal (PData "Int32" [])) (deco "4" (EInt 4));
    Branch (CVal (PData "Int64" [])) (deco "8" (EInt 8));
    Branch (CVal (PData "Int" [])) (
      deco "Sys.word_size / 8" (
        EIntDiv (deco "Sys.word_size" (EPath [ "Sys"; "word_size" ])) (
          deco "8" (EInt 8)
        )
      )
    );
    Branch (CVal (PData "Nativeint" [])) (
      deco "Sys.word_size / 8" (
        EIntDiv (deco "Sys.word_size" (EPath [ "Sys"; "word_size" ])) (
          deco "8" (EInt 8)
        )
      )
    );
    Branch (CVal (PData "Complex32" [])) (deco "8" (EInt 8));
    Branch (CVal (PData "Complex64" [])) (deco "16" (EInt 16));
    Branch (CVal (PData "Char" [])) (deco "1" (EInt 1))
  ].

Definition __fun1 := AnonFunction __branches0.

Definition __exp2 :=
  EApp (
    EApp (EApp (deco "set" (EPath [ "set" ])) (deco "arr" (EPath [ "arr" ]))) (
      deco "idx" (EPath [ "idx" ])
    )
  ) (
    deco "(f idx)" (
      EApp (deco "f" (EPath [ "f" ])) (deco "idx" (EPath [ "idx" ]))
    )
  ).

Definition __exp3 :=
  EApp (
    EApp (
      EApp (
        EApp (
          EApp (deco "cloop" (EPath [ "cloop" ])) (deco "arr" (EPath [ "arr" ]))
        ) (deco "idx" (EPath [ "idx" ]))
      ) (deco "f" (EPath [ "f" ]))
    ) (deco "(succ col)" (EIntAdd (deco "col" (EPath [ "col" ])) (EInt 1)))
  ) (deco "max" (EPath [ "max" ])).

Definition __exp4 :=
  ESeq (
    deco "idx.(col) <- j" (
      EApp (
        EApp (
          EApp (deco "idx.(col) <- j" (EPath [ "Array"; "set" ])) (
            deco "idx" (EPath [ "idx" ])
          )
        ) (deco "col" (EPath [ "col" ]))
      ) (deco "j" (EPath [ "j" ]))
    )
  ) (deco "cloop arr idx f (succ col) max" __exp3).

Definition __exp5 :=
  EFor "j" (deco "0" (EInt 0)) (
    deco "pred max.(col)" (
      EIntSub (
        deco "max.(col)" (
          EApp (
            EApp (deco "max.(col)" (EPath [ "Array"; "get" ])) (
              deco "max" (EPath [ "max" ])
            )
          ) (deco "col" (EPath [ "col" ]))
        )
      ) (EInt 1)
    )
  ) (deco "idx.(col) <- j;... (succ col) max" __exp4).

Definition __fun6 :=
  AnonFun "max" (
    deco "if col = Array....c col) max done" (
      EIfThenElse (
        deco "col = Array.length idx" (
          EOpEq (deco "col" (EPath [ "col" ])) (
            deco "Array.length idx" (
              EApp (deco "Array.length" (EPath [ "Array"; "length" ])) (
                deco "idx" (EPath [ "idx" ])
              )
            )
          )
        )
      ) (deco "set arr idx (f idx)" __exp2) (
        deco "for j = 0 to pr...c col) max done" __exp5
      )
    )
  ).

Definition __fun7 := AnonFun "col" (EAnonFun __fun6).

Definition __fun8 := AnonFun "f" (EAnonFun __fun7).

Definition __fun9 := AnonFun "idx" (EAnonFun __fun8).

Definition __bindings10 :=
  [
    RecBinding "cloop" (AnonFun "arr" (EAnonFun __fun9))
  ].

Definition __exp11 :=
  EApp (
    EApp (EApp (deco "set" (EPath [ "set" ])) (deco "arr" (EPath [ "arr" ]))) (
      deco "idx" (EPath [ "idx" ])
    )
  ) (
    deco "(f idx)" (
      EApp (deco "f" (EPath [ "f" ])) (deco "idx" (EPath [ "idx" ]))
    )
  ).

Definition __exp12 :=
  EApp (
    EApp (
      EApp (
        EApp (
          EApp (deco "floop" (EPath [ "floop" ])) (deco "arr" (EPath [ "arr" ]))
        ) (deco "idx" (EPath [ "idx" ]))
      ) (deco "f" (EPath [ "f" ]))
    ) (deco "(pred col)" (EIntSub (deco "col" (EPath [ "col" ])) (EInt 1)))
  ) (deco "max" (EPath [ "max" ])).

Definition __exp13 :=
  ESeq (
    deco "idx.(col) <- j" (
      EApp (
        EApp (
          EApp (deco "idx.(col) <- j" (EPath [ "Array"; "set" ])) (
            deco "idx" (EPath [ "idx" ])
          )
        ) (deco "col" (EPath [ "col" ]))
      ) (deco "j" (EPath [ "j" ]))
    )
  ) (deco "floop arr idx f (pred col) max" __exp12).

Definition __exp14 :=
  EFor "j" (deco "1" (EInt 1)) (
    deco "max.(col)" (
      EApp (
        EApp (deco "max.(col)" (EPath [ "Array"; "get" ])) (
          deco "max" (EPath [ "max" ])
        )
      ) (deco "col" (EPath [ "col" ]))
    )
  ) (deco "idx.(col) <- j;... (pred col) max" __exp13).

Definition __fun15 :=
  AnonFun "max" (
    deco "if col < 0 then...d col) max done" (
      EIfThenElse (
        deco "col < 0" (
          EOpLt (deco "col" (EPath [ "col" ])) (deco "0" (EInt 0))
        )
      ) (deco "set arr idx (f idx)" __exp11) (
        deco "for j = 1 to ma...d col) max done" __exp14
      )
    )
  ).

Definition __fun16 := AnonFun "col" (EAnonFun __fun15).

Definition __fun17 := AnonFun "f" (EAnonFun __fun16).

Definition __fun18 := AnonFun "idx" (EAnonFun __fun17).

Definition __bindings19 :=
  [
    RecBinding "floop" (AnonFun "arr" (EAnonFun __fun18))
  ].

Definition __exp20 := EPath [ "arr" ].

Definition __exp21 := EPath [ "arr" ].

Definition __branches22 :=
  [
    Branch (CVal (PData "C_layout" [])) (
      deco "cloop arr (Arra...) f 0 dims; arr" (
        ESeq (
          deco "cloop arr (Arra...len 0) f 0 dims" (
            EApp (
              EApp (
                EApp (
                  EApp (
                    EApp (deco "cloop" (EPath [ "cloop" ])) (
                      deco "arr" (EPath [ "arr" ])
                    )
                  ) (
                    deco "(Array.make dlen 0)" (
                      EApp (
                        EApp (deco "Array.make" (EPath [ "Array"; "make" ])) (
                          deco "dlen" (EPath [ "dlen" ])
                        )
                      ) (deco "0" (EInt 0))
                    )
                  )
                ) (deco "f" (EPath [ "f" ]))
              ) (deco "0" (EInt 0))
            ) (deco "dims" (EPath [ "dims" ]))
          )
        ) (deco "arr" __exp20)
      )
    );
    Branch (CVal (PData "Fortran_layout" [])) (
      deco "floop arr (Arra...dlen) dims; arr" (
        ESeq (
          deco "floop arr (Arra...pred dlen) dims" (
            EApp (
              EApp (
                EApp (
                  EApp (
                    EApp (deco "floop" (EPath [ "floop" ])) (
                      deco "arr" (EPath [ "arr" ])
                    )
                  ) (
                    deco "(Array.make dlen 1)" (
                      EApp (
                        EApp (deco "Array.make" (EPath [ "Array"; "make" ])) (
                          deco "dlen" (EPath [ "dlen" ])
                        )
                      ) (deco "1" (EInt 1))
                    )
                  )
                ) (deco "f" (EPath [ "f" ]))
              ) (
                deco "(pred dlen)" (
                  EIntSub (deco "dlen" (EPath [ "dlen" ])) (EInt 1)
                )
              )
            ) (deco "dims" (EPath [ "dims" ]))
          )
        ) (deco "arr" __exp21)
      )
    )
  ].

Definition __exp23 := EMatch (deco "layout" (EPath [ "layout" ])) __branches22.

Definition __exp24 :=
  ELet [
    Binding (PVar "dlen") (
      deco "Array.length dims" (
        EApp (deco "Array.length" (EPath [ "Array"; "length" ])) (
          deco "dims" (EPath [ "dims" ])
        )
      )
    )
  ] (deco "match layout wi...dlen) dims; arr" __exp23).

Definition __fun25 :=
  AnonFun "f" (
    deco "let arr = creat...dlen) dims; arr" (
      ELet [
        Binding (PVar "arr") (
          deco "create kind layout dims" (
            EApp (
              EApp (
                EApp (deco "create" (EPath [ "create" ])) (
                  deco "kind" (EPath [ "kind" ])
                )
              ) (deco "layout" (EPath [ "layout" ]))
            ) (deco "dims" (EPath [ "dims" ]))
          )
        )
      ] (deco "let dlen = Arra...dlen) dims; arr" __exp24)
    )
  ).

Definition __fun26 := AnonFun "dims" (EAnonFun __fun25).

Definition __branches27 :=
  [
    Branch (CVal (PAlias PAny "layout")) (EAnonFun __fun26)
  ].

Definition __fun28 := AnonFunction __branches27.

Definition __fun29 := AnonFun "kind" (EAnonFun __fun28).

Definition __exp30 :=
  EApp (
    EApp (
      EApp (deco "d.(i) <- nth_dim a i" (EPath [ "Array"; "set" ])) (
        deco "d" (EPath [ "d" ])
      )
    ) (deco "i" (EPath [ "i" ]))
  ) (
    deco "nth_dim a i" (
      EApp (
        EApp (deco "nth_dim" (EPath [ "nth_dim" ])) (deco "a" (EPath [ "a" ]))
      ) (deco "i" (EPath [ "i" ]))
    )
  ).

Definition __exp31 := EPath [ "d" ].

Definition __exp32 :=
  ESeq (
    deco "for i = 0 to n-...th_dim a i done" (
      EFor "i" (deco "0" (EInt 0)) (
        deco "n-1" (EIntSub (deco "n" (EPath [ "n" ])) (deco "1" (EInt 1)))
      ) (deco "d.(i) <- nth_dim a i" __exp30)
    )
  ) (deco "d" __exp31).

Definition __exp33 :=
  ELet [
    Binding (PVar "d") (
      deco "Array.make n 0" (
        EApp (
          EApp (deco "Array.make" (EPath [ "Array"; "make" ])) (
            deco "n" (EPath [ "n" ])
          )
        ) (deco "0" (EInt 0))
      )
    )
  ] (deco "for i = 0 to n-...dim a i done; d" __exp32).

Definition __fun34 :=
  AnonFun "a" (
    deco "let n = num_dim...dim a i done; d" (
      ELet [
        Binding (PVar "n") (
          deco "num_dims a" (
            EApp (deco "num_dims" (EPath [ "num_dims" ])) (
              deco "a" (EPath [ "a" ])
            )
          )
        )
      ] (deco "let d = Array.m...dim a i done; d" __exp33)
    )
  ).

Definition __fun35 :=
  AnonFun "arr" (
    deco "(kind_size_in_b...) 1 (dims arr))" (
      EIntMul (
        deco "(kind_size_in_bytes (kind arr))" (
          EApp (deco "kind_size_in_bytes" (EPath [ "kind_size_in_bytes" ])) (
            deco "(kind arr)" (
              EApp (deco "kind" (EPath [ "kind" ])) (
                deco "arr" (EPath [ "arr" ])
              )
            )
          )
        )
      ) (
        deco "(Array.fold_lef...) 1 (dims arr))" (
          EApp (
            EApp (
              EApp (deco "Array.fold_left" (EPath [ "Array"; "fold_left" ])) (
                deco "( * )" (EPath [ "*" ])
              )
            ) (deco "1" (EInt 1))
          ) (
            deco "(dims arr)" (
              EApp (deco "dims" (EPath [ "dims" ])) (
                deco "arr" (EPath [ "arr" ])
              )
            )
          )
        )
      )
    )
  ).

Definition __fun36 :=
  AnonFun "layout" (
    deco "Genarray.create kind layout [||]" (
      EApp (
        EApp (
          EApp (deco "Genarray.create" (EPath [ "Genarray"; "create" ])) (
            deco "kind" (EPath [ "kind" ])
          )
        ) (deco "layout" (EPath [ "layout" ]))
      ) (deco "[||]" (EArrayLit []))
    )
  ).

Definition __fun37 := AnonFun "kind" (EAnonFun __fun36).

Definition __fun38 :=
  AnonFun "arr" (
    deco "Genarray.get arr [||]" (
      EApp (
        EApp (deco "Genarray.get" (EPath [ "Genarray"; "get" ])) (
          deco "arr" (EPath [ "arr" ])
        )
      ) (deco "[||]" (EArrayLit []))
    )
  ).

Definition __fun39 :=
  AnonFun "arr" (
    deco "Genarray.set arr [||]" (
      EApp (
        EApp (deco "Genarray.set" (EPath [ "Genarray"; "set" ])) (
          deco "arr" (EPath [ "arr" ])
        )
      ) (deco "[||]" (EArrayLit []))
    )
  ).

Definition __fun40 :=
  AnonFun "arr" (
    deco "kind_size_in_bytes (kind arr)" (
      EApp (deco "kind_size_in_bytes" (EPath [ "kind_size_in_bytes" ])) (
        deco "(kind arr)" (
          EApp (deco "kind" (EPath [ "kind" ])) (deco "arr" (EPath [ "arr" ]))
        )
      )
    )
  ).

Definition __exp41 := EPath [ "a" ].

Definition __exp42 :=
  ESeq (
    deco "set a v" (
      EApp (EApp (deco "set" (EPath [ "set" ])) (deco "a" (EPath [ "a" ]))) (
        deco "v" (EPath [ "v" ])
      )
    )
  ) (deco "a" __exp41).

Definition __fun43 :=
  AnonFun "v" (
    deco "let a = create ...t in set a v; a" (
      ELet [
        Binding (PVar "a") (
          deco "create kind layout" (
            EApp (
              EApp (deco "create" (EPath [ "create" ])) (
                deco "kind" (EPath [ "kind" ])
              )
            ) (deco "layout" (EPath [ "layout" ]))
          )
        )
      ] (deco "set a v; a" __exp42)
    )
  ).

Definition __fun44 := AnonFun "layout" (EAnonFun __fun43).

Definition __fun45 := AnonFun "kind" (EAnonFun __fun44).

Definition __fun46 :=
  AnonFun "dim" (
    deco "Genarray.create... layout [|dim|]" (
      EApp (
        EApp (
          EApp (deco "Genarray.create" (EPath [ "Genarray"; "create" ])) (
            deco "kind" (EPath [ "kind" ])
          )
        ) (deco "layout" (EPath [ "layout" ]))
      ) (deco "[|dim|]" (EArrayLit [ deco "dim" (EPath [ "dim" ]) ]))
    )
  ).

Definition __fun47 := AnonFun "layout" (EAnonFun __fun46).

Definition __fun48 := AnonFun "kind" (EAnonFun __fun47).

Definition __fun49 :=
  AnonFun "arr" (
    deco "(kind_size_in_b...r)) * (dim arr)" (
      EIntMul (
        deco "(kind_size_in_bytes (kind arr))" (
          EApp (deco "kind_size_in_bytes" (EPath [ "kind_size_in_bytes" ])) (
            deco "(kind arr)" (
              EApp (deco "kind" (EPath [ "kind" ])) (
                deco "arr" (EPath [ "arr" ])
              )
            )
          )
        )
      ) (
        deco "(dim arr)" (
          EApp (deco "dim" (EPath [ "dim" ])) (deco "arr" (EPath [ "arr" ]))
        )
      )
    )
  ).

Definition __branches50 :=
  [
    Branch (CVal (PData "C_layout" [])) (
      deco "Genarray.slice_left a [|n|]" (
        EApp (
          EApp (deco "Genarray.slice_left" (EPath [ "Genarray"; "slice_left" ])) (
            deco "a" (EPath [ "a" ])
          )
        ) (deco "[|n|]" (EArrayLit [ deco "n" (EPath [ "n" ]) ]))
      )
    );
    Branch (CVal (PData "Fortran_layout" [])) (
      deco "Genarray.slice_right a [|n|]" (
        EApp (
          EApp (
            deco "Genarray.slice_right" (EPath [ "Genarray"; "slice_right" ])
          ) (deco "a" (EPath [ "a" ]))
        ) (deco "[|n|]" (EArrayLit [ deco "n" (EPath [ "n" ]) ]))
      )
    )
  ].

Definition __fun51 :=
  AnonFun "n" (
    deco "match layout a ... t) Genarray.t)" (
      EMatch (
        deco "layout a" (
          EApp (deco "layout" (EPath [ "layout" ])) (deco "a" (EPath [ "a" ]))
        )
      ) __branches50
    )
  ).

Definition __branches52 :=
  [
    Branch (CVal (PAlias PAny "a")) (EAnonFun __fun51)
  ].

Definition __fun53 := AnonFunction __branches52.

Definition __exp54 :=
  EApp (
    EApp (
      EApp (deco "unsafe_set" (EPath [ "unsafe_set" ])) (
        deco "arr" (EPath [ "arr" ])
      )
    ) (deco "i" (EPath [ "i" ]))
  ) (deco "(f i)" (EApp (deco "f" (EPath [ "f" ])) (deco "i" (EPath [ "i" ])))).

Definition __fun55 :=
  AnonFun "f" (
    deco "for i = 0 to pr...rr i (f i) done" (
      EFor "i" (deco "0" (EInt 0)) (
        deco "pred dim" (EIntSub (deco "dim" (EPath [ "dim" ])) (EInt 1))
      ) (deco "unsafe_set arr i (f i)" __exp54)
    )
  ).

Definition __fun56 := AnonFun "dim" (EAnonFun __fun55).

Definition __fun57 := AnonFun "arr" (EAnonFun __fun56).

Definition __exp58 :=
  EApp (
    EApp (
      EApp (deco "unsafe_set" (EPath [ "unsafe_set" ])) (
        deco "arr" (EPath [ "arr" ])
      )
    ) (deco "i" (EPath [ "i" ]))
  ) (deco "(f i)" (EApp (deco "f" (EPath [ "f" ])) (deco "i" (EPath [ "i" ])))).

Definition __fun59 :=
  AnonFun "f" (
    deco "for i = 1 to di...rr i (f i) done" (
      EFor "i" (deco "1" (EInt 1)) (deco "dim" (EPath [ "dim" ])) (
        deco "unsafe_set arr i (f i)" __exp58
      )
    )
  ).

Definition __fun60 := AnonFun "dim" (EAnonFun __fun59).

Definition __fun61 := AnonFun "arr" (EAnonFun __fun60).

Definition __exp62 := EPath [ "arr" ].

Definition __exp63 := EPath [ "arr" ].

Definition __branches64 :=
  [
    Branch (CVal (PData "C_layout" [])) (
      deco "c_init arr dim f; arr" (
        ESeq (
          deco "c_init arr dim f" (
            EApp (
              EApp (
                EApp (deco "c_init" (EPath [ "c_init" ])) (
                  deco "arr" (EPath [ "arr" ])
                )
              ) (deco "dim" (EPath [ "dim" ]))
            ) (deco "f" (EPath [ "f" ]))
          )
        ) (deco "arr" __exp62)
      )
    );
    Branch (CVal (PData "Fortran_layout" [])) (
      deco "fortran_init arr dim f; arr" (
        ESeq (
          deco "fortran_init arr dim f" (
            EApp (
              EApp (
                EApp (deco "fortran_init" (EPath [ "fortran_init" ])) (
                  deco "arr" (EPath [ "arr" ])
                )
              ) (deco "dim" (EPath [ "dim" ]))
            ) (deco "f" (EPath [ "f" ]))
          )
        ) (deco "arr" __exp63)
      )
    )
  ].

Definition __exp65 := EMatch (deco "layout" (EPath [ "layout" ])) __branches64.

Definition __fun66 :=
  AnonFun "f" (
    deco "let arr = creat... arr dim f; arr" (
      ELet [
        Binding (PVar "arr") (
          deco "create kind layout dim" (
            EApp (
              EApp (
                EApp (deco "create" (EPath [ "create" ])) (
                  deco "kind" (EPath [ "kind" ])
                )
              ) (deco "layout" (EPath [ "layout" ]))
            ) (deco "dim" (EPath [ "dim" ]))
          )
        )
      ] (deco "match layout wi... arr dim f; arr" __exp65)
    )
  ).

Definition __fun67 := AnonFun "dim" (EAnonFun __fun66).

Definition __branches68 :=
  [
    Branch (CVal (PAlias PAny "layout")) (EAnonFun __fun67)
  ].

Definition __fun69 := AnonFunction __branches68.

Definition __fun70 := AnonFun "kind" (EAnonFun __fun69).

Definition __branches71 :=
  [
    Branch (CVal (PData "C_layout" [])) (deco "0" (EInt 0));
    Branch (CVal (PData "Fortran_layout" [])) (deco "1" (EInt 1))
  ].

Definition __exp72 :=
  EApp (
    EApp (
      EApp (deco "unsafe_set" (EPath [ "unsafe_set" ])) (
        deco "ba" (EPath [ "ba" ])
      )
    ) (
      deco "(i + ofs)" (
        EIntAdd (deco "i" (EPath [ "i" ])) (deco "ofs" (EPath [ "ofs" ]))
      )
    )
  ) (
    deco "data.(i)" (
      EApp (
        EApp (deco "data.(i)" (EPath [ "Array"; "get" ])) (
          deco "data" (EPath [ "data" ])
        )
      ) (deco "i" (EPath [ "i" ]))
    )
  ).

Definition __exp73 := EPath [ "ba" ].

Definition __exp74 :=
  ESeq (
    deco "for i = 0 to Ar...) data.(i) done" (
      EFor "i" (deco "0" (EInt 0)) (
        deco "Array.length data - 1" (
          EIntSub (
            deco "Array.length data" (
              EApp (deco "Array.length" (EPath [ "Array"; "length" ])) (
                deco "data" (EPath [ "data" ])
              )
            )
          ) (deco "1" (EInt 1))
        )
      ) (deco "unsafe_set ba (i + ofs) data.(i)" __exp72)
    )
  ) (deco "ba" __exp73).

Definition __exp75 :=
  ELet [
    Binding (PVar "ofs") (
      deco "match layout wi...ran_layout -> 1" (
        EMatch (deco "layout" (EPath [ "layout" ])) __branches71
      )
    )
  ] (deco "for i = 0 to Ar...ta.(i) done; ba" __exp74).

Definition __fun76 :=
  AnonFun "data" (
    deco "let ba = create...ta.(i) done; ba" (
      ELet [
        Binding (PVar "ba") (
          deco "create kind lay...ay.length data)" (
            EApp (
              EApp (
                EApp (deco "create" (EPath [ "create" ])) (
                  deco "kind" (EPath [ "kind" ])
                )
              ) (deco "layout" (EPath [ "layout" ]))
            ) (
              deco "(Array.length data)" (
                EApp (deco "Array.length" (EPath [ "Array"; "length" ])) (
                  deco "data" (EPath [ "data" ])
                )
              )
            )
          )
        )
      ] (deco "let ofs = match...ta.(i) done; ba" __exp75)
    )
  ).

Definition __branches77 :=
  [
    Branch (CVal (PAlias PAny "layout")) (EAnonFun __fun76)
  ].

Definition __fun78 := AnonFunction __branches77.

Definition __fun79 := AnonFun "kind" (EAnonFun __fun78).

Definition __fun80 :=
  AnonFun "dim2" (
    deco "Genarray.create... [|dim1; dim2|]" (
      EApp (
        EApp (
          EApp (deco "Genarray.create" (EPath [ "Genarray"; "create" ])) (
            deco "kind" (EPath [ "kind" ])
          )
        ) (deco "layout" (EPath [ "layout" ]))
      ) (
        deco "[|dim1; dim2|]" (
          EArrayLit [
            deco "dim1" (EPath [ "dim1" ]);
            deco "dim2" (EPath [ "dim2" ])
          ]
        )
      )
    )
  ).

Definition __fun81 := AnonFun "dim1" (EAnonFun __fun80).

Definition __fun82 := AnonFun "layout" (EAnonFun __fun81).

Definition __fun83 := AnonFun "kind" (EAnonFun __fun82).

Definition __fun84 :=
  AnonFun "arr" (
    deco "(kind_size_in_b...r) * (dim2 arr)" (
      EIntMul (
        deco "(kind_size_in_b...)) * (dim1 arr)" (
          EIntMul (
            deco "(kind_size_in_bytes (kind arr))" (
              EApp (deco "kind_size_in_bytes" (EPath [ "kind_size_in_bytes" ])) (
                deco "(kind arr)" (
                  EApp (deco "kind" (EPath [ "kind" ])) (
                    deco "arr" (EPath [ "arr" ])
                  )
                )
              )
            )
          ) (
            deco "(dim1 arr)" (
              EApp (deco "dim1" (EPath [ "dim1" ])) (
                deco "arr" (EPath [ "arr" ])
              )
            )
          )
        )
      ) (
        deco "(dim2 arr)" (
          EApp (deco "dim2" (EPath [ "dim2" ])) (deco "arr" (EPath [ "arr" ]))
        )
      )
    )
  ).

Definition __fun85 :=
  AnonFun "n" (
    deco "Genarray.slice_left a [|n|]" (
      EApp (
        EApp (deco "Genarray.slice_left" (EPath [ "Genarray"; "slice_left" ])) (
          deco "a" (EPath [ "a" ])
        )
      ) (deco "[|n|]" (EArrayLit [ deco "n" (EPath [ "n" ]) ]))
    )
  ).

Definition __fun86 := AnonFun "a" (EAnonFun __fun85).

Definition __fun87 :=
  AnonFun "n" (
    deco "Genarray.slice_right a [|n|]" (
      EApp (
        EApp (deco "Genarray.slice_right" (EPath [ "Genarray"; "slice_right" ])) (
          deco "a" (EPath [ "a" ])
        )
      ) (deco "[|n|]" (EArrayLit [ deco "n" (EPath [ "n" ]) ]))
    )
  ).

Definition __fun88 := AnonFun "a" (EAnonFun __fun87).

Definition __exp89 :=
  EApp (
    EApp (
      EApp (
        EApp (deco "unsafe_set" (EPath [ "unsafe_set" ])) (
          deco "arr" (EPath [ "arr" ])
        )
      ) (deco "i" (EPath [ "i" ]))
    ) (deco "j" (EPath [ "j" ]))
  ) (
    deco "(f i j)" (
      EApp (EApp (deco "f" (EPath [ "f" ])) (deco "i" (EPath [ "i" ]))) (
        deco "j" (EPath [ "j" ])
      )
    )
  ).

Definition __exp90 :=
  EFor "j" (deco "0" (EInt 0)) (
    deco "pred dim2" (EIntSub (deco "dim2" (EPath [ "dim2" ])) (EInt 1))
  ) (deco "unsafe_set arr i j (f i j)" __exp89).

Definition __fun91 :=
  AnonFun "f" (
    deco "for i = 0 to pr... i j) done done" (
      EFor "i" (deco "0" (EInt 0)) (
        deco "pred dim1" (EIntSub (deco "dim1" (EPath [ "dim1" ])) (EInt 1))
      ) (deco "for j = 0 to pr... j (f i j) done" __exp90)
    )
  ).

Definition __fun92 := AnonFun "dim2" (EAnonFun __fun91).

Definition __fun93 := AnonFun "dim1" (EAnonFun __fun92).

Definition __fun94 := AnonFun "arr" (EAnonFun __fun93).

Definition __exp95 :=
  EApp (
    EApp (
      EApp (
        EApp (deco "unsafe_set" (EPath [ "unsafe_set" ])) (
          deco "arr" (EPath [ "arr" ])
        )
      ) (deco "i" (EPath [ "i" ]))
    ) (deco "j" (EPath [ "j" ]))
  ) (
    deco "(f i j)" (
      EApp (EApp (deco "f" (EPath [ "f" ])) (deco "i" (EPath [ "i" ]))) (
        deco "j" (EPath [ "j" ])
      )
    )
  ).

Definition __exp96 :=
  EFor "i" (deco "1" (EInt 1)) (deco "dim1" (EPath [ "dim1" ])) (
    deco "unsafe_set arr i j (f i j)" __exp95
  ).

Definition __fun97 :=
  AnonFun "f" (
    deco "for j = 1 to di... i j) done done" (
      EFor "j" (deco "1" (EInt 1)) (deco "dim2" (EPath [ "dim2" ])) (
        deco "for i = 1 to di... j (f i j) done" __exp96
      )
    )
  ).

Definition __fun98 := AnonFun "dim2" (EAnonFun __fun97).

Definition __fun99 := AnonFun "dim1" (EAnonFun __fun98).

Definition __fun100 := AnonFun "arr" (EAnonFun __fun99).

Definition __exp101 := EPath [ "arr" ].

Definition __exp102 := EPath [ "arr" ].

Definition __branches103 :=
  [
    Branch (CVal (PData "C_layout" [])) (
      deco "c_init arr dim1 dim2 f; arr" (
        ESeq (
          deco "c_init arr dim1 dim2 f" (
            EApp (
              EApp (
                EApp (
                  EApp (deco "c_init" (EPath [ "c_init" ])) (
                    deco "arr" (EPath [ "arr" ])
                  )
                ) (deco "dim1" (EPath [ "dim1" ]))
              ) (deco "dim2" (EPath [ "dim2" ]))
            ) (deco "f" (EPath [ "f" ]))
          )
        ) (deco "arr" __exp101)
      )
    );
    Branch (CVal (PData "Fortran_layout" [])) (
      deco "fortran_init arr dim1 dim2 f; arr" (
        ESeq (
          deco "fortran_init arr dim1 dim2 f" (
            EApp (
              EApp (
                EApp (
                  EApp (deco "fortran_init" (EPath [ "fortran_init" ])) (
                    deco "arr" (EPath [ "arr" ])
                  )
                ) (deco "dim1" (EPath [ "dim1" ]))
              ) (deco "dim2" (EPath [ "dim2" ]))
            ) (deco "f" (EPath [ "f" ]))
          )
        ) (deco "arr" __exp102)
      )
    )
  ].

Definition __exp104 :=
  EMatch (deco "layout" (EPath [ "layout" ])) __branches103.

Definition __fun105 :=
  AnonFun "f" (
    deco "let arr = creat...im1 dim2 f; arr" (
      ELet [
        Binding (PVar "arr") (
          deco "create kind layout dim1 dim2" (
            EApp (
              EApp (
                EApp (
                  EApp (deco "create" (EPath [ "create" ])) (
                    deco "kind" (EPath [ "kind" ])
                  )
                ) (deco "layout" (EPath [ "layout" ]))
              ) (deco "dim1" (EPath [ "dim1" ]))
            ) (deco "dim2" (EPath [ "dim2" ]))
          )
        )
      ] (deco "match layout wi...im1 dim2 f; arr" __exp104)
    )
  ).

Definition __fun106 := AnonFun "dim2" (EAnonFun __fun105).

Definition __fun107 := AnonFun "dim1" (EAnonFun __fun106).

Definition __branches108 :=
  [
    Branch (CVal (PAlias PAny "layout")) (EAnonFun __fun107)
  ].

Definition __fun109 := AnonFunction __branches108.

Definition __fun110 := AnonFun "kind" (EAnonFun __fun109).

Definition __exp111 := EInt 0.

Definition __exp112 :=
  EApp (deco "Array.length" (EPath [ "Array"; "length" ])) (
    deco "data.(0)" (
      EApp (
        EApp (deco "data.(0)" (EPath [ "Array"; "get" ])) (
          deco "data" (EPath [ "data" ])
        )
      ) (deco "0" (EInt 0))
    )
  ).

Definition __branches113 :=
  [
    Branch (CVal (PData "C_layout" [])) (deco "0" (EInt 0));
    Branch (CVal (PData "Fortran_layout" [])) (deco "1" (EInt 1))
  ].

Definition __exp114 :=
  EApp (deco "invalid_arg" (EPath [ "invalid_arg" ])) (
    deco "(""Bigarray.Arra...tangular data"")" (
      EString "Bigarray.Array2.of_array: non-rectangular data"
    )
  ).

Definition __exp115 :=
  EApp (
    EApp (
      EApp (
        EApp (deco "unsafe_set" (EPath [ "unsafe_set" ])) (
          deco "ba" (EPath [ "ba" ])
        )
      ) (
        deco "(i + ofs)" (
          EIntAdd (deco "i" (EPath [ "i" ])) (deco "ofs" (EPath [ "ofs" ]))
        )
      )
    ) (
      deco "(j + ofs)" (
        EIntAdd (deco "j" (EPath [ "j" ])) (deco "ofs" (EPath [ "ofs" ]))
      )
    )
  ) (
    deco "row.(j)" (
      EApp (
        EApp (deco "row.(j)" (EPath [ "Array"; "get" ])) (
          deco "row" (EPath [ "row" ])
        )
      ) (deco "j" (EPath [ "j" ]))
    )
  ).

Definition __exp116 :=
  EFor "j" (deco "0" (EInt 0)) (
    deco "dim2 - 1" (
      EIntSub (deco "dim2" (EPath [ "dim2" ])) (deco "1" (EInt 1))
    )
  ) (deco "unsafe_set ba (... + ofs) row.(j)" __exp115).

Definition __exp117 :=
  ESeq (
    deco "if Array.length...tangular data"")" (
      EIfThen (
        deco "Array.length row <> dim2" (
          EOpNe (
            deco "Array.length row" (
              EApp (deco "Array.length" (EPath [ "Array"; "length" ])) (
                deco "row" (EPath [ "row" ])
              )
            )
          ) (deco "dim2" (EPath [ "dim2" ]))
        )
      ) (deco "invalid_arg(""Bi...tangular data"")" __exp114)
    )
  ) (deco "for j = 0 to di...s) row.(j) done" __exp116).

Definition __exp118 :=
  ELet [
    Binding (PVar "row") (
      deco "data.(i)" (
        EApp (
          EApp (deco "data.(i)" (EPath [ "Array"; "get" ])) (
            deco "data" (EPath [ "data" ])
          )
        ) (deco "i" (EPath [ "i" ]))
      )
    )
  ] (deco "if Array.length...s) row.(j) done" __exp117).

Definition __exp119 := EPath [ "ba" ].

Definition __exp120 :=
  ESeq (
    deco "for i = 0 to di...w.(j) done done" (
      EFor "i" (deco "0" (EInt 0)) (
        deco "dim1 - 1" (
          EIntSub (deco "dim1" (EPath [ "dim1" ])) (deco "1" (EInt 1))
        )
      ) (deco "let row = data....s) row.(j) done" __exp118)
    )
  ) (deco "ba" __exp119).

Definition __exp121 :=
  ELet [
    Binding (PVar "ofs") (
      deco "match layout wi...ran_layout -> 1" (
        EMatch (deco "layout" (EPath [ "layout" ])) __branches113
      )
    )
  ] (deco "for i = 0 to di...) done done; ba" __exp120).

Definition __exp122 :=
  ELet [
    Binding (PVar "ba") (
      deco "create kind layout dim1 dim2" (
        EApp (
          EApp (
            EApp (
              EApp (deco "create" (EPath [ "create" ])) (
                deco "kind" (EPath [ "kind" ])
              )
            ) (deco "layout" (EPath [ "layout" ]))
          ) (deco "dim1" (EPath [ "dim1" ]))
        ) (deco "dim2" (EPath [ "dim2" ]))
      )
    )
  ] (deco "let ofs = match...) done done; ba" __exp121).

Definition __exp123 :=
  ELet [
    Binding (PVar "dim2") (
      deco "if dim1 = 0 the...length data.(0)" (
        EIfThenElse (
          deco "dim1 = 0" (
            EOpEq (deco "dim1" (EPath [ "dim1" ])) (deco "0" (EInt 0))
          )
        ) (deco "0" __exp111) (deco "Array.length data.(0)" __exp112)
      )
    )
  ] (deco "let ba = create...) done done; ba" __exp122).

Definition __fun124 :=
  AnonFun "data" (
    deco "let dim1 = Arra...) done done; ba" (
      ELet [
        Binding (PVar "dim1") (
          deco "Array.length data" (
            EApp (deco "Array.length" (EPath [ "Array"; "length" ])) (
              deco "data" (EPath [ "data" ])
            )
          )
        )
      ] (deco "let dim2 = if d...) done done; ba" __exp123)
    )
  ).

Definition __branches125 :=
  [
    Branch (CVal (PAlias PAny "layout")) (EAnonFun __fun124)
  ].

Definition __fun126 := AnonFunction __branches125.

Definition __fun127 := AnonFun "kind" (EAnonFun __fun126).

Definition __fun128 :=
  AnonFun "dim3" (
    deco "Genarray.create...1; dim2; dim3|]" (
      EApp (
        EApp (
          EApp (deco "Genarray.create" (EPath [ "Genarray"; "create" ])) (
            deco "kind" (EPath [ "kind" ])
          )
        ) (deco "layout" (EPath [ "layout" ]))
      ) (
        deco "[|dim1; dim2; dim3|]" (
          EArrayLit [
            deco "dim1" (EPath [ "dim1" ]);
            deco "dim2" (EPath [ "dim2" ]);
            deco "dim3" (EPath [ "dim3" ])
          ]
        )
      )
    )
  ).

Definition __fun129 := AnonFun "dim2" (EAnonFun __fun128).

Definition __fun130 := AnonFun "dim1" (EAnonFun __fun129).

Definition __fun131 := AnonFun "layout" (EAnonFun __fun130).

Definition __fun132 := AnonFun "kind" (EAnonFun __fun131).

Definition __fun133 :=
  AnonFun "arr" (
    deco "(kind_size_in_b...r) * (dim3 arr)" (
      EIntMul (
        deco "(kind_size_in_b...r) * (dim2 arr)" (
          EIntMul (
            deco "(kind_size_in_b...)) * (dim1 arr)" (
              EIntMul (
                deco "(kind_size_in_bytes (kind arr))" (
                  EApp (
                    deco "kind_size_in_bytes" (EPath [ "kind_size_in_bytes" ])
                  ) (
                    deco "(kind arr)" (
                      EApp (deco "kind" (EPath [ "kind" ])) (
                        deco "arr" (EPath [ "arr" ])
                      )
                    )
                  )
                )
              ) (
                deco "(dim1 arr)" (
                  EApp (deco "dim1" (EPath [ "dim1" ])) (
                    deco "arr" (EPath [ "arr" ])
                  )
                )
              )
            )
          ) (
            deco "(dim2 arr)" (
              EApp (deco "dim2" (EPath [ "dim2" ])) (
                deco "arr" (EPath [ "arr" ])
              )
            )
          )
        )
      ) (
        deco "(dim3 arr)" (
          EApp (deco "dim3" (EPath [ "dim3" ])) (deco "arr" (EPath [ "arr" ]))
        )
      )
    )
  ).

Definition __fun134 :=
  AnonFun "m" (
    deco "Genarray.slice_left a [|n; m|]" (
      EApp (
        EApp (deco "Genarray.slice_left" (EPath [ "Genarray"; "slice_left" ])) (
          deco "a" (EPath [ "a" ])
        )
      ) (
        deco "[|n; m|]" (
          EArrayLit [
            deco "n" (EPath [ "n" ]);
            deco "m" (EPath [ "m" ])
          ]
        )
      )
    )
  ).

Definition __fun135 := AnonFun "n" (EAnonFun __fun134).

Definition __fun136 := AnonFun "a" (EAnonFun __fun135).

Definition __fun137 :=
  AnonFun "m" (
    deco "Genarray.slice_right a [|n; m|]" (
      EApp (
        EApp (deco "Genarray.slice_right" (EPath [ "Genarray"; "slice_right" ])) (
          deco "a" (EPath [ "a" ])
        )
      ) (
        deco "[|n; m|]" (
          EArrayLit [
            deco "n" (EPath [ "n" ]);
            deco "m" (EPath [ "m" ])
          ]
        )
      )
    )
  ).

Definition __fun138 := AnonFun "n" (EAnonFun __fun137).

Definition __fun139 := AnonFun "a" (EAnonFun __fun138).

Definition __fun140 :=
  AnonFun "n" (
    deco "Genarray.slice_left a [|n|]" (
      EApp (
        EApp (deco "Genarray.slice_left" (EPath [ "Genarray"; "slice_left" ])) (
          deco "a" (EPath [ "a" ])
        )
      ) (deco "[|n|]" (EArrayLit [ deco "n" (EPath [ "n" ]) ]))
    )
  ).

Definition __fun141 := AnonFun "a" (EAnonFun __fun140).

Definition __fun142 :=
  AnonFun "n" (
    deco "Genarray.slice_right a [|n|]" (
      EApp (
        EApp (deco "Genarray.slice_right" (EPath [ "Genarray"; "slice_right" ])) (
          deco "a" (EPath [ "a" ])
        )
      ) (deco "[|n|]" (EArrayLit [ deco "n" (EPath [ "n" ]) ]))
    )
  ).

Definition __fun143 := AnonFun "a" (EAnonFun __fun142).

Definition __exp144 :=
  EApp (
    EApp (
      EApp (
        EApp (
          EApp (deco "unsafe_set" (EPath [ "unsafe_set" ])) (
            deco "arr" (EPath [ "arr" ])
          )
        ) (deco "i" (EPath [ "i" ]))
      ) (deco "j" (EPath [ "j" ]))
    ) (deco "k" (EPath [ "k" ]))
  ) (
    deco "(f i j k)" (
      EApp (
        EApp (EApp (deco "f" (EPath [ "f" ])) (deco "i" (EPath [ "i" ]))) (
          deco "j" (EPath [ "j" ])
        )
      ) (deco "k" (EPath [ "k" ]))
    )
  ).

Definition __exp145 :=
  EFor "k" (deco "0" (EInt 0)) (
    deco "pred dim3" (EIntSub (deco "dim3" (EPath [ "dim3" ])) (EInt 1))
  ) (deco "unsafe_set arr i j k (f i j k)" __exp144).

Definition __exp146 :=
  EFor "j" (deco "0" (EInt 0)) (
    deco "pred dim2" (EIntSub (deco "dim2" (EPath [ "dim2" ])) (EInt 1))
  ) (deco "for k = 0 to pr... (f i j k) done" __exp145).

Definition __fun147 :=
  AnonFun "f" (
    deco "for i = 0 to pr... done done done" (
      EFor "i" (deco "0" (EInt 0)) (
        deco "pred dim1" (EIntSub (deco "dim1" (EPath [ "dim1" ])) (EInt 1))
      ) (deco "for j = 0 to pr... j k) done done" __exp146)
    )
  ).

Definition __fun148 := AnonFun "dim3" (EAnonFun __fun147).

Definition __fun149 := AnonFun "dim2" (EAnonFun __fun148).

Definition __fun150 := AnonFun "dim1" (EAnonFun __fun149).

Definition __fun151 := AnonFun "arr" (EAnonFun __fun150).

Definition __exp152 :=
  EApp (
    EApp (
      EApp (
        EApp (
          EApp (deco "unsafe_set" (EPath [ "unsafe_set" ])) (
            deco "arr" (EPath [ "arr" ])
          )
        ) (deco "i" (EPath [ "i" ]))
      ) (deco "j" (EPath [ "j" ]))
    ) (deco "k" (EPath [ "k" ]))
  ) (
    deco "(f i j k)" (
      EApp (
        EApp (EApp (deco "f" (EPath [ "f" ])) (deco "i" (EPath [ "i" ]))) (
          deco "j" (EPath [ "j" ])
        )
      ) (deco "k" (EPath [ "k" ]))
    )
  ).

Definition __exp153 :=
  EFor "i" (deco "1" (EInt 1)) (deco "dim1" (EPath [ "dim1" ])) (
    deco "unsafe_set arr i j k (f i j k)" __exp152
  ).

Definition __exp154 :=
  EFor "j" (deco "1" (EInt 1)) (deco "dim2" (EPath [ "dim2" ])) (
    deco "for i = 1 to di... (f i j k) done" __exp153
  ).

Definition __fun155 :=
  AnonFun "f" (
    deco "for k = 1 to di... done done done" (
      EFor "k" (deco "1" (EInt 1)) (deco "dim3" (EPath [ "dim3" ])) (
        deco "for j = 1 to di... j k) done done" __exp154
      )
    )
  ).

Definition __fun156 := AnonFun "dim3" (EAnonFun __fun155).

Definition __fun157 := AnonFun "dim2" (EAnonFun __fun156).

Definition __fun158 := AnonFun "dim1" (EAnonFun __fun157).

Definition __fun159 := AnonFun "arr" (EAnonFun __fun158).

Definition __exp160 := EPath [ "arr" ].

Definition __exp161 := EPath [ "arr" ].

Definition __branches162 :=
  [
    Branch (CVal (PData "C_layout" [])) (
      deco "c_init arr dim1 dim2 dim3 f; arr" (
        ESeq (
          deco "c_init arr dim1 dim2 dim3 f" (
            EApp (
              EApp (
                EApp (
                  EApp (
                    EApp (deco "c_init" (EPath [ "c_init" ])) (
                      deco "arr" (EPath [ "arr" ])
                    )
                  ) (deco "dim1" (EPath [ "dim1" ]))
                ) (deco "dim2" (EPath [ "dim2" ]))
              ) (deco "dim3" (EPath [ "dim3" ]))
            ) (deco "f" (EPath [ "f" ]))
          )
        ) (deco "arr" __exp160)
      )
    );
    Branch (CVal (PData "Fortran_layout" [])) (
      deco "fortran_init ar...im2 dim3 f; arr" (
        ESeq (
          deco "fortran_init arr dim1 dim2 dim3 f" (
            EApp (
              EApp (
                EApp (
                  EApp (
                    EApp (deco "fortran_init" (EPath [ "fortran_init" ])) (
                      deco "arr" (EPath [ "arr" ])
                    )
                  ) (deco "dim1" (EPath [ "dim1" ]))
                ) (deco "dim2" (EPath [ "dim2" ]))
              ) (deco "dim3" (EPath [ "dim3" ]))
            ) (deco "f" (EPath [ "f" ]))
          )
        ) (deco "arr" __exp161)
      )
    )
  ].

Definition __exp163 :=
  EMatch (deco "layout" (EPath [ "layout" ])) __branches162.

Definition __fun164 :=
  AnonFun "f" (
    deco "let arr = creat...im2 dim3 f; arr" (
      ELet [
        Binding (PVar "arr") (
          deco "create kind layout dim1 dim2 dim3" (
            EApp (
              EApp (
                EApp (
                  EApp (
                    EApp (deco "create" (EPath [ "create" ])) (
                      deco "kind" (EPath [ "kind" ])
                    )
                  ) (deco "layout" (EPath [ "layout" ]))
                ) (deco "dim1" (EPath [ "dim1" ]))
              ) (deco "dim2" (EPath [ "dim2" ]))
            ) (deco "dim3" (EPath [ "dim3" ]))
          )
        )
      ] (deco "match layout wi...im2 dim3 f; arr" __exp163)
    )
  ).

Definition __fun165 := AnonFun "dim3" (EAnonFun __fun164).

Definition __fun166 := AnonFun "dim2" (EAnonFun __fun165).

Definition __fun167 := AnonFun "dim1" (EAnonFun __fun166).

Definition __branches168 :=
  [
    Branch (CVal (PAlias PAny "layout")) (EAnonFun __fun167)
  ].

Definition __fun169 := AnonFunction __branches168.

Definition __fun170 := AnonFun "kind" (EAnonFun __fun169).

Definition __exp171 := EInt 0.

Definition __exp172 :=
  EApp (deco "Array.length" (EPath [ "Array"; "length" ])) (
    deco "data.(0)" (
      EApp (
        EApp (deco "data.(0)" (EPath [ "Array"; "get" ])) (
          deco "data" (EPath [ "data" ])
        )
      ) (deco "0" (EInt 0))
    )
  ).

Definition __exp173 := EInt 0.

Definition __exp174 :=
  EApp (deco "Array.length" (EPath [ "Array"; "length" ])) (
    deco "data.(0).(0)" (
      EApp (
        EApp (deco "data.(0).(0)" (EPath [ "Array"; "get" ])) (
          deco "data.(0)" (
            EApp (
              EApp (deco "data.(0)" (EPath [ "Array"; "get" ])) (
                deco "data" (EPath [ "data" ])
              )
            ) (deco "0" (EInt 0))
          )
        )
      ) (deco "0" (EInt 0))
    )
  ).

Definition __branches175 :=
  [
    Branch (CVal (PData "C_layout" [])) (deco "0" (EInt 0));
    Branch (CVal (PData "Fortran_layout" [])) (deco "1" (EInt 1))
  ].

Definition __exp176 :=
  EApp (deco "invalid_arg" (EPath [ "invalid_arg" ])) (
    deco "(""Bigarray.Arra...on-cubic data"")" (
      EString "Bigarray.Array3.of_array: non-cubic data"
    )
  ).

Definition __exp177 :=
  EApp (deco "invalid_arg" (EPath [ "invalid_arg" ])) (
    deco "(""Bigarray.Arra...on-cubic data"")" (
      EString "Bigarray.Array3.of_array: non-cubic data"
    )
  ).

Definition __exp178 :=
  EApp (
    EApp (
      EApp (
        EApp (
          EApp (deco "unsafe_set" (EPath [ "unsafe_set" ])) (
            deco "ba" (EPath [ "ba" ])
          )
        ) (
          deco "(i + ofs)" (
            EIntAdd (deco "i" (EPath [ "i" ])) (deco "ofs" (EPath [ "ofs" ]))
          )
        )
      ) (
        deco "(j + ofs)" (
          EIntAdd (deco "j" (EPath [ "j" ])) (deco "ofs" (EPath [ "ofs" ]))
        )
      )
    ) (
      deco "(k + ofs)" (
        EIntAdd (deco "k" (EPath [ "k" ])) (deco "ofs" (EPath [ "ofs" ]))
      )
    )
  ) (
    deco "col.(k)" (
      EApp (
        EApp (deco "col.(k)" (EPath [ "Array"; "get" ])) (
          deco "col" (EPath [ "col" ])
        )
      ) (deco "k" (EPath [ "k" ]))
    )
  ).

Definition __exp179 :=
  EFor "k" (deco "0" (EInt 0)) (
    deco "dim3 - 1" (
      EIntSub (deco "dim3" (EPath [ "dim3" ])) (deco "1" (EInt 1))
    )
  ) (deco "unsafe_set ba (... + ofs) col.(k)" __exp178).

Definition __exp180 :=
  ESeq (
    deco "if Array.length...on-cubic data"")" (
      EIfThen (
        deco "Array.length col <> dim3" (
          EOpNe (
            deco "Array.length col" (
              EApp (deco "Array.length" (EPath [ "Array"; "length" ])) (
                deco "col" (EPath [ "col" ])
              )
            )
          ) (deco "dim3" (EPath [ "dim3" ]))
        )
      ) (deco "invalid_arg(""Bi...on-cubic data"")" __exp177)
    )
  ) (deco "for k = 0 to di...s) col.(k) done" __exp179).

Definition __exp181 :=
  ELet [
    Binding (PVar "col") (
      deco "row.(j)" (
        EApp (
          EApp (deco "row.(j)" (EPath [ "Array"; "get" ])) (
            deco "row" (EPath [ "row" ])
          )
        ) (deco "j" (EPath [ "j" ]))
      )
    )
  ] (deco "if Array.length...s) col.(k) done" __exp180).

Definition __exp182 :=
  EFor "j" (deco "0" (EInt 0)) (
    deco "dim2 - 1" (
      EIntSub (deco "dim2" (EPath [ "dim2" ])) (deco "1" (EInt 1))
    )
  ) (deco "let col = row.(...s) col.(k) done" __exp181).

Definition __exp183 :=
  ESeq (
    deco "if Array.length...on-cubic data"")" (
      EIfThen (
        deco "Array.length row <> dim2" (
          EOpNe (
            deco "Array.length row" (
              EApp (deco "Array.length" (EPath [ "Array"; "length" ])) (
                deco "row" (EPath [ "row" ])
              )
            )
          ) (deco "dim2" (EPath [ "dim2" ]))
        )
      ) (deco "invalid_arg(""Bi...on-cubic data"")" __exp176)
    )
  ) (deco "for j = 0 to di...l.(k) done done" __exp182).

Definition __exp184 :=
  ELet [
    Binding (PVar "row") (
      deco "data.(i)" (
        EApp (
          EApp (deco "data.(i)" (EPath [ "Array"; "get" ])) (
            deco "data" (EPath [ "data" ])
          )
        ) (deco "i" (EPath [ "i" ]))
      )
    )
  ] (deco "if Array.length...l.(k) done done" __exp183).

Definition __exp185 := EPath [ "ba" ].

Definition __exp186 :=
  ESeq (
    deco "for i = 0 to di... done done done" (
      EFor "i" (deco "0" (EInt 0)) (
        deco "dim1 - 1" (
          EIntSub (deco "dim1" (EPath [ "dim1" ])) (deco "1" (EInt 1))
        )
      ) (deco "let row = data....l.(k) done done" __exp184)
    )
  ) (deco "ba" __exp185).

Definition __exp187 :=
  ELet [
    Binding (PVar "ofs") (
      deco "match layout wi...ran_layout -> 1" (
        EMatch (deco "layout" (EPath [ "layout" ])) __branches175
      )
    )
  ] (deco "for i = 0 to di...e done done; ba" __exp186).

Definition __exp188 :=
  ELet [
    Binding (PVar "ba") (
      deco "create kind layout dim1 dim2 dim3" (
        EApp (
          EApp (
            EApp (
              EApp (
                EApp (deco "create" (EPath [ "create" ])) (
                  deco "kind" (EPath [ "kind" ])
                )
              ) (deco "layout" (EPath [ "layout" ]))
            ) (deco "dim1" (EPath [ "dim1" ]))
          ) (deco "dim2" (EPath [ "dim2" ]))
        ) (deco "dim3" (EPath [ "dim3" ]))
      )
    )
  ] (deco "let ofs = match...e done done; ba" __exp187).

Definition __exp189 :=
  ELet [
    Binding (PVar "dim3") (
      deco "if dim2 = 0 the...th data.(0).(0)" (
        EIfThenElse (
          deco "dim2 = 0" (
            EOpEq (deco "dim2" (EPath [ "dim2" ])) (deco "0" (EInt 0))
          )
        ) (deco "0" __exp173) (deco "Array.length data.(0).(0)" __exp174)
      )
    )
  ] (deco "let ba = create...e done done; ba" __exp188).

Definition __exp190 :=
  ELet [
    Binding (PVar "dim2") (
      deco "if dim1 = 0 the...length data.(0)" (
        EIfThenElse (
          deco "dim1 = 0" (
            EOpEq (deco "dim1" (EPath [ "dim1" ])) (deco "0" (EInt 0))
          )
        ) (deco "0" __exp171) (deco "Array.length data.(0)" __exp172)
      )
    )
  ] (deco "let dim3 = if d...e done done; ba" __exp189).

Definition __fun191 :=
  AnonFun "data" (
    deco "let dim1 = Arra...e done done; ba" (
      ELet [
        Binding (PVar "dim1") (
          deco "Array.length data" (
            EApp (deco "Array.length" (EPath [ "Array"; "length" ])) (
              deco "data" (EPath [ "data" ])
            )
          )
        )
      ] (deco "let dim2 = if d...e done done; ba" __exp190)
    )
  ).

Definition __branches192 :=
  [
    Branch (CVal (PAlias PAny "layout")) (EAnonFun __fun191)
  ].

Definition __fun193 := AnonFunction __branches192.

Definition __fun194 := AnonFun "kind" (EAnonFun __fun193).

Definition __exp195 := EPath [ "a" ].

Definition __exp196 :=
  EApp (deco "invalid_arg" (EPath [ "invalid_arg" ])) (
    deco """Bigarray.array0_of_genarray""" (
      EString "Bigarray.array0_of_genarray"
    )
  ).

Definition __fun197 :=
  AnonFun "a" (
    deco "if Genarray.num...y0_of_genarray""" (
      EIfThenElse (
        deco "Genarray.num_dims a = 0" (
          EOpEq (
            deco "Genarray.num_dims a" (
              EApp (deco "Genarray.num_dims" (EPath [ "Genarray"; "num_dims" ])) (
                deco "a" (EPath [ "a" ])
              )
            )
          ) (deco "0" (EInt 0))
        )
      ) (deco "a" __exp195) (
        deco "invalid_arg ""Bi...y0_of_genarray""" __exp196
      )
    )
  ).

Definition __exp198 := EPath [ "a" ].

Definition __exp199 :=
  EApp (deco "invalid_arg" (EPath [ "invalid_arg" ])) (
    deco """Bigarray.array1_of_genarray""" (
      EString "Bigarray.array1_of_genarray"
    )
  ).

Definition __fun200 :=
  AnonFun "a" (
    deco "if Genarray.num...y1_of_genarray""" (
      EIfThenElse (
        deco "Genarray.num_dims a = 1" (
          EOpEq (
            deco "Genarray.num_dims a" (
              EApp (deco "Genarray.num_dims" (EPath [ "Genarray"; "num_dims" ])) (
                deco "a" (EPath [ "a" ])
              )
            )
          ) (deco "1" (EInt 1))
        )
      ) (deco "a" __exp198) (
        deco "invalid_arg ""Bi...y1_of_genarray""" __exp199
      )
    )
  ).

Definition __exp201 := EPath [ "a" ].

Definition __exp202 :=
  EApp (deco "invalid_arg" (EPath [ "invalid_arg" ])) (
    deco """Bigarray.array2_of_genarray""" (
      EString "Bigarray.array2_of_genarray"
    )
  ).

Definition __fun203 :=
  AnonFun "a" (
    deco "if Genarray.num...y2_of_genarray""" (
      EIfThenElse (
        deco "Genarray.num_dims a = 2" (
          EOpEq (
            deco "Genarray.num_dims a" (
              EApp (deco "Genarray.num_dims" (EPath [ "Genarray"; "num_dims" ])) (
                deco "a" (EPath [ "a" ])
              )
            )
          ) (deco "2" (EInt 2))
        )
      ) (deco "a" __exp201) (
        deco "invalid_arg ""Bi...y2_of_genarray""" __exp202
      )
    )
  ).

Definition __exp204 := EPath [ "a" ].

Definition __exp205 :=
  EApp (deco "invalid_arg" (EPath [ "invalid_arg" ])) (
    deco """Bigarray.array3_of_genarray""" (
      EString "Bigarray.array3_of_genarray"
    )
  ).

Definition __fun206 :=
  AnonFun "a" (
    deco "if Genarray.num...y3_of_genarray""" (
      EIfThenElse (
        deco "Genarray.num_dims a = 3" (
          EOpEq (
            deco "Genarray.num_dims a" (
              EApp (deco "Genarray.num_dims" (EPath [ "Genarray"; "num_dims" ])) (
                deco "a" (EPath [ "a" ])
              )
            )
          ) (deco "3" (EInt 3))
        )
      ) (deco "a" __exp204) (
        deco "invalid_arg ""Bi...y3_of_genarray""" __exp205
      )
    )
  ).

Definition __fun207 :=
  AnonFun "a" (
    deco "reshape a [||]" (
      EApp (
        EApp (deco "reshape" (EPath [ "reshape" ])) (deco "a" (EPath [ "a" ]))
      ) (deco "[||]" (EArrayLit []))
    )
  ).

Definition __fun208 :=
  AnonFun "dim1" (
    deco "reshape a [|dim1|]" (
      EApp (
        EApp (deco "reshape" (EPath [ "reshape" ])) (deco "a" (EPath [ "a" ]))
      ) (deco "[|dim1|]" (EArrayLit [ deco "dim1" (EPath [ "dim1" ]) ]))
    )
  ).

Definition __fun209 := AnonFun "a" (EAnonFun __fun208).

Definition __fun210 :=
  AnonFun "dim2" (
    deco "reshape a [|dim1;dim2|]" (
      EApp (
        EApp (deco "reshape" (EPath [ "reshape" ])) (deco "a" (EPath [ "a" ]))
      ) (
        deco "[|dim1;dim2|]" (
          EArrayLit [
            deco "dim1" (EPath [ "dim1" ]);
            deco "dim2" (EPath [ "dim2" ])
          ]
        )
      )
    )
  ).

Definition __fun211 := AnonFun "dim1" (EAnonFun __fun210).

Definition __fun212 := AnonFun "a" (EAnonFun __fun211).

Definition __fun213 :=
  AnonFun "dim3" (
    deco "reshape a [|dim1;dim2;dim3|]" (
      EApp (
        EApp (deco "reshape" (EPath [ "reshape" ])) (deco "a" (EPath [ "a" ]))
      ) (
        deco "[|dim1;dim2;dim3|]" (
          EArrayLit [
            deco "dim1" (EPath [ "dim1" ]);
            deco "dim2" (EPath [ "dim2" ]);
            deco "dim3" (EPath [ "dim3" ])
          ]
        )
      )
    )
  ).

Definition __fun214 := AnonFun "dim2" (EAnonFun __fun213).

Definition __fun215 := AnonFun "dim1" (EAnonFun __fun214).

Definition __fun216 := AnonFun "a" (EAnonFun __fun215).

Definition __exp217 := EData "()" [].

Definition __exp218 :=
  ELet [
    Binding PAny (deco "Array3.get" (EPath [ "Array3"; "get" ]))
  ] (deco "()" __exp217).

Definition __exp219 :=
  ELet [
    Binding PAny (deco "Array2.get" (EPath [ "Array2"; "get" ]))
  ] (deco "let _ = Array3.get in ()" __exp218).

Definition __exp220 :=
  ELet [
    Binding PAny (deco "Array1.get" (EPath [ "Array1"; "get" ]))
  ] (deco "let _ = Array2....rray3.get in ()" __exp219).

Definition __main :=
  MStruct [
    ILet [
      Binding (PVar "float16") (deco "Float16" (EData "Float16" []))
    ];
    ILet [
      Binding (PVar "float32") (deco "Float32" (EData "Float32" []))
    ];
    ILet [
      Binding (PVar "float64") (deco "Float64" (EData "Float64" []))
    ];
    ILet [
      Binding (PVar "int8_signed") (deco "Int8_signed" (EData "Int8_signed" []))
    ];
    ILet [
      Binding (PVar "int8_unsigned") (
        deco "Int8_unsigned" (EData "Int8_unsigned" [])
      )
    ];
    ILet [
      Binding (PVar "int16_signed") (
        deco "Int16_signed" (EData "Int16_signed" [])
      )
    ];
    ILet [
      Binding (PVar "int16_unsigned") (
        deco "Int16_unsigned" (EData "Int16_unsigned" [])
      )
    ];
    ILet [
      Binding (PVar "int32") (deco "Int32" (EData "Int32" []))
    ];
    ILet [
      Binding (PVar "int64") (deco "Int64" (EData "Int64" []))
    ];
    ILet [
      Binding (PVar "int") (deco "Int" (EData "Int" []))
    ];
    ILet [
      Binding (PVar "nativeint") (deco "Nativeint" (EData "Nativeint" []))
    ];
    ILet [
      Binding (PVar "complex32") (deco "Complex32" (EData "Complex32" []))
    ];
    ILet [
      Binding (PVar "complex64") (deco "Complex64" (EData "Complex64" []))
    ];
    ILet [
      Binding (PVar "char") (deco "Char" (EData "Char" []))
    ];
    ILet [
      Binding (PVar "kind_size_in_bytes") (
        deco "kind_size_in_by... 16 | Char -> 1" (EAnonFun __fun1)
      )
    ];
    ILet [
      Binding (PVar "c_layout") (deco "C_layout" (EData "C_layout" []))
    ];
    ILet [
      Binding (PVar "fortran_layout") (
        deco "Fortran_layout" (EData "Fortran_layout" [])
      )
    ];
    IModule "Genarray" (
      MStruct [
        ILetRec __bindings10;
        ILetRec __bindings19;
        ILet [
          Binding (PVar "init") (
            deco "(type t) kind (...dlen) dims; arr" (EAnonFun __fun29)
          )
        ];
        ILet [
          Binding (PVar "dims") (
            deco "a = let n = num...dim a i done; d" (EAnonFun __fun34)
          )
        ];
        ILet [
          Binding (PVar "size_in_bytes") (
            deco "arr = (kind_siz...) 1 (dims arr))" (EAnonFun __fun35)
          )
        ]
      ]
    );
    IModule "Array0" (
      MStruct [
        ILet [
          Binding (PVar "create") (
            deco "kind layout = G...ind layout [||]" (EAnonFun __fun37)
          )
        ];
        ILet [
          Binding (PVar "get") (
            deco "arr = Genarray.get arr [||]" (EAnonFun __fun38)
          )
        ];
        ILet [
          Binding (PVar "set") (
            deco "arr = Genarray.set arr [||]" (EAnonFun __fun39)
          )
        ];
        ILet [
          Binding (PVar "size_in_bytes") (
            deco "arr = kind_size...ytes (kind arr)" (EAnonFun __fun40)
          )
        ];
        ILet [
          Binding (PVar "of_value") (
            deco "kind layout v =...t in set a v; a" (EAnonFun __fun45)
          )
        ];
        ILet [
          Binding (PVar "init") (deco "of_value" (EPath [ "of_value" ]))
        ]
      ]
    );
    IModule "Array1" (
      MStruct [
        ILet [
          Binding (PVar "create") (
            deco "kind layout dim... layout [|dim|]" (EAnonFun __fun48)
          )
        ];
        ILet [
          Binding (PVar "size_in_bytes") (
            deco "arr = (kind_siz...r)) * (dim arr)" (EAnonFun __fun49)
          )
        ];
        ILet [
          Binding (PVar "slice") (
            deco "(type t) (a : (... t) Genarray.t)" (EAnonFun __fun53)
          )
        ];
        ILet [
          Binding (PVar "c_init") (
            deco "arr dim f = for...rr i (f i) done" (EAnonFun __fun57)
          )
        ];
        ILet [
          Binding (PVar "fortran_init") (
            deco "arr dim f = for...rr i (f i) done" (EAnonFun __fun61)
          )
        ];
        ILet [
          Binding (PVar "init") (
            deco "(type t) kind (... arr dim f; arr" (EAnonFun __fun70)
          )
        ];
        ILet [
          Binding (PVar "of_array") (
            deco "(type t) kind (...ta.(i) done; ba" (EAnonFun __fun79)
          )
        ]
      ]
    );
    IModule "Array2" (
      MStruct [
        ILet [
          Binding (PVar "create") (
            deco "kind layout dim... [|dim1; dim2|]" (EAnonFun __fun83)
          )
        ];
        ILet [
          Binding (PVar "size_in_bytes") (
            deco "arr = (kind_siz...r) * (dim2 arr)" (EAnonFun __fun84)
          )
        ];
        ILet [
          Binding (PVar "slice_left") (
            deco "a n = Genarray.slice_left a [|n|]" (EAnonFun __fun86)
          )
        ];
        ILet [
          Binding (PVar "slice_right") (
            deco "a n = Genarray....e_right a [|n|]" (EAnonFun __fun88)
          )
        ];
        ILet [
          Binding (PVar "c_init") (
            deco "arr dim1 dim2 f... i j) done done" (EAnonFun __fun94)
          )
        ];
        ILet [
          Binding (PVar "fortran_init") (
            deco "arr dim1 dim2 f... i j) done done" (EAnonFun __fun100)
          )
        ];
        ILet [
          Binding (PVar "init") (
            deco "(type t) kind (...im1 dim2 f; arr" (EAnonFun __fun110)
          )
        ];
        ILet [
          Binding (PVar "of_array") (
            deco "(type t) kind (...) done done; ba" (EAnonFun __fun127)
          )
        ]
      ]
    );
    IModule "Array3" (
      MStruct [
        ILet [
          Binding (PVar "create") (
            deco "kind layout dim...1; dim2; dim3|]" (EAnonFun __fun132)
          )
        ];
        ILet [
          Binding (PVar "size_in_bytes") (
            deco "arr = (kind_siz...r) * (dim3 arr)" (EAnonFun __fun133)
          )
        ];
        ILet [
          Binding (PVar "slice_left_1") (
            deco "a n m = Genarra...left a [|n; m|]" (EAnonFun __fun136)
          )
        ];
        ILet [
          Binding (PVar "slice_right_1") (
            deco "a n m = Genarra...ight a [|n; m|]" (EAnonFun __fun139)
          )
        ];
        ILet [
          Binding (PVar "slice_left_2") (
            deco "a n = Genarray.slice_left a [|n|]" (EAnonFun __fun141)
          )
        ];
        ILet [
          Binding (PVar "slice_right_2") (
            deco "a n = Genarray....e_right a [|n|]" (EAnonFun __fun143)
          )
        ];
        ILet [
          Binding (PVar "c_init") (
            deco "arr dim1 dim2 d... done done done" (EAnonFun __fun151)
          )
        ];
        ILet [
          Binding (PVar "fortran_init") (
            deco "arr dim1 dim2 d... done done done" (EAnonFun __fun159)
          )
        ];
        ILet [
          Binding (PVar "init") (
            deco "(type t) kind (...im2 dim3 f; arr" (EAnonFun __fun170)
          )
        ];
        ILet [
          Binding (PVar "of_array") (
            deco "(type t) kind (...e done done; ba" (EAnonFun __fun194)
          )
        ]
      ]
    );
    ILet [
      Binding (PVar "array0_of_genarray") (
        deco "a = if Genarray...y0_of_genarray""" (EAnonFun __fun197)
      )
    ];
    ILet [
      Binding (PVar "array1_of_genarray") (
        deco "a = if Genarray...y1_of_genarray""" (EAnonFun __fun200)
      )
    ];
    ILet [
      Binding (PVar "array2_of_genarray") (
        deco "a = if Genarray...y2_of_genarray""" (EAnonFun __fun203)
      )
    ];
    ILet [
      Binding (PVar "array3_of_genarray") (
        deco "a = if Genarray...y3_of_genarray""" (EAnonFun __fun206)
      )
    ];
    ILet [
      Binding (PVar "reshape_0") (deco "a = reshape a [||]" (EAnonFun __fun207))
    ];
    ILet [
      Binding (PVar "reshape_1") (
        deco "a dim1 = reshape a [|dim1|]" (EAnonFun __fun209)
      )
    ];
    ILet [
      Binding (PVar "reshape_2") (
        deco "a dim1 dim2 = r...a [|dim1;dim2|]" (EAnonFun __fun212)
      )
    ];
    ILet [
      Binding (PVar "reshape_3") (
        deco "a dim1 dim2 dim...im1;dim2;dim3|]" (EAnonFun __fun216)
      )
    ];
    ILet [
      Binding PAny (
        deco "let _ = Genarra...rray3.get in ()" (
          ELet [
            Binding PAny (deco "Genarray.get" (EPath [ "Genarray"; "get" ]))
          ] (deco "let _ = Array1....rray3.get in ()" __exp220)
        )
      )
    ]
  ].

