(* This file has been generated by Osiris. Do not edit. *)

From osiris Require Import osiris.

Definition __exp0 :=
  EApp (deco "invalid_arg" (EPath [ "invalid_arg" ])) (
    deco """Char.chr""" (EString "Char.chr")
  ).

Definition __exp1 :=
  EApp (deco "unsafe_chr" (EPath [ "unsafe_chr" ])) (deco "n" (EPath [ "n" ])).

Definition __fun2 :=
  AnonFun "n" (
    deco "if n < 0 || n >...se unsafe_chr n" (
      EIfThenElse (
        deco "n < 0 || n > 255" (
          EBoolDisj (
            deco "n < 0" (EOpLt (deco "n" (EPath [ "n" ])) (deco "0" (EInt 0)))
          ) (
            deco "n > 255" (
              EOpGt (deco "n" (EPath [ "n" ])) (deco "255" (EInt 255))
            )
          )
        )
      ) (deco "invalid_arg ""Char.chr""" __exp0) (deco "unsafe_chr n" __exp1)
    )
  ).

Definition __exp3 :=
  EApp (deco "unsafe_to_string" (EPath [ "unsafe_to_string" ])) (
    deco "s" (EPath [ "s" ])
  ).

Definition __exp4 :=
  ESeq (
    deco "bytes_unsafe_set s 0 c" (
      EApp (
        EApp (
          EApp (deco "bytes_unsafe_set" (EPath [ "bytes_unsafe_set" ])) (
            deco "s" (EPath [ "s" ])
          )
        ) (deco "0" (EInt 0))
      ) (deco "c" (EPath [ "c" ]))
    )
  ) (deco "unsafe_to_string s" __exp3).

Definition __exp5 :=
  EApp (deco "unsafe_to_string" (EPath [ "unsafe_to_string" ])) (
    deco "s" (EPath [ "s" ])
  ).

Definition __exp6 :=
  ESeq (
    deco "bytes_unsafe_se...48 + n mod 10))" (
      EApp (
        EApp (
          EApp (deco "bytes_unsafe_set" (EPath [ "bytes_unsafe_set" ])) (
            deco "s" (EPath [ "s" ])
          )
        ) (deco "3" (EInt 3))
      ) (
        deco "(unsafe_chr (48 + n mod 10))" (
          EApp (deco "unsafe_chr" (EPath [ "unsafe_chr" ])) (
            deco "(48 + n mod 10)" (
              EIntAdd (deco "48" (EInt 48)) (
                deco "n mod 10" (
                  EIntMod (deco "n" (EPath [ "n" ])) (deco "10" (EInt 10))
                )
              )
            )
          )
        )
      )
    )
  ) (deco "unsafe_to_string s" __exp5).

Definition __exp7 :=
  ESeq (
    deco "bytes_unsafe_se... / 10) mod 10))" (
      EApp (
        EApp (
          EApp (deco "bytes_unsafe_set" (EPath [ "bytes_unsafe_set" ])) (
            deco "s" (EPath [ "s" ])
          )
        ) (deco "2" (EInt 2))
      ) (
        deco "(unsafe_chr (48... / 10) mod 10))" (
          EApp (deco "unsafe_chr" (EPath [ "unsafe_chr" ])) (
            deco "(48 + (n / 10) mod 10)" (
              EIntAdd (deco "48" (EInt 48)) (
                deco "(n / 10) mod 10" (
                  EIntMod (
                    deco "(n / 10)" (
                      EIntDiv (deco "n" (EPath [ "n" ])) (deco "10" (EInt 10))
                    )
                  ) (deco "10" (EInt 10))
                )
              )
            )
          )
        )
      )
    )
  ) (deco "bytes_unsafe_se...afe_to_string s" __exp6).

Definition __exp8 :=
  ESeq (
    deco "bytes_unsafe_se...(48 + n / 100))" (
      EApp (
        EApp (
          EApp (deco "bytes_unsafe_set" (EPath [ "bytes_unsafe_set" ])) (
            deco "s" (EPath [ "s" ])
          )
        ) (deco "1" (EInt 1))
      ) (
        deco "(unsafe_chr (48 + n / 100))" (
          EApp (deco "unsafe_chr" (EPath [ "unsafe_chr" ])) (
            deco "(48 + n / 100)" (
              EIntAdd (deco "48" (EInt 48)) (
                deco "n / 100" (
                  EIntDiv (deco "n" (EPath [ "n" ])) (deco "100" (EInt 100))
                )
              )
            )
          )
        )
      )
    )
  ) (deco "bytes_unsafe_se...afe_to_string s" __exp7).

Definition __exp9 :=
  ESeq (
    deco "bytes_unsafe_set s 0 '\\'" (
      EApp (
        EApp (
          EApp (deco "bytes_unsafe_set" (EPath [ "bytes_unsafe_set" ])) (
            deco "s" (EPath [ "s" ])
          )
        ) (deco "0" (EInt 0))
      ) (deco "'\\'" (EChar "\"%char))
    )
  ) (deco "bytes_unsafe_se...afe_to_string s" __exp8).

Definition __exp10 :=
  ELet [
    Binding (PVar "s") (
      deco "bytes_create 4" (
        EApp (deco "bytes_create" (EPath [ "bytes_create" ])) (
          deco "4" (EInt 4)
        )
      )
    )
  ] (deco "bytes_unsafe_se...afe_to_string s" __exp9).

Definition __branches11 :=
  [
    Branch (CVal (PChar "'"%char)) (deco """\\'""" (EString "\'"));
    Branch (CVal (PChar "\"%char)) (deco """\\\\""" (EString "\\"));
    Branch (CVal (PChar "
"%char)) (deco """\\n""" (EString "\n"));
    Branch (CVal (PChar "	"%char)) (deco """\\t""" (EString "\t"));
    Branch (CVal (PChar ""%char)) (deco """\\r""" (EString "\r"));
    Branch (CVal (PChar ""%char)) (deco """\\b""" (EString "\b"));
    Branch (
      CVal (
        PAlias (
          POr (PChar " "%char) (
            POr (PChar "!"%char) (
              POr (PChar """"%char) (
                POr (PChar "#"%char) (
                  POr (PChar "$"%char) (
                    POr (PChar "%"%char) (
                      POr (PChar "&"%char) (
                        POr (PChar "'"%char) (
                          POr (PChar "("%char) (
                            POr (PChar ")"%char) (
                              POr (PChar "*"%char) (
                                POr (PChar "+"%char) (
                                  POr (PChar ","%char) (
                                    POr (PChar "-"%char) (
                                      POr (PChar "."%char) (
                                        POr (PChar "/"%char) (
                                          POr (PChar "0"%char) (
                                            POr (PChar "1"%char) (
                                              POr (PChar "2"%char) (
                                                POr (PChar "3"%char) (
                                                  POr (PChar "4"%char) (
                                                    POr (PChar "5"%char) (
                                                      POr (PChar "6"%char) (
                                                        POr (PChar "7"%char) (
                                                          POr (PChar "8"%char) (
                                                            POr (PChar "9"%char) (
                                                              POr (
                                                                PChar ":"%char
                                                              ) (
                                                                POr (
                                                                  PChar ";"%char
                                                                ) (
                                                                  POr (
                                                                    PChar "<"%char
                                                                  ) (
                                                                    POr (
                                                                      PChar "="%char
                                                                    ) (
                                                                      POr (
                                                                        PChar ">"%char
                                                                      ) (
                                                                        POr (
                                                                          PChar "?"%char
                                                                        ) (
                                                                          POr (
                                                                            PChar "@"%char
                                                                          ) (
                                                                            POr (
                                                                              PChar "A"%char
                                                                            ) (
                                                                              POr (
                                                                                PChar "B"%char
                                                                              ) (
                                                                                POr (
                                                                                  PChar "C"%char
                                                                                ) (
                                                                                  POr (
                                                                                    PChar "D"%char
                                                                                  ) (
                                                                                    POr (
                                                                                      PChar "E"%char
                                                                                    ) (
                                                                                      POr (
                                                                                        PChar "F"%char
                                                                                      ) (
                                                                                        POr (
                                                                                          PChar "G"%char
                                                                                        ) (
                                                                                          POr (
                                                                                            PChar "H"%char
                                                                                          ) (
                                                                                            POr (
                                                                                              PChar "I"%char
                                                                                            ) (
                                                                                              POr (
                                                                                                PChar "J"%char
                                                                                              ) (
                                                                                                POr (
                                                                                                  PChar "K"%char
                                                                                                ) (
                                                                                                  POr (
                                                                                                    PChar "L"%char
                                                                                                  ) (
                                                                                                    POr (
                                                                                                      PChar "M"%char
                                                                                                    ) (
                                                                                                      POr (
                                                                                                        PChar "N"%char
                                                                                                      ) (
                                                                                                        POr (
                                                                                                          PChar "O"%char
                                                                                                        ) (
                                                                                                          POr (
                                                                                                            PChar "P"%char
                                                                                                          ) (
                                                                                                            POr (
                                                                                                              PChar "Q"%char
                                                                                                            ) (
                                                                                                              POr (
                                                                                                                PChar "R"%char
                                                                                                              ) (
                                                                                                                POr (
                                                                                                                  PChar "S"%char
                                                                                                                ) (
                                                                                                                  POr (
                                                                                                                    PChar "T"%char
                                                                                                                  ) (
                                                                                                                    POr (
                                                                                                                      PChar "U"%char
                                                                                                                    ) (
                                                                                                                      POr (
                                                                                                                        PChar "V"%char
                                                                                                                      ) (
                                                                                                                        POr (
                                                                                                                          PChar "W"%char
                                                                                                                        ) (
                                                                                                                          POr (
                                                                                                                            PChar "X"%char
                                                                                                                          ) (
                                                                                                                            POr (
                                                                                                                              PChar "Y"%char
                                                                                                                            ) (
                                                                                                                              POr (
                                                                                                                                PChar "Z"%char
                                                                                                                              ) (
                                                                                                                                POr (
                                                                                                                                  PChar "["%char
                                                                                                                                ) (
                                                                                                                                  POr (
                                                                                                                                    PChar "\"%char
                                                                                                                                  ) (
                                                                                                                                    POr (
                                                                                                                                      PChar "]"%char
                                                                                                                                    ) (
                                                                                                                                      POr (
                                                                                                                                        PChar "^"%char
                                                                                                                                      ) (
                                                                                                                                        POr (
                                                                                                                                          PChar "_"%char
                                                                                                                                        ) (
                                                                                                                                          POr (
                                                                                                                                            PChar "`"%char
                                                                                                                                          ) (
                                                                                                                                            POr (
                                                                                                                                              PChar "a"%char
                                                                                                                                            ) (
                                                                                                                                              POr (
                                                                                                                                                PChar "b"%char
                                                                                                                                              ) (
                                                                                                                                                POr (
                                                                                                                                                  PChar "c"%char
                                                                                                                                                ) (
                                                                                                                                                  POr (
                                                                                                                                                    PChar "d"%char
                                                                                                                                                  ) (
                                                                                                                                                    POr (
                                                                                                                                                      PChar "e"%char
                                                                                                                                                    ) (
                                                                                                                                                      POr (
                                                                                                                                                        PChar "f"%char
                                                                                                                                                      ) (
                                                                                                                                                        POr (
                                                                                                                                                          PChar "g"%char
                                                                                                                                                        ) (
                                                                                                                                                          POr (
                                                                                                                                                            PChar "h"%char
                                                                                                                                                          ) (
                                                                                                                                                            POr (
                                                                                                                                                              PChar "i"%char
                                                                                                                                                            ) (
                                                                                                                                                              POr (
                                                                                                                                                                PChar "j"%char
                                                                                                                                                              ) (
                                                                                                                                                                POr (
                                                                                                                                                                  PChar "k"%char
                                                                                                                                                                ) (
                                                                                                                                                                  POr (
                                                                                                                                                                    PChar "l"%char
                                                                                                                                                                  ) (
                                                                                                                                                                    POr (
                                                                                                                                                                      PChar "m"%char
                                                                                                                                                                    ) (
                                                                                                                                                                      POr (
                                                                                                                                                                        PChar "n"%char
                                                                                                                                                                      ) (
                                                                                                                                                                        POr (
                                                                                                                                                                          PChar "o"%char
                                                                                                                                                                        ) (
                                                                                                                                                                          POr (
                                                                                                                                                                            PChar "p"%char
                                                                                                                                                                          ) (
                                                                                                                                                                            POr (
                                                                                                                                                                              PChar "q"%char
                                                                                                                                                                            ) (
                                                                                                                                                                              POr (
                                                                                                                                                                                PChar "r"%char
                                                                                                                                                                              ) (
                                                                                                                                                                                POr (
                                                                                                                                                                                  PChar "s"%char
                                                                                                                                                                                ) (
                                                                                                                                                                                  POr (
                                                                                                                                                                                    PChar "t"%char
                                                                                                                                                                                  ) (
                                                                                                                                                                                    POr (
                                                                                                                                                                                      PChar "u"%char
                                                                                                                                                                                    ) (
                                                                                                                                                                                      POr (
                                                                                                                                                                                        PChar "v"%char
                                                                                                                                                                                      ) (
                                                                                                                                                                                        POr (
                                                                                                                                                                                          PChar "w"%char
                                                                                                                                                                                        ) (
                                                                                                                                                                                          POr (
                                                                                                                                                                                            PChar "x"%char
                                                                                                                                                                                          ) (
                                                                                                                                                                                            POr (
                                                                                                                                                                                              PChar "y"%char
                                                                                                                                                                                            ) (
                                                                                                                                                                                              POr (
                                                                                                                                                                                                PChar "z"%char
                                                                                                                                                                                              ) (
                                                                                                                                                                                                POr (
                                                                                                                                                                                                  PChar "{"%char
                                                                                                                                                                                                ) (
                                                                                                                                                                                                  POr (
                                                                                                                                                                                                    PChar "|"%char
                                                                                                                                                                                                  ) (
                                                                                                                                                                                                    POr (
                                                                                                                                                                                                      PChar "}"%char
                                                                                                                                                                                                    ) (
                                                                                                                                                                                                      PChar "~"%char
                                                                                                                                                                                                    )
                                                                                                                                                                                                  )
                                                                                                                                                                                                )
                                                                                                                                                                                              )
                                                                                                                                                                                            )
                                                                                                                                                                                          )
                                                                                                                                                                                        )
                                                                                                                                                                                      )
                                                                                                                                                                                    )
                                                                                                                                                                                  )
                                                                                                                                                                                )
                                                                                                                                                                              )
                                                                                                                                                                            )
                                                                                                                                                                          )
                                                                                                                                                                        )
                                                                                                                                                                      )
                                                                                                                                                                    )
                                                                                                                                                                  )
                                                                                                                                                                )
                                                                                                                                                              )
                                                                                                                                                            )
                                                                                                                                                          )
                                                                                                                                                        )
                                                                                                                                                      )
                                                                                                                                                    )
                                                                                                                                                  )
                                                                                                                                                )
                                                                                                                                              )
                                                                                                                                            )
                                                                                                                                          )
                                                                                                                                        )
                                                                                                                                      )
                                                                                                                                    )
                                                                                                                                  )
                                                                                                                                )
                                                                                                                              )
                                                                                                                            )
                                                                                                                          )
                                                                                                                        )
                                                                                                                      )
                                                                                                                    )
                                                                                                                  )
                                                                                                                )
                                                                                                              )
                                                                                                            )
                                                                                                          )
                                                                                                        )
                                                                                                      )
                                                                                                    )
                                                                                                  )
                                                                                                )
                                                                                              )
                                                                                            )
                                                                                          )
                                                                                        )
                                                                                      )
                                                                                    )
                                                                                  )
                                                                                )
                                                                              )
                                                                            )
                                                                          )
                                                                        )
                                                                      )
                                                                    )
                                                                  )
                                                                )
                                                              )
                                                            )
                                                          )
                                                        )
                                                      )
                                                    )
                                                  )
                                                )
                                              )
                                            )
                                          )
                                        )
                                      )
                                    )
                                  )
                                )
                              )
                            )
                          )
                        )
                      )
                    )
                  )
                )
              )
            )
          )
        ) "c"
      )
    ) (
      deco "let s = bytes_c...afe_to_string s" (
        ELet [
          Binding (PVar "s") (
            deco "bytes_create 1" (
              EApp (deco "bytes_create" (EPath [ "bytes_create" ])) (
                deco "1" (EInt 1)
              )
            )
          )
        ] (deco "bytes_unsafe_se...afe_to_string s" __exp4)
      )
    );
    Branch (CVal (PVar "c")) (
      deco "let n = code c ...afe_to_string s" (
        ELet [
          Binding (PVar "n") (
            deco "code c" (
              EApp (deco "code" (EPath [ "code" ])) (deco "c" (EPath [ "c" ]))
            )
          )
        ] (deco "let s = bytes_c...afe_to_string s" __exp10)
      )
    )
  ].

Definition __fun12 := AnonFunction __branches11.

Definition __branches13 :=
  [
    Branch (
      CVal (
        PAlias (
          POr (PChar "A"%char) (
            POr (PChar "B"%char) (
              POr (PChar "C"%char) (
                POr (PChar "D"%char) (
                  POr (PChar "E"%char) (
                    POr (PChar "F"%char) (
                      POr (PChar "G"%char) (
                        POr (PChar "H"%char) (
                          POr (PChar "I"%char) (
                            POr (PChar "J"%char) (
                              POr (PChar "K"%char) (
                                POr (PChar "L"%char) (
                                  POr (PChar "M"%char) (
                                    POr (PChar "N"%char) (
                                      POr (PChar "O"%char) (
                                        POr (PChar "P"%char) (
                                          POr (PChar "Q"%char) (
                                            POr (PChar "R"%char) (
                                              POr (PChar "S"%char) (
                                                POr (PChar "T"%char) (
                                                  POr (PChar "U"%char) (
                                                    POr (PChar "V"%char) (
                                                      POr (PChar "W"%char) (
                                                        POr (PChar "X"%char) (
                                                          POr (PChar "Y"%char) (
                                                            PChar "Z"%char
                                                          )
                                                        )
                                                      )
                                                    )
                                                  )
                                                )
                                              )
                                            )
                                          )
                                        )
                                      )
                                    )
                                  )
                                )
                              )
                            )
                          )
                        )
                      )
                    )
                  )
                )
              )
            )
          )
        ) "c"
      )
    ) (
      deco "unsafe_chr(code c + 32)" (
        EApp (deco "unsafe_chr" (EPath [ "unsafe_chr" ])) (
          deco "(code c + 32)" (
            EIntAdd (
              deco "code c" (
                EApp (deco "code" (EPath [ "code" ])) (deco "c" (EPath [ "c" ]))
              )
            ) (deco "32" (EInt 32))
          )
        )
      )
    );
    Branch (CVal (PVar "c")) (deco "c" (EPath [ "c" ]))
  ].

Definition __fun14 := AnonFunction __branches13.

Definition __branches15 :=
  [
    Branch (
      CVal (
        PAlias (
          POr (PChar "a"%char) (
            POr (PChar "b"%char) (
              POr (PChar "c"%char) (
                POr (PChar "d"%char) (
                  POr (PChar "e"%char) (
                    POr (PChar "f"%char) (
                      POr (PChar "g"%char) (
                        POr (PChar "h"%char) (
                          POr (PChar "i"%char) (
                            POr (PChar "j"%char) (
                              POr (PChar "k"%char) (
                                POr (PChar "l"%char) (
                                  POr (PChar "m"%char) (
                                    POr (PChar "n"%char) (
                                      POr (PChar "o"%char) (
                                        POr (PChar "p"%char) (
                                          POr (PChar "q"%char) (
                                            POr (PChar "r"%char) (
                                              POr (PChar "s"%char) (
                                                POr (PChar "t"%char) (
                                                  POr (PChar "u"%char) (
                                                    POr (PChar "v"%char) (
                                                      POr (PChar "w"%char) (
                                                        POr (PChar "x"%char) (
                                                          POr (PChar "y"%char) (
                                                            PChar "z"%char
                                                          )
                                                        )
                                                      )
                                                    )
                                                  )
                                                )
                                              )
                                            )
                                          )
                                        )
                                      )
                                    )
                                  )
                                )
                              )
                            )
                          )
                        )
                      )
                    )
                  )
                )
              )
            )
          )
        ) "c"
      )
    ) (
      deco "unsafe_chr(code c - 32)" (
        EApp (deco "unsafe_chr" (EPath [ "unsafe_chr" ])) (
          deco "(code c - 32)" (
            EIntSub (
              deco "code c" (
                EApp (deco "code" (EPath [ "code" ])) (deco "c" (EPath [ "c" ]))
              )
            ) (deco "32" (EInt 32))
          )
        )
      )
    );
    Branch (CVal (PVar "c")) (deco "c" (EPath [ "c" ]))
  ].

Definition __fun16 := AnonFunction __branches15.

Definition __fun17 :=
  AnonFun "c2" (
    deco "code c1 - code c2" (
      EIntSub (
        deco "code c1" (
          EApp (deco "code" (EPath [ "code" ])) (deco "c1" (EPath [ "c1" ]))
        )
      ) (
        deco "code c2" (
          EApp (deco "code" (EPath [ "code" ])) (deco "c2" (EPath [ "c2" ]))
        )
      )
    )
  ).

Definition __fun18 := AnonFun "c1" (EAnonFun __fun17).

Definition __branches19 :=
  [
    Branch (CVal (PAlias PAny "c2")) (
      deco "compare c1 c2 = 0" (
        EOpEq (
          deco "compare c1 c2" (
            EApp (
              EApp (deco "compare" (EPath [ "compare" ])) (
                deco "c1" (EPath [ "c1" ])
              )
            ) (deco "c2" (EPath [ "c2" ]))
          )
        ) (deco "0" (EInt 0))
      )
    )
  ].

Definition __fun20 := AnonFunction __branches19.

Definition __branches21 :=
  [
    Branch (CVal (PAlias PAny "c1")) (EAnonFun __fun20)
  ].

Definition __fun22 := AnonFunction __branches21.

Definition __fun23 :=
  AnonFun "x" (
    deco "seeded_hash_param 10 100 seed x" (
      EApp (
        EApp (
          EApp (
            EApp (deco "seeded_hash_param" (EPath [ "seeded_hash_param" ])) (
              deco "10" (EInt 10)
            )
          ) (deco "100" (EInt 100))
        ) (deco "seed" (EPath [ "seed" ]))
      ) (deco "x" (EPath [ "x" ]))
    )
  ).

Definition __fun24 := AnonFun "seed" (EAnonFun __fun23).

Definition __fun25 :=
  AnonFun "x" (
    deco "seeded_hash_param 10 100 0 x" (
      EApp (
        EApp (
          EApp (
            EApp (deco "seeded_hash_param" (EPath [ "seeded_hash_param" ])) (
              deco "10" (EInt 10)
            )
          ) (deco "100" (EInt 100))
        ) (deco "0" (EInt 0))
      ) (deco "x" (EPath [ "x" ]))
    )
  ).

Definition __main :=
  MStruct [
    ILet [
      Binding (PVar "chr") (
        deco "n = if n < 0 ||...se unsafe_chr n" (EAnonFun __fun2)
      )
    ];
    ILet [
      Binding (PVar "escaped") (
        deco "function | '\''...afe_to_string s" (EAnonFun __fun12)
      )
    ];
    ILet [
      Binding (PVar "lowercase_ascii") (
        deco "function | 'A' ... + 32) | c -> c" (EAnonFun __fun14)
      )
    ];
    ILet [
      Binding (PVar "uppercase_ascii") (
        deco "function | 'a' ... - 32) | c -> c" (EAnonFun __fun16)
      )
    ];
    ILet [
      Binding (PVar "compare") (
        deco "c1 c2 = code c1 - code c2" (EAnonFun __fun18)
      )
    ];
    ILet [
      Binding (PVar "equal") (
        deco "(c1: t) (c2: t)...mpare c1 c2 = 0" (EAnonFun __fun22)
      )
    ];
    ILet [
      Binding (PVar "seeded_hash") (
        deco "seed x = seeded...m 10 100 seed x" (EAnonFun __fun24)
      )
    ];
    ILet [
      Binding (PVar "hash") (
        deco "x = seeded_hash_param 10 100 0 x" (EAnonFun __fun25)
      )
    ]
  ].

