(* This file has been generated by Osiris. Do not edit. *)

From osiris Require Import osiris.

Definition __exp0 :=
  EIntAdd (
    deco "Char.code '0'" (
      EApp (deco "Char.code" (EPath [ "Char"; "code" ])) (
        deco "'0'" (EChar "0"%char)
      )
    )
  ) (deco "n" (EPath [ "n" ])).

Definition __exp1 :=
  EIntSub (
    deco "Char.code 'a' + n" (
      EIntAdd (
        deco "Char.code 'a'" (
          EApp (deco "Char.code" (EPath [ "Char"; "code" ])) (
            deco "'a'" (EChar "a"%char)
          )
        )
      ) (deco "n" (EPath [ "n" ]))
    )
  ) (deco "10" (EInt 10)).

Definition __fun2 :=
  AnonFun "n" (
    deco "Char.chr (if n ...e 'a' + n - 10)" (
      EApp (deco "Char.chr" (EPath [ "Char"; "chr" ])) (
        deco "(if n < 10 then...e 'a' + n - 10)" (
          EIfThenElse (
            deco "n < 10" (
              EOpLt (deco "n" (EPath [ "n" ])) (deco "10" (EInt 10))
            )
          ) (deco "Char.code '0' + n" __exp0) (
            deco "Char.code 'a' + n - 10" __exp1
          )
        )
      )
    )
  ).

Definition __exp3 :=
  EApp (
    EApp (
      EApp (deco "Bytes.unsafe_set" (EPath [ "Bytes"; "unsafe_set" ])) (
        deco "result" (EPath [ "result" ])
      )
    ) (
      deco "(i*2+1)" (
        EIntAdd (
          deco "i*2" (EIntMul (deco "i" (EPath [ "i" ])) (deco "2" (EInt 2)))
        ) (deco "1" (EInt 1))
      )
    )
  ) (
    deco "(char_hex (x land 0x0f))" (
      EApp (deco "char_hex" (EPath [ "char_hex" ])) (
        deco "(x land 0x0f)" (
          EIntLand (deco "x" (EPath [ "x" ])) (deco "0x0f" (EInt 15))
        )
      )
    )
  ).

Definition __exp4 :=
  ESeq (
    deco "Bytes.unsafe_se..._hex (x lsr 4))" (
      EApp (
        EApp (
          EApp (deco "Bytes.unsafe_set" (EPath [ "Bytes"; "unsafe_set" ])) (
            deco "result" (EPath [ "result" ])
          )
        ) (
          deco "(i*2)" (EIntMul (deco "i" (EPath [ "i" ])) (deco "2" (EInt 2)))
        )
      ) (
        deco "(char_hex (x lsr 4))" (
          EApp (deco "char_hex" (EPath [ "char_hex" ])) (
            deco "(x lsr 4)" (
              EIntLsr (deco "x" (EPath [ "x" ])) (deco "4" (EInt 4))
            )
          )
        )
      )
    )
  ) (deco "Bytes.unsafe_se... (x land 0x0f))" __exp3).

Definition __exp5 :=
  ELet [
    Binding (PVar "x") (
      deco "Char.code d.[i]" (
        EApp (deco "Char.code" (EPath [ "Char"; "code" ])) (
          deco "d.[i]" (
            EApp (
              EApp (deco "d.[i]" (EPath [ "String"; "get" ])) (
                deco "d" (EPath [ "d" ])
              )
            ) (deco "i" (EPath [ "i" ]))
          )
        )
      )
    )
  ] (deco "Bytes.unsafe_se...(x land 0x0f));" __exp4).

Definition __exp6 :=
  EApp (deco "Bytes.unsafe_to_string" (EPath [ "Bytes"; "unsafe_to_string" ])) (
    deco "result" (EPath [ "result" ])
  ).

Definition __exp7 :=
  ESeq (
    deco "for i = 0 to le...nd 0x0f)); done" (
      EFor "i" (deco "0" (EInt 0)) (
        deco "len - 1" (
          EIntSub (deco "len" (EPath [ "len" ])) (deco "1" (EInt 1))
        )
      ) (deco "let x = Char.co...(x land 0x0f));" __exp5)
    )
  ) (deco "Bytes.unsafe_to_string result" __exp6).

Definition __exp8 :=
  ELet [
    Binding (PVar "result") (
      deco "Bytes.create (len * 2)" (
        EApp (deco "Bytes.create" (EPath [ "Bytes"; "create" ])) (
          deco "(len * 2)" (
            EIntMul (deco "len" (EPath [ "len" ])) (deco "2" (EInt 2))
          )
        )
      )
    )
  ] (deco "for i = 0 to le...o_string result" __exp7).

Definition __exp9 :=
  ELet [
    Binding (PVar "len") (
      deco "String.length d" (
        EApp (deco "String.length" (EPath [ "String"; "length" ])) (
          deco "d" (EPath [ "d" ])
        )
      )
    )
  ] (deco "let result = By...o_string result" __exp8).

Definition __fun10 :=
  AnonFun "d" (
    deco "let char_hex n ...o_string result" (
      ELet [
        Binding (PVar "char_hex") (
          deco "n = Char.chr (i...e 'a' + n - 10)" (EAnonFun __fun2)
        )
      ] (deco "let len = Strin...o_string result" __exp9)
    )
  ).

Definition __branches11 :=
  [
    Branch (
      COr (CVal (PChar "0"%char)) (
        COr (CVal (PChar "1"%char)) (
          COr (CVal (PChar "2"%char)) (
            COr (CVal (PChar "3"%char)) (
              COr (CVal (PChar "4"%char)) (
                COr (CVal (PChar "5"%char)) (
                  COr (CVal (PChar "6"%char)) (
                    COr (CVal (PChar "7"%char)) (
                      COr (CVal (PChar "8"%char)) (CVal (PChar "9"%char))
                    )
                  )
                )
              )
            )
          )
        )
      )
    ) (
      deco "Char.code c - Char.code '0'" (
        EIntSub (
          deco "Char.code c" (
            EApp (deco "Char.code" (EPath [ "Char"; "code" ])) (
              deco "c" (EPath [ "c" ])
            )
          )
        ) (
          deco "Char.code '0'" (
            EApp (deco "Char.code" (EPath [ "Char"; "code" ])) (
              deco "'0'" (EChar "0"%char)
            )
          )
        )
      )
    );
    Branch (
      COr (CVal (PChar "A"%char)) (
        COr (CVal (PChar "B"%char)) (
          COr (CVal (PChar "C"%char)) (
            COr (CVal (PChar "D"%char)) (
              COr (CVal (PChar "E"%char)) (CVal (PChar "F"%char))
            )
          )
        )
      )
    ) (
      deco "Char.code c - Char.code 'A' + 10" (
        EIntAdd (
          deco "Char.code c - Char.code 'A'" (
            EIntSub (
              deco "Char.code c" (
                EApp (deco "Char.code" (EPath [ "Char"; "code" ])) (
                  deco "c" (EPath [ "c" ])
                )
              )
            ) (
              deco "Char.code 'A'" (
                EApp (deco "Char.code" (EPath [ "Char"; "code" ])) (
                  deco "'A'" (EChar "A"%char)
                )
              )
            )
          )
        ) (deco "10" (EInt 10))
      )
    );
    Branch (
      COr (CVal (PChar "a"%char)) (
        COr (CVal (PChar "b"%char)) (
          COr (CVal (PChar "c"%char)) (
            COr (CVal (PChar "d"%char)) (
              COr (CVal (PChar "e"%char)) (CVal (PChar "f"%char))
            )
          )
        )
      )
    ) (
      deco "Char.code c - Char.code 'a' + 10" (
        EIntAdd (
          deco "Char.code c - Char.code 'a'" (
            EIntSub (
              deco "Char.code c" (
                EApp (deco "Char.code" (EPath [ "Char"; "code" ])) (
                  deco "c" (EPath [ "c" ])
                )
              )
            ) (
              deco "Char.code 'a'" (
                EApp (deco "Char.code" (EPath [ "Char"; "code" ])) (
                  deco "'a'" (EChar "a"%char)
                )
              )
            )
          )
        ) (deco "10" (EInt 10))
      )
    );
    Branch (CVal PAny) (
      deco "invalid_arg ""Digest.of_hex""" (
        EApp (deco "invalid_arg" (EPath [ "invalid_arg" ])) (
          deco """Digest.of_hex""" (EString "Digest.of_hex")
        )
      )
    )
  ].

Definition __fun12 :=
  AnonFun "c" (
    deco "match c with | ...""Digest.of_hex""" (
      EMatch (deco "c" (EPath [ "c" ])) __branches11
    )
  ).

Definition __fun13 :=
  AnonFun "i" (
    deco "digit s.[i] lsl 4 + digit s.[i+1]" (
      EIntAdd (
        deco "digit s.[i] lsl 4" (
          EIntLsl (
            deco "digit s.[i]" (
              EApp (deco "digit" (EPath [ "digit" ])) (
                deco "s.[i]" (
                  EApp (
                    EApp (deco "s.[i]" (EPath [ "String"; "get" ])) (
                      deco "s" (EPath [ "s" ])
                    )
                  ) (deco "i" (EPath [ "i" ]))
                )
              )
            )
          ) (deco "4" (EInt 4))
        )
      ) (
        deco "digit s.[i+1]" (
          EApp (deco "digit" (EPath [ "digit" ])) (
            deco "s.[i+1]" (
              EApp (
                EApp (deco "s.[i+1]" (EPath [ "String"; "get" ])) (
                  deco "s" (EPath [ "s" ])
                )
              ) (
                deco "i+1" (
                  EIntAdd (deco "i" (EPath [ "i" ])) (deco "1" (EInt 1))
                )
              )
            )
          )
        )
      )
    )
  ).

Definition __fun14 :=
  AnonFun "i" (
    deco "Char.chr (byte (2 * i))" (
      EApp (deco "Char.chr" (EPath [ "Char"; "chr" ])) (
        deco "(byte (2 * i))" (
          EApp (deco "byte" (EPath [ "byte" ])) (
            deco "(2 * i)" (
              EIntMul (deco "2" (EInt 2)) (deco "i" (EPath [ "i" ]))
            )
          )
        )
      )
    )
  ).

Definition __exp15 :=
  EApp (
    EApp (deco "String.init" (EPath [ "String"; "init" ])) (
      deco "(String.length s / 2)" (
        EIntDiv (
          deco "String.length s" (
            EApp (deco "String.length" (EPath [ "String"; "length" ])) (
              deco "s" (EPath [ "s" ])
            )
          )
        ) (deco "2" (EInt 2))
      )
    )
  ) (deco "(fun i -> Char....(byte (2 * i)))" (EAnonFun __fun14)).

Definition __exp16 :=
  ELet [
    Binding (PVar "byte") (
      deco "i = digit s.[i]...+ digit s.[i+1]" (EAnonFun __fun13)
    )
  ] (deco "String.init (St...(byte (2 * i)))" __exp15).

Definition __fun17 :=
  AnonFun "s" (
    deco "let digit c = m...(byte (2 * i)))" (
      ELet [
        Binding (PVar "digit") (
          deco "c = match c wit...""Digest.of_hex""" (EAnonFun __fun12)
        )
      ] (deco "let byte i = di...(byte (2 * i)))" __exp16)
    )
  ).

Definition __fun18 :=
  AnonFun "str" (
    deco "unsafe_string s...ing.length str)" (
      EApp (
        EApp (
          EApp (deco "unsafe_string" (EPath [ "unsafe_string" ])) (
            deco "str" (EPath [ "str" ])
          )
        ) (deco "0" (EInt 0))
      ) (
        deco "(String.length str)" (
          EApp (deco "String.length" (EPath [ "String"; "length" ])) (
            deco "str" (EPath [ "str" ])
          )
        )
      )
    )
  ).

Definition __fun19 :=
  AnonFun "b" (
    deco "string (Bytes.unsafe_to_string b)" (
      EApp (deco "string" (EPath [ "string" ])) (
        deco "(Bytes.unsafe_to_string b)" (
          EApp (
            deco "Bytes.unsafe_to_string" (
              EPath [
                "Bytes";
                "unsafe_to_string"
              ]
            )
          ) (deco "b" (EPath [ "b" ]))
        )
      )
    )
  ).

Definition __exp20 :=
  EApp (deco "invalid_arg" (EPath [ "invalid_arg" ])) (
    deco """Digest.substring""" (EString "Digest.substring")
  ).

Definition __exp21 :=
  EApp (
    EApp (
      EApp (deco "unsafe_string" (EPath [ "unsafe_string" ])) (
        deco "str" (EPath [ "str" ])
      )
    ) (deco "ofs" (EPath [ "ofs" ]))
  ) (deco "len" (EPath [ "len" ])).

Definition __fun22 :=
  AnonFun "len" (
    deco "if ofs < 0 || l...ing str ofs len" (
      EIfThenElse (
        deco "ofs < 0 || len ...ength str - len" (
          EBoolDisj (
            deco "ofs < 0" (
              EOpLt (deco "ofs" (EPath [ "ofs" ])) (deco "0" (EInt 0))
            )
          ) (
            deco "len < 0 || ofs ...ength str - len" (
              EBoolDisj (
                deco "len < 0" (
                  EOpLt (deco "len" (EPath [ "len" ])) (deco "0" (EInt 0))
                )
              ) (
                deco "ofs > String.length str - len" (
                  EOpGt (deco "ofs" (EPath [ "ofs" ])) (
                    deco "String.length str - len" (
                      EIntSub (
                        deco "String.length str" (
                          EApp (
                            deco "String.length" (EPath [ "String"; "length" ])
                          ) (deco "str" (EPath [ "str" ]))
                        )
                      ) (deco "len" (EPath [ "len" ]))
                    )
                  )
                )
              )
            )
          )
        )
      ) (deco "invalid_arg ""Digest.substring""" __exp20) (
        deco "unsafe_string str ofs len" __exp21
      )
    )
  ).

Definition __fun23 := AnonFun "ofs" (EAnonFun __fun22).

Definition __fun24 := AnonFun "str" (EAnonFun __fun23).

Definition __fun25 :=
  AnonFun "len" (
    deco "substring (Byte...ring b) ofs len" (
      EApp (
        EApp (
          EApp (deco "substring" (EPath [ "substring" ])) (
            deco "(Bytes.unsafe_to_string b)" (
              EApp (
                deco "Bytes.unsafe_to_string" (
                  EPath [
                    "Bytes";
                    "unsafe_to_string"
                  ]
                )
              ) (deco "b" (EPath [ "b" ]))
            )
          )
        ) (deco "ofs" (EPath [ "ofs" ]))
      ) (deco "len" (EPath [ "len" ]))
    )
  ).

Definition __fun26 := AnonFun "ofs" (EAnonFun __fun25).

Definition __fun27 := AnonFun "b" (EAnonFun __fun26).

Definition __fun28 :=
  AnonFun "ic" (
    deco "channel ic (-1)" (
      EApp (
        EApp (deco "channel" (EPath [ "channel" ])) (deco "ic" (EPath [ "ic" ]))
      ) (deco "(-1)" (EInt -1))
    )
  ).

Definition __fun29 :=
  AnonFun "filename" (
    deco "In_channel.with...hannel ic (-1))" (
      EApp (
        EApp (
          deco "In_channel.with_open_bin" (
            EPath [
              "In_channel";
              "with_open_bin"
            ]
          )
        ) (deco "filename" (EPath [ "filename" ]))
      ) (deco "(fun ic -> channel ic (-1))" (EAnonFun __fun28))
    )
  ).

Definition __fun30 :=
  AnonFun "digest" (
    deco "output_string chan digest" (
      EApp (
        EApp (deco "output_string" (EPath [ "output_string" ])) (
          deco "chan" (EPath [ "chan" ])
        )
      ) (deco "digest" (EPath [ "digest" ]))
    )
  ).

Definition __fun31 := AnonFun "chan" (EAnonFun __fun30).

Definition __fun32 :=
  AnonFun "chan" (
    deco "really_input_string chan 16" (
      EApp (
        EApp (deco "really_input_string" (EPath [ "really_input_string" ])) (
          deco "chan" (EPath [ "chan" ])
        )
      ) (deco "16" (EInt 16))
    )
  ).

Definition __exp33 :=
  EApp (deco "invalid_arg" (EPath [ "invalid_arg" ])) (
    deco """Digest.to_hex""" (EString "Digest.to_hex")
  ).

Definition __exp34 :=
  EApp (deco "hex_of_string" (EPath [ "hex_of_string" ])) (
    deco "d" (EPath [ "d" ])
  ).

Definition __fun35 :=
  AnonFun "d" (
    deco "if String.lengt...hex_of_string d" (
      ESeq (
        deco "if String.lengt...""Digest.to_hex""" (
          EIfThen (
            deco "String.length d <> 16" (
              EOpNe (
                deco "String.length d" (
                  EApp (deco "String.length" (EPath [ "String"; "length" ])) (
                    deco "d" (EPath [ "d" ])
                  )
                )
              ) (deco "16" (EInt 16))
            )
          ) (deco "invalid_arg ""Digest.to_hex""" __exp33)
        )
      ) (deco "hex_of_string d" __exp34)
    )
  ).

Definition __exp36 :=
  EApp (deco "invalid_arg" (EPath [ "invalid_arg" ])) (
    deco """Digest.from_hex""" (EString "Digest.from_hex")
  ).

Definition __exp37 :=
  EApp (deco "string_of_hex" (EPath [ "string_of_hex" ])) (
    deco "s" (EPath [ "s" ])
  ).

Definition __fun38 :=
  AnonFun "s" (
    deco "if String.lengt...string_of_hex s" (
      ESeq (
        deco "if String.lengt...igest.from_hex""" (
          EIfThen (
            deco "String.length s <> 32" (
              EOpNe (
                deco "String.length s" (
                  EApp (deco "String.length" (EPath [ "String"; "length" ])) (
                    deco "s" (EPath [ "s" ])
                  )
                )
              ) (deco "32" (EInt 32))
            )
          ) (deco "invalid_arg ""Digest.from_hex""" __exp36)
        )
      ) (deco "string_of_hex s" __exp37)
    )
  ).

Definition __main :=
  MStruct [
    ILet [
      Binding (PVar "hex_of_string") (
        deco "d = let char_he...o_string result" (EAnonFun __fun10)
      )
    ];
    ILet [
      Binding (PVar "string_of_hex") (
        deco "s = let digit c...(byte (2 * i)))" (EAnonFun __fun17)
      )
    ];
    IModule "BLAKE2" MUnsupported;
    IModule "BLAKE128" MUnsupported;
    IModule "BLAKE256" MUnsupported;
    IModule "BLAKE512" MUnsupported;
    IModule "MD5" (
      MStruct [
        ILet [
          Binding (PVar "hash_length") (deco "16" (EInt 16))
        ];
        ILet [
          Binding (PVar "compare") (
            deco "String.compare" (EPath [ "String"; "compare" ])
          )
        ];
        ILet [
          Binding (PVar "equal") (
            deco "String.equal" (EPath [ "String"; "equal" ])
          )
        ];
        ILet [
          Binding (PVar "string") (
            deco "str = unsafe_st...ing.length str)" (EAnonFun __fun18)
          )
        ];
        ILet [
          Binding (PVar "bytes") (
            deco "b = string (Byt...fe_to_string b)" (EAnonFun __fun19)
          )
        ];
        ILet [
          Binding (PVar "substring") (
            deco "str ofs len = i...ing str ofs len" (EAnonFun __fun24)
          )
        ];
        ILet [
          Binding (PVar "subbytes") (
            deco "b ofs len = sub...ring b) ofs len" (EAnonFun __fun27)
          )
        ];
        ILet [
          Binding (PVar "file") (
            deco "filename = In_c...hannel ic (-1))" (EAnonFun __fun29)
          )
        ];
        ILet [
          Binding (PVar "output") (
            deco "chan digest = o...ing chan digest" (EAnonFun __fun31)
          )
        ];
        ILet [
          Binding (PVar "input") (
            deco "chan = really_i..._string chan 16" (EAnonFun __fun32)
          )
        ];
        ILet [
          Binding (PVar "to_hex") (
            deco "d = if String.l...hex_of_string d" (EAnonFun __fun35)
          )
        ];
        ILet [
          Binding (PVar "of_hex") (
            deco "s = if String.l...string_of_hex s" (EAnonFun __fun38)
          )
        ]
      ]
    );
    IInclude (MPath [ "MD5" ]);
    ILet [
      Binding (PVar "from_hex") (deco "of_hex" (EPath [ "of_hex" ]))
    ]
  ].

