(* This file has been generated by Osiris. Do not edit. *)

From osiris Require Import osiris.

Definition __main :=
  MStruct [
    IModule "Array" (MPath [ "Dummy_stdlib__Array" ]);
    IModule "Bigarray" (MPath [ "Dummy_stdlib__Bigarray" ]);
    IModule "Bool" (MPath [ "Dummy_stdlib__Bool" ]);
    IModule "Buffer" (MPath [ "Dummy_stdlib__Buffer" ]);
    IModule "Bytes" (MPath [ "Dummy_stdlib__Bytes" ]);
    IModule "Char" (MPath [ "Dummy_stdlib__Char" ]);
    IModule "Condition" (MPath [ "Dummy_stdlib__Condition" ]);
    IModule "Digest" (MPath [ "Dummy_stdlib__Digest" ]);
    IModule "Either" (MPath [ "Dummy_stdlib__Either" ]);
    IModule "Fun" (MPath [ "Dummy_stdlib__Fun" ]);
    IModule "Gc" (MPath [ "Dummy_stdlib__Gc" ]);
    IModule "Int" (MPath [ "Dummy_stdlib__Int" ]);
    IModule "Int32" (MPath [ "Dummy_stdlib__Int32" ]);
    IModule "Int64" (MPath [ "Dummy_stdlib__Int64" ]);
    IModule "List" (MPath [ "Dummy_stdlib__List" ]);
    IModule "Map" (MPath [ "Dummy_stdlib__Map" ]);
    IModule "Mutex" (MPath [ "Dummy_stdlib__Mutex" ]);
    IModule "Nativeint" (MPath [ "Dummy_stdlib__Nativeint" ]);
    IModule "Option" (MPath [ "Dummy_stdlib__Option" ]);
    IModule "Queue" (MPath [ "Dummy_stdlib__Queue" ]);
    IModule "Result" (MPath [ "Dummy_stdlib__Result" ]);
    IModule "Semaphore" (MPath [ "Dummy_stdlib__Semaphore" ]);
    IModule "Seq" (MPath [ "Dummy_stdlib__Seq" ]);
    IModule "Set" (MPath [ "Dummy_stdlib__Set" ]);
    IModule "Stack" (MPath [ "Dummy_stdlib__Stack" ]);
    IModule "String" (MPath [ "Dummy_stdlib__String" ]);
    IModule "Uchar" (MPath [ "Dummy_stdlib__Uchar" ]);
    IModule "Unit" (MPath [ "Dummy_stdlib__Unit" ])
  ].

