(* This file has been generated by Osiris. Do not edit. *)

From osiris Require Import osiris.

Definition __fun0 :=
  AnonFun "v" (deco "Left v" (EData "Left" [ deco "v" (EPath [ "v" ]) ])).

Definition __fun1 :=
  AnonFun "v" (deco "Right v" (EData "Right" [ deco "v" (EPath [ "v" ]) ])).

Definition __branches2 :=
  [
    Branch (CVal (PData "Left" [ PAny ])) (deco "true" (EData "true" []));
    Branch (CVal (PData "Right" [ PAny ])) (deco "false" (EData "false" []))
  ].

Definition __fun3 := AnonFunction __branches2.

Definition __branches4 :=
  [
    Branch (CVal (PData "Left" [ PAny ])) (deco "false" (EData "false" []));
    Branch (CVal (PData "Right" [ PAny ])) (deco "true" (EData "true" []))
  ].

Definition __fun5 := AnonFunction __branches4.

Definition __branches6 :=
  [
    Branch (CVal (PData "Left" [ PVar "v" ])) (
      deco "Some v" (EData "Some" [ deco "v" (EPath [ "v" ]) ])
    );
    Branch (CVal (PData "Right" [ PAny ])) (deco "None" (EData "None" []))
  ].

Definition __fun7 := AnonFunction __branches6.

Definition __branches8 :=
  [
    Branch (CVal (PData "Left" [ PAny ])) (deco "None" (EData "None" []));
    Branch (CVal (PData "Right" [ PVar "v" ])) (
      deco "Some v" (EData "Some" [ deco "v" (EPath [ "v" ]) ])
    )
  ].

Definition __fun9 := AnonFunction __branches8.

Definition __branches10 :=
  [
    Branch (CVal (PData "Left" [ PVar "v" ])) (
      deco "Left (f v)" (
        EData "Left" [
          deco "(f v)" (
            EApp (deco "f" (EPath [ "f" ])) (deco "v" (EPath [ "v" ]))
          )
        ]
      )
    );
    Branch (CVal (PAlias (PData "Right" [ PAny ]) "e")) (
      deco "e" (EPath [ "e" ])
    )
  ].

Definition __fun11 := AnonFunction __branches10.

Definition __fun12 := AnonFun "f" (EAnonFun __fun11).

Definition __branches13 :=
  [
    Branch (CVal (PAlias (PData "Left" [ PAny ]) "e")) (
      deco "e" (EPath [ "e" ])
    );
    Branch (CVal (PData "Right" [ PVar "v" ])) (
      deco "Right (f v)" (
        EData "Right" [
          deco "(f v)" (
            EApp (deco "f" (EPath [ "f" ])) (deco "v" (EPath [ "v" ]))
          )
        ]
      )
    )
  ].

Definition __fun14 := AnonFunction __branches13.

Definition __fun15 := AnonFun "f" (EAnonFun __fun14).

Definition __main :=
  MStruct [
    ILet [
      Binding (PVar "left") (deco "v = Left v" (EAnonFun __fun0))
    ];
    ILet [
      Binding (PVar "right") (deco "v = Right v" (EAnonFun __fun1))
    ];
    ILet [
      Binding (PVar "is_left") (
        deco "function | Left...ight _ -> false" (EAnonFun __fun3)
      )
    ];
    ILet [
      Binding (PVar "is_right") (
        deco "function | Left...Right _ -> true" (EAnonFun __fun5)
      )
    ];
    ILet [
      Binding (PVar "find_left") (
        deco "function | Left...Right _ -> None" (EAnonFun __fun7)
      )
    ];
    ILet [
      Binding (PVar "find_right") (
        deco "function | Left...ght v -> Some v" (EAnonFun __fun9)
      )
    ];
    ILet [
      Binding (PVar "map_left") (
        deco "f = function | ...ght _ as e -> e" (EAnonFun __fun12)
      )
    ];
    ILet [
      Binding (PVar "map_right") (
        deco "f = function | ... -> Right (f v)" (EAnonFun __fun15)
      )
    ];
    ILet [
      Binding (PVar "map") (
        deco "~left ~right = ...Right (right v)" EUnsupported
      )
    ];
    ILet [
      Binding (PVar "fold") (
        deco "~left ~right = ...ht v -> right v" EUnsupported
      )
    ];
    ILet [
      Binding (PVar "iter") (deco "fold" (EPath [ "fold" ]))
    ];
    ILet [
      Binding (PVar "for_all") (deco "fold" (EPath [ "fold" ]))
    ];
    ILet [
      Binding (PVar "equal") (
        deco "~left ~right e1...Left _ -> false" EUnsupported
      )
    ];
    ILet [
      Binding (PVar "compare") (
        deco "~left ~right e1... _, Left _ -> 1" EUnsupported
      )
    ]
  ].

