(* This file has been generated by Osiris. Do not edit. *)

From osiris Require Import osiris.

Definition __branches0 := [ Branch (CVal PAny) (deco "c" (EPath [ "c" ])) ].

Definition __fun1 := AnonFunction __branches0.

Definition __fun2 := AnonFun "c" (EAnonFun __fun1).

Definition __fun3 :=
  AnonFun "x" (
    deco "f (g x)" (
      EApp (deco "f" (EPath [ "f" ])) (
        deco "(g x)" (
          EApp (deco "g" (EPath [ "g" ])) (deco "x" (EPath [ "x" ]))
        )
      )
    )
  ).

Definition __fun4 := AnonFun "g" (EAnonFun __fun3).

Definition __fun5 := AnonFun "f" (EAnonFun __fun4).

Definition __fun6 :=
  AnonFun "y" (
    deco "f y x" (
      EApp (EApp (deco "f" (EPath [ "f" ])) (deco "y" (EPath [ "y" ]))) (
        deco "x" (EPath [ "x" ])
      )
    )
  ).

Definition __fun7 := AnonFun "x" (EAnonFun __fun6).

Definition __fun8 := AnonFun "f" (EAnonFun __fun7).

Definition __fun9 :=
  AnonFun "v" (
    deco "not (p v)" (
      EBoolNeg (
        deco "(p v)" (
          EApp (deco "p" (EPath [ "p" ])) (deco "v" (EPath [ "v" ]))
        )
      )
    )
  ).

Definition __fun10 := AnonFun "p" (EAnonFun __fun9).

Definition __branches11 :=
  [
    Branch (CVal (PXData [ "Finally_raised" ] [ PVar "exn" ])) (
      deco "Some (""Fun.Fina....to_string exn)" (
        EData "Some" [
          deco "(""Fun.Finally_r....to_string exn)" (
            EApp (
              EApp (deco "^" (EPath [ "^" ])) (
                deco """Fun.Finally_raised: """ (EString "Fun.Finally_raised: ")
              )
            ) (
              deco "Printexc.to_string exn" (
                EApp (
                  deco "Printexc.to_string" (EPath [ "Printexc"; "to_string" ])
                ) (deco "exn" (EPath [ "exn" ]))
              )
            )
          )
        ]
      )
    );
    Branch (CVal PAny) (deco "None" (EData "None" []))
  ].

Definition __fun12 := AnonFunction __branches11.

Definition __main :=
  MStruct [
    ILet [
      Binding (PVar "const") (deco "c _ = c" (EAnonFun __fun2))
    ];
    ILet [
      Binding (PVar "compose") (deco "f g x = f (g x)" (EAnonFun __fun5))
    ];
    ILet [
      Binding (PVar "flip") (deco "f x y = f y x" (EAnonFun __fun8))
    ];
    ILet [
      Binding (PVar "negate") (deco "p v = not (p v)" (EAnonFun __fun10))
    ];
    IExtend [
      "Finally_raised"
    ];
    ILet [
      Binding (PData "()" []) (
        deco "Printexc.regist...xn) | _ -> None" (
          EApp (
            deco "Printexc.register_printer" (
              EPath [
                "Printexc";
                "register_printer"
              ]
            )
          ) (deco "function | Fina...xn) | _ -> None" (EAnonFun __fun12))
        )
      )
    ];
    ILet [
      Binding (PVar "protect") (
        deco "~(finally : uni...ork_exn work_bt" EUnsupported
      )
    ]
  ].

