(* This file has been generated by Osiris. Do not edit. *)

From osiris Require Import osiris.

Definition __branches0 :=
  [
    Branch (CVal (PData "()" [])) (deco "()" (EData "()" []))
  ].

Definition __fun1 := AnonFunction __branches0.

Definition __branches2 :=
  [
    Branch (CVal (PData "()" [])) (deco "()" (EData "()" []))
  ].

Definition __fun3 := AnonFunction __branches2.

Definition __exp4 :=
  EApp (
    EApp (
      EApp (deco "fprintf" (EPath [ "fprintf" ])) (deco "c" (EPath [ "c" ]))
    ) (
      deco """heap_chunks: %d\n""" (
        EData "Format" [
          deco """heap_chunks: %d\n""" (
            EData "String_literal" [
              deco """heap_chunks: %d\n""" (EString "heap_chunks: ");
              deco """heap_chunks: %d\n""" (
                EData "Int" [
                  deco """heap_chunks: %d\n""" (EData "Int_d" []);
                  deco """heap_chunks: %d\n""" (EData "No_padding" []);
                  deco """heap_chunks: %d\n""" (EData "No_precision" []);
                  deco """heap_chunks: %d\n""" (
                    EData "Char_literal" [
                      deco """heap_chunks: %d\n""" (EChar "
"%char);
                      deco """heap_chunks: %d\n""" (EData "End_of_format" [])
                    ]
                  )
                ]
              )
            ]
          );
          deco """heap_chunks: %d\n""" (EString "heap_chunks: %d
")
        ]
      )
    )
  ) (
    deco "st.heap_chunks" (
      ERecordAccess (deco "st" (EPath [ "st" ])) "heap_chunks"
    )
  ).

Definition __exp5 :=
  ESeq (
    deco "fprintf c ""free... st.free_blocks" (
      EApp (
        EApp (
          EApp (deco "fprintf" (EPath [ "fprintf" ])) (deco "c" (EPath [ "c" ]))
        ) (
          deco """free_blocks: %d\n""" (
            EData "Format" [
              deco """free_blocks: %d\n""" (
                EData "String_literal" [
                  deco """free_blocks: %d\n""" (EString "free_blocks: ");
                  deco """free_blocks: %d\n""" (
                    EData "Int" [
                      deco """free_blocks: %d\n""" (EData "Int_d" []);
                      deco """free_blocks: %d\n""" (EData "No_padding" []);
                      deco """free_blocks: %d\n""" (EData "No_precision" []);
                      deco """free_blocks: %d\n""" (
                        EData "Char_literal" [
                          deco """free_blocks: %d\n""" (EChar "
"%char);
                          deco """free_blocks: %d\n""" (
                            EData "End_of_format" []
                          )
                        ]
                      )
                    ]
                  )
                ]
              );
              deco """free_blocks: %d\n""" (EString "free_blocks: %d
")
            ]
          )
        )
      ) (
        deco "st.free_blocks" (
          ERecordAccess (deco "st" (EPath [ "st" ])) "free_blocks"
        )
      )
    )
  ) (deco "fprintf c ""heap... st.heap_chunks" __exp4).

Definition __exp6 :=
  ESeq (
    deco "fprintf c ""live... st.live_blocks" (
      EApp (
        EApp (
          EApp (deco "fprintf" (EPath [ "fprintf" ])) (deco "c" (EPath [ "c" ]))
        ) (
          deco """live_blocks: %d\n""" (
            EData "Format" [
              deco """live_blocks: %d\n""" (
                EData "String_literal" [
                  deco """live_blocks: %d\n""" (EString "live_blocks: ");
                  deco """live_blocks: %d\n""" (
                    EData "Int" [
                      deco """live_blocks: %d\n""" (EData "Int_d" []);
                      deco """live_blocks: %d\n""" (EData "No_padding" []);
                      deco """live_blocks: %d\n""" (EData "No_precision" []);
                      deco """live_blocks: %d\n""" (
                        EData "Char_literal" [
                          deco """live_blocks: %d\n""" (EChar "
"%char);
                          deco """live_blocks: %d\n""" (
                            EData "End_of_format" []
                          )
                        ]
                      )
                    ]
                  )
                ]
              );
              deco """live_blocks: %d\n""" (EString "live_blocks: %d
")
            ]
          )
        )
      ) (
        deco "st.live_blocks" (
          ERecordAccess (deco "st" (EPath [ "st" ])) "live_blocks"
        )
      )
    )
  ) (deco "fprintf c ""free... st.heap_chunks" __exp5).

Definition __exp7 :=
  ESeq (
    deco "fprintf c ""\n""" (
      EApp (
        EApp (deco "fprintf" (EPath [ "fprintf" ])) (deco "c" (EPath [ "c" ]))
      ) (
        deco """\n""" (
          EData "Format" [
            deco """\n""" (
              EData "Char_literal" [
                deco """\n""" (EChar "
"%char);
                deco """\n""" (EData "End_of_format" [])
              ]
            );
            deco """\n""" (EString "
")
          ]
        )
      )
    )
  ) (deco "fprintf c ""live... st.heap_chunks" __exp6).

Definition __exp8 :=
  ESeq (
    deco "fprintf c ""frag...l2 st.fragments" (
      EApp (
        EApp (
          EApp (
            EApp (deco "fprintf" (EPath [ "fprintf" ])) (
              deco "c" (EPath [ "c" ])
            )
          ) (
            deco """fragments: %*d\n""" (
              EData "Format" [
                deco """fragments: %*d\n""" (
                  EData "String_literal" [
                    deco """fragments: %*d\n""" (EString "fragments:      ");
                    deco """fragments: %*d\n""" (
                      EData "Int" [
                        deco """fragments: %*d\n""" (EData "Int_d" []);
                        deco """fragments: %*d\n""" (
                          EData "Arg_padding" [
                            deco """fragments: %*d\n""" (EData "Right" [])
                          ]
                        );
                        deco """fragments: %*d\n""" (EData "No_precision" []);
                        deco """fragments: %*d\n""" (
                          EData "Char_literal" [
                            deco """fragments: %*d\n""" (EChar "
"%char);
                            deco """fragments: %*d\n""" (
                              EData "End_of_format" []
                            )
                          ]
                        )
                      ]
                    )
                  ]
                );
                deco """fragments: %*d\n""" (EString "fragments:      %*d
")
              ]
            )
          )
        ) (deco "l2" (EPath [ "l2" ]))
      ) (
        deco "st.fragments" (
          ERecordAccess (deco "st" (EPath [ "st" ])) "fragments"
        )
      )
    )
  ) (deco "fprintf c ""\n"";... st.heap_chunks" __exp7).

Definition __exp9 :=
  ESeq (
    deco "fprintf c ""larg...st.largest_free" (
      EApp (
        EApp (
          EApp (
            EApp (deco "fprintf" (EPath [ "fprintf" ])) (
              deco "c" (EPath [ "c" ])
            )
          ) (
            deco """largest_free: %*d\n""" (
              EData "Format" [
                deco """largest_free: %*d\n""" (
                  EData "String_literal" [
                    deco """largest_free: %*d\n""" (EString "largest_free:   ");
                    deco """largest_free: %*d\n""" (
                      EData "Int" [
                        deco """largest_free: %*d\n""" (EData "Int_d" []);
                        deco """largest_free: %*d\n""" (
                          EData "Arg_padding" [
                            deco """largest_free: %*d\n""" (EData "Right" [])
                          ]
                        );
                        deco """largest_free: %*d\n""" (EData "No_precision" []);
                        deco """largest_free: %*d\n""" (
                          EData "Char_literal" [
                            deco """largest_free: %*d\n""" (EChar "
"%char);
                            deco """largest_free: %*d\n""" (
                              EData "End_of_format" []
                            )
                          ]
                        )
                      ]
                    )
                  ]
                );
                deco """largest_free: %*d\n""" (EString "largest_free:   %*d
")
              ]
            )
          )
        ) (deco "l2" (EPath [ "l2" ]))
      ) (
        deco "st.largest_free" (
          ERecordAccess (deco "st" (EPath [ "st" ])) "largest_free"
        )
      )
    )
  ) (deco "fprintf c ""frag... st.heap_chunks" __exp8).

Definition __exp10 :=
  ESeq (
    deco "fprintf c ""free...2 st.free_words" (
      EApp (
        EApp (
          EApp (
            EApp (deco "fprintf" (EPath [ "fprintf" ])) (
              deco "c" (EPath [ "c" ])
            )
          ) (
            deco """free_words: %*d\n""" (
              EData "Format" [
                deco """free_words: %*d\n""" (
                  EData "String_literal" [
                    deco """free_words: %*d\n""" (EString "free_words:     ");
                    deco """free_words: %*d\n""" (
                      EData "Int" [
                        deco """free_words: %*d\n""" (EData "Int_d" []);
                        deco """free_words: %*d\n""" (
                          EData "Arg_padding" [
                            deco """free_words: %*d\n""" (EData "Right" [])
                          ]
                        );
                        deco """free_words: %*d\n""" (EData "No_precision" []);
                        deco """free_words: %*d\n""" (
                          EData "Char_literal" [
                            deco """free_words: %*d\n""" (EChar "
"%char);
                            deco """free_words: %*d\n""" (
                              EData "End_of_format" []
                            )
                          ]
                        )
                      ]
                    )
                  ]
                );
                deco """free_words: %*d\n""" (EString "free_words:     %*d
")
              ]
            )
          )
        ) (deco "l2" (EPath [ "l2" ]))
      ) (
        deco "st.free_words" (
          ERecordAccess (deco "st" (EPath [ "st" ])) "free_words"
        )
      )
    )
  ) (deco "fprintf c ""larg... st.heap_chunks" __exp9).

Definition __exp11 :=
  ESeq (
    deco "fprintf c ""live...2 st.live_words" (
      EApp (
        EApp (
          EApp (
            EApp (deco "fprintf" (EPath [ "fprintf" ])) (
              deco "c" (EPath [ "c" ])
            )
          ) (
            deco """live_words: %*d\n""" (
              EData "Format" [
                deco """live_words: %*d\n""" (
                  EData "String_literal" [
                    deco """live_words: %*d\n""" (EString "live_words:     ");
                    deco """live_words: %*d\n""" (
                      EData "Int" [
                        deco """live_words: %*d\n""" (EData "Int_d" []);
                        deco """live_words: %*d\n""" (
                          EData "Arg_padding" [
                            deco """live_words: %*d\n""" (EData "Right" [])
                          ]
                        );
                        deco """live_words: %*d\n""" (EData "No_precision" []);
                        deco """live_words: %*d\n""" (
                          EData "Char_literal" [
                            deco """live_words: %*d\n""" (EChar "
"%char);
                            deco """live_words: %*d\n""" (
                              EData "End_of_format" []
                            )
                          ]
                        )
                      ]
                    )
                  ]
                );
                deco """live_words: %*d\n""" (EString "live_words:     %*d
")
              ]
            )
          )
        ) (deco "l2" (EPath [ "l2" ]))
      ) (
        deco "st.live_words" (
          ERecordAccess (deco "st" (EPath [ "st" ])) "live_words"
        )
      )
    )
  ) (deco "fprintf c ""free... st.heap_chunks" __exp10).

Definition __exp12 :=
  ESeq (
    deco "fprintf c ""heap...2 st.heap_words" (
      EApp (
        EApp (
          EApp (
            EApp (deco "fprintf" (EPath [ "fprintf" ])) (
              deco "c" (EPath [ "c" ])
            )
          ) (
            deco """heap_words: %*d\n""" (
              EData "Format" [
                deco """heap_words: %*d\n""" (
                  EData "String_literal" [
                    deco """heap_words: %*d\n""" (EString "heap_words:     ");
                    deco """heap_words: %*d\n""" (
                      EData "Int" [
                        deco """heap_words: %*d\n""" (EData "Int_d" []);
                        deco """heap_words: %*d\n""" (
                          EData "Arg_padding" [
                            deco """heap_words: %*d\n""" (EData "Right" [])
                          ]
                        );
                        deco """heap_words: %*d\n""" (EData "No_precision" []);
                        deco """heap_words: %*d\n""" (
                          EData "Char_literal" [
                            deco """heap_words: %*d\n""" (EChar "
"%char);
                            deco """heap_words: %*d\n""" (
                              EData "End_of_format" []
                            )
                          ]
                        )
                      ]
                    )
                  ]
                );
                deco """heap_words: %*d\n""" (EString "heap_words:     %*d
")
              ]
            )
          )
        ) (deco "l2" (EPath [ "l2" ]))
      ) (
        deco "st.heap_words" (
          ERecordAccess (deco "st" (EPath [ "st" ])) "heap_words"
        )
      )
    )
  ) (deco "fprintf c ""live... st.heap_chunks" __exp11).

Definition __exp13 :=
  ESeq (
    deco "fprintf c ""top_....top_heap_words" (
      EApp (
        EApp (
          EApp (
            EApp (deco "fprintf" (EPath [ "fprintf" ])) (
              deco "c" (EPath [ "c" ])
            )
          ) (
            deco """top_heap_words: %*d\n""" (
              EData "Format" [
                deco """top_heap_words: %*d\n""" (
                  EData "String_literal" [
                    deco """top_heap_words: %*d\n""" (
                      EString "top_heap_words: "
                    );
                    deco """top_heap_words: %*d\n""" (
                      EData "Int" [
                        deco """top_heap_words: %*d\n""" (EData "Int_d" []);
                        deco """top_heap_words: %*d\n""" (
                          EData "Arg_padding" [
                            deco """top_heap_words: %*d\n""" (EData "Right" [])
                          ]
                        );
                        deco """top_heap_words: %*d\n""" (
                          EData "No_precision" []
                        );
                        deco """top_heap_words: %*d\n""" (
                          EData "Char_literal" [
                            deco """top_heap_words: %*d\n""" (EChar "
"%char);
                            deco """top_heap_words: %*d\n""" (
                              EData "End_of_format" []
                            )
                          ]
                        )
                      ]
                    )
                  ]
                );
                deco """top_heap_words: %*d\n""" (
                  EString "top_heap_words: %*d
"
                )
              ]
            )
          )
        ) (deco "l2" (EPath [ "l2" ]))
      ) (
        deco "st.top_heap_words" (
          ERecordAccess (deco "st" (EPath [ "st" ])) "top_heap_words"
        )
      )
    )
  ) (deco "fprintf c ""heap... st.heap_chunks" __exp12).

Definition __exp14 :=
  ELet [
    Binding (PVar "l2") (
      deco "String.length (...top_heap_words)" (
        EApp (deco "String.length" (EPath [ "String"; "length" ])) (
          deco "(sprintf ""%d"" st.top_heap_words)" (
            EApp (
              EApp (deco "sprintf" (EPath [ "sprintf" ])) (
                deco """%d""" (
                  EData "Format" [
                    deco """%d""" (
                      EData "Int" [
                        deco """%d""" (EData "Int_d" []);
                        deco """%d""" (EData "No_padding" []);
                        deco """%d""" (EData "No_precision" []);
                        deco """%d""" (EData "End_of_format" [])
                      ]
                    );
                    deco """%d""" (EString "%d")
                  ]
                )
              )
            ) (
              deco "st.top_heap_words" (
                ERecordAccess (deco "st" (EPath [ "st" ])) "top_heap_words"
              )
            )
          )
        )
      )
    )
  ] (deco "fprintf c ""top_... st.heap_chunks" __exp13).

Definition __exp15 :=
  ESeq (
    deco "fprintf c ""\n""" (
      EApp (
        EApp (deco "fprintf" (EPath [ "fprintf" ])) (deco "c" (EPath [ "c" ]))
      ) (
        deco """\n""" (
          EData "Format" [
            deco """\n""" (
              EData "Char_literal" [
                deco """\n""" (EChar "
"%char);
                deco """\n""" (EData "End_of_format" [])
              ]
            );
            deco """\n""" (EString "
")
          ]
        )
      )
    )
  ) (deco "let l2 = String... st.heap_chunks" __exp14).

Definition __exp16 :=
  ESeq (
    deco "fprintf c ""majo... st.major_words" (
      EApp (
        EApp (
          EApp (
            EApp (deco "fprintf" (EPath [ "fprintf" ])) (
              deco "c" (EPath [ "c" ])
            )
          ) (
            deco """major_words: %*.0f\n""" (
              EData "Format" [
                deco """major_words: %*.0f\n""" (
                  EData "String_literal" [
                    deco """major_words: %*.0f\n""" (EString "major_words:    ");
                    deco """major_words: %*.0f\n""" (
                      EData "Float" [
                        deco """major_words: %*.0f\n""" (
                          ETuple [
                            deco """major_words: %*.0f\n""" (
                              EData "Float_flag_" []
                            );
                            deco """major_words: %*.0f\n""" (EData "Float_f" [])
                          ]
                        );
                        deco """major_words: %*.0f\n""" (
                          EData "Arg_padding" [
                            deco """major_words: %*.0f\n""" (EData "Right" [])
                          ]
                        );
                        deco """major_words: %*.0f\n""" (
                          EData "Lit_precision" [
                            deco """major_words: %*.0f\n""" (EInt 0)
                          ]
                        );
                        deco """major_words: %*.0f\n""" (
                          EData "Char_literal" [
                            deco """major_words: %*.0f\n""" (EChar "
"%char);
                            deco """major_words: %*.0f\n""" (
                              EData "End_of_format" []
                            )
                          ]
                        )
                      ]
                    )
                  ]
                );
                deco """major_words: %*.0f\n""" (
                  EString "major_words:    %*.0f
"
                )
              ]
            )
          )
        ) (deco "l1" (EPath [ "l1" ]))
      ) (
        deco "st.major_words" (
          ERecordAccess (deco "st" (EPath [ "st" ])) "major_words"
        )
      )
    )
  ) (deco "fprintf c ""\n"";... st.heap_chunks" __exp15).

Definition __exp17 :=
  ESeq (
    deco "fprintf c ""prom....promoted_words" (
      EApp (
        EApp (
          EApp (
            EApp (deco "fprintf" (EPath [ "fprintf" ])) (
              deco "c" (EPath [ "c" ])
            )
          ) (
            deco """promoted_words: %*.0f\n""" (
              EData "Format" [
                deco """promoted_words: %*.0f\n""" (
                  EData "String_literal" [
                    deco """promoted_words: %*.0f\n""" (
                      EString "promoted_words: "
                    );
                    deco """promoted_words: %*.0f\n""" (
                      EData "Float" [
                        deco """promoted_words: %*.0f\n""" (
                          ETuple [
                            deco """promoted_words: %*.0f\n""" (
                              EData "Float_flag_" []
                            );
                            deco """promoted_words: %*.0f\n""" (
                              EData "Float_f" []
                            )
                          ]
                        );
                        deco """promoted_words: %*.0f\n""" (
                          EData "Arg_padding" [
                            deco """promoted_words: %*.0f\n""" (
                              EData "Right" []
                            )
                          ]
                        );
                        deco """promoted_words: %*.0f\n""" (
                          EData "Lit_precision" [
                            deco """promoted_words: %*.0f\n""" (EInt 0)
                          ]
                        );
                        deco """promoted_words: %*.0f\n""" (
                          EData "Char_literal" [
                            deco """promoted_words: %*.0f\n""" (EChar "
"%char);
                            deco """promoted_words: %*.0f\n""" (
                              EData "End_of_format" []
                            )
                          ]
                        )
                      ]
                    )
                  ]
                );
                deco """promoted_words: %*.0f\n""" (
                  EString "promoted_words: %*.0f
"
                )
              ]
            )
          )
        ) (deco "l1" (EPath [ "l1" ]))
      ) (
        deco "st.promoted_words" (
          ERecordAccess (deco "st" (EPath [ "st" ])) "promoted_words"
        )
      )
    )
  ) (deco "fprintf c ""majo... st.heap_chunks" __exp16).

Definition __exp18 :=
  ESeq (
    deco "fprintf c ""mino... st.minor_words" (
      EApp (
        EApp (
          EApp (
            EApp (deco "fprintf" (EPath [ "fprintf" ])) (
              deco "c" (EPath [ "c" ])
            )
          ) (
            deco """minor_words: %*.0f\n""" (
              EData "Format" [
                deco """minor_words: %*.0f\n""" (
                  EData "String_literal" [
                    deco """minor_words: %*.0f\n""" (EString "minor_words:    ");
                    deco """minor_words: %*.0f\n""" (
                      EData "Float" [
                        deco """minor_words: %*.0f\n""" (
                          ETuple [
                            deco """minor_words: %*.0f\n""" (
                              EData "Float_flag_" []
                            );
                            deco """minor_words: %*.0f\n""" (EData "Float_f" [])
                          ]
                        );
                        deco """minor_words: %*.0f\n""" (
                          EData "Arg_padding" [
                            deco """minor_words: %*.0f\n""" (EData "Right" [])
                          ]
                        );
                        deco """minor_words: %*.0f\n""" (
                          EData "Lit_precision" [
                            deco """minor_words: %*.0f\n""" (EInt 0)
                          ]
                        );
                        deco """minor_words: %*.0f\n""" (
                          EData "Char_literal" [
                            deco """minor_words: %*.0f\n""" (EChar "
"%char);
                            deco """minor_words: %*.0f\n""" (
                              EData "End_of_format" []
                            )
                          ]
                        )
                      ]
                    )
                  ]
                );
                deco """minor_words: %*.0f\n""" (
                  EString "minor_words:    %*.0f
"
                )
              ]
            )
          )
        ) (deco "l1" (EPath [ "l1" ]))
      ) (
        deco "st.minor_words" (
          ERecordAccess (deco "st" (EPath [ "st" ])) "minor_words"
        )
      )
    )
  ) (deco "fprintf c ""prom... st.heap_chunks" __exp17).

Definition __exp19 :=
  ELet [
    Binding (PVar "l1") (
      deco "String.length (...st.minor_words)" (
        EApp (deco "String.length" (EPath [ "String"; "length" ])) (
          deco "(sprintf ""%.0f"" st.minor_words)" (
            EApp (
              EApp (deco "sprintf" (EPath [ "sprintf" ])) (
                deco """%.0f""" (
                  EData "Format" [
                    deco """%.0f""" (
                      EData "Float" [
                        deco """%.0f""" (
                          ETuple [
                            deco """%.0f""" (EData "Float_flag_" []);
                            deco """%.0f""" (EData "Float_f" [])
                          ]
                        );
                        deco """%.0f""" (EData "No_padding" []);
                        deco """%.0f""" (
                          EData "Lit_precision" [
                            deco """%.0f""" (EInt 0)
                          ]
                        );
                        deco """%.0f""" (EData "End_of_format" [])
                      ]
                    );
                    deco """%.0f""" (EString "%.0f")
                  ]
                )
              )
            ) (
              deco "st.minor_words" (
                ERecordAccess (deco "st" (EPath [ "st" ])) "minor_words"
              )
            )
          )
        )
      )
    )
  ] (deco "fprintf c ""mino... st.heap_chunks" __exp18).

Definition __exp20 :=
  ESeq (
    deco "fprintf c ""\n""" (
      EApp (
        EApp (deco "fprintf" (EPath [ "fprintf" ])) (deco "c" (EPath [ "c" ]))
      ) (
        deco """\n""" (
          EData "Format" [
            deco """\n""" (
              EData "Char_literal" [
                deco """\n""" (EChar "
"%char);
                deco """\n""" (EData "End_of_format" [])
              ]
            );
            deco """\n""" (EString "
")
          ]
        )
      )
    )
  ) (deco "let l1 = String... st.heap_chunks" __exp19).

Definition __exp21 :=
  ESeq (
    deco "fprintf c ""forc...jor_collections" (
      EApp (
        EApp (
          EApp (deco "fprintf" (EPath [ "fprintf" ])) (deco "c" (EPath [ "c" ]))
        ) (
          deco """forced_major_collections: %d\n""" (
            EData "Format" [
              deco """forced_major_collections: %d\n""" (
                EData "String_literal" [
                  deco """forced_major_collections: %d\n""" (
                    EString "forced_major_collections: "
                  );
                  deco """forced_major_collections: %d\n""" (
                    EData "Int" [
                      deco """forced_major_collections: %d\n""" (
                        EData "Int_d" []
                      );
                      deco """forced_major_collections: %d\n""" (
                        EData "No_padding" []
                      );
                      deco """forced_major_collections: %d\n""" (
                        EData "No_precision" []
                      );
                      deco """forced_major_collections: %d\n""" (
                        EData "Char_literal" [
                          deco """forced_major_collections: %d\n""" (
                            EChar "
"%char
                          );
                          deco """forced_major_collections: %d\n""" (
                            EData "End_of_format" []
                          )
                        ]
                      )
                    ]
                  )
                ]
              );
              deco """forced_major_collections: %d\n""" (
                EString "forced_major_collections: %d
"
              )
            ]
          )
        )
      ) (
        deco "st.forced_major_collections" (
          ERecordAccess (deco "st" (EPath [ "st" ])) "forced_major_collections"
        )
      )
    )
  ) (deco "fprintf c ""\n"";... st.heap_chunks" __exp20).

Definition __exp22 :=
  ESeq (
    deco "fprintf c ""comp... st.compactions" (
      EApp (
        EApp (
          EApp (deco "fprintf" (EPath [ "fprintf" ])) (deco "c" (EPath [ "c" ]))
        ) (
          deco """compactions: %d\n""" (
            EData "Format" [
              deco """compactions: %d\n""" (
                EData "String_literal" [
                  deco """compactions: %d\n""" (
                    EString "compactions:            "
                  );
                  deco """compactions: %d\n""" (
                    EData "Int" [
                      deco """compactions: %d\n""" (EData "Int_d" []);
                      deco """compactions: %d\n""" (EData "No_padding" []);
                      deco """compactions: %d\n""" (EData "No_precision" []);
                      deco """compactions: %d\n""" (
                        EData "Char_literal" [
                          deco """compactions: %d\n""" (EChar "
"%char);
                          deco """compactions: %d\n""" (
                            EData "End_of_format" []
                          )
                        ]
                      )
                    ]
                  )
                ]
              );
              deco """compactions: %d\n""" (
                EString "compactions:            %d
"
              )
            ]
          )
        )
      ) (
        deco "st.compactions" (
          ERecordAccess (deco "st" (EPath [ "st" ])) "compactions"
        )
      )
    )
  ) (deco "fprintf c ""forc... st.heap_chunks" __exp21).

Definition __exp23 :=
  ESeq (
    deco "fprintf c ""majo...jor_collections" (
      EApp (
        EApp (
          EApp (deco "fprintf" (EPath [ "fprintf" ])) (deco "c" (EPath [ "c" ]))
        ) (
          deco """major_collections: %d\n""" (
            EData "Format" [
              deco """major_collections: %d\n""" (
                EData "String_literal" [
                  deco """major_collections: %d\n""" (
                    EString "major_collections:      "
                  );
                  deco """major_collections: %d\n""" (
                    EData "Int" [
                      deco """major_collections: %d\n""" (EData "Int_d" []);
                      deco """major_collections: %d\n""" (EData "No_padding" []);
                      deco """major_collections: %d\n""" (
                        EData "No_precision" []
                      );
                      deco """major_collections: %d\n""" (
                        EData "Char_literal" [
                          deco """major_collections: %d\n""" (EChar "
"%char);
                          deco """major_collections: %d\n""" (
                            EData "End_of_format" []
                          )
                        ]
                      )
                    ]
                  )
                ]
              );
              deco """major_collections: %d\n""" (
                EString "major_collections:      %d
"
              )
            ]
          )
        )
      ) (
        deco "st.major_collections" (
          ERecordAccess (deco "st" (EPath [ "st" ])) "major_collections"
        )
      )
    )
  ) (deco "fprintf c ""comp... st.heap_chunks" __exp22).

Definition __exp24 :=
  ESeq (
    deco "fprintf c ""mino...nor_collections" (
      EApp (
        EApp (
          EApp (deco "fprintf" (EPath [ "fprintf" ])) (deco "c" (EPath [ "c" ]))
        ) (
          deco """minor_collections: %d\n""" (
            EData "Format" [
              deco """minor_collections: %d\n""" (
                EData "String_literal" [
                  deco """minor_collections: %d\n""" (
                    EString "minor_collections:      "
                  );
                  deco """minor_collections: %d\n""" (
                    EData "Int" [
                      deco """minor_collections: %d\n""" (EData "Int_d" []);
                      deco """minor_collections: %d\n""" (EData "No_padding" []);
                      deco """minor_collections: %d\n""" (
                        EData "No_precision" []
                      );
                      deco """minor_collections: %d\n""" (
                        EData "Char_literal" [
                          deco """minor_collections: %d\n""" (EChar "
"%char);
                          deco """minor_collections: %d\n""" (
                            EData "End_of_format" []
                          )
                        ]
                      )
                    ]
                  )
                ]
              );
              deco """minor_collections: %d\n""" (
                EString "minor_collections:      %d
"
              )
            ]
          )
        )
      ) (
        deco "st.minor_collections" (
          ERecordAccess (deco "st" (EPath [ "st" ])) "minor_collections"
        )
      )
    )
  ) (deco "fprintf c ""majo... st.heap_chunks" __exp23).

Definition __fun25 :=
  AnonFun "c" (
    deco "let st = stat (... st.heap_chunks" (
      ELet [
        Binding (PVar "st") (
          deco "stat ()" (
            EApp (deco "stat" (EPath [ "stat" ])) (deco "()" (EData "()" []))
          )
        )
      ] (deco "fprintf c ""mino... st.heap_chunks" __exp24)
    )
  ).

Definition __exp26 :=
  EApp (
    EApp (deco "*." (EPath [ "*." ])) (
      deco "(mi +. ma -. pro)" (
        EApp (
          EApp (deco "-." (EPath [ "-." ])) (
            deco "mi +. ma" (
              EApp (
                EApp (deco "+." (EPath [ "+." ])) (deco "mi" (EPath [ "mi" ]))
              ) (deco "ma" (EPath [ "ma" ]))
            )
          )
        ) (deco "pro" (EPath [ "pro" ]))
      )
    )
  ) (
    deco "float_of_int (Sys.word_size / 8)" (
      EApp (deco "float_of_int" (EPath [ "float_of_int" ])) (
        deco "(Sys.word_size / 8)" (
          EIntDiv (deco "Sys.word_size" (EPath [ "Sys"; "word_size" ])) (
            deco "8" (EInt 8)
          )
        )
      )
    )
  ).

Definition __branches27 :=
  [
    Branch (CVal (PData "()" [])) (
      deco "let (mi, pro, m....word_size / 8)" (
        ELet [
          Binding (PTuple [ PVar "mi"; PVar "pro"; PVar "ma" ]) (
            deco "counters ()" (
              EApp (deco "counters" (EPath [ "counters" ])) (
                deco "()" (EData "()" [])
              )
            )
          )
        ] (deco "(mi +. ma -. pr....word_size / 8)" __exp26)
      )
    )
  ].

Definition __fun28 := AnonFunction __branches27.

Definition __branches29 :=
  [
    Branch (CVal (PData "()" [])) (
      deco "finalise call_alarm arec" (
        EApp (
          EApp (deco "finalise" (EPath [ "finalise" ])) (
            deco "call_alarm" (EPath [ "call_alarm" ])
          )
        ) (deco "arec" (EPath [ "arec" ]))
      )
    )
  ].

Definition __fun30 := AnonFunction __branches29.

Definition __exp31 :=
  EApp (EApp (deco "Fun.protect" (EPath [ "Fun"; "protect" ])) EUnsupported) (
    deco "arec.f" (ERecordAccess (deco "arec" (EPath [ "arec" ])) "f")
  ).

Definition __exp32 :=
  ELet [
    Binding (PVar "finally") (
      deco "() = finalise call_alarm arec" (EAnonFun __fun30)
    )
  ] (deco "Fun.protect ~finally arec.f" __exp31).

Definition __bindings33 :=
  [
    RecBinding "call_alarm" (
      AnonFun "arec" (
        deco "if Atomic.get a...ally arec.f end" (
          EIfThen (
            deco "Atomic.get arec.active" (
              EApp (deco "Atomic.get" (EPath [ "Atomic"; "get" ])) (
                deco "arec.active" (
                  ERecordAccess (deco "arec" (EPath [ "arec" ])) "active"
                )
              )
            )
          ) (deco "begin let final...ally arec.f end" __exp32)
        )
      )
    )
  ].

Definition __fun34 :=
  AnonFun "a" (
    deco "Atomic.set a false" (
      EApp (
        EApp (deco "Atomic.set" (EPath [ "Atomic"; "set" ])) (
          deco "a" (EPath [ "a" ])
        )
      ) (deco "false" (EData "false" []))
    )
  ).

Definition __branches35 :=
  [
    Branch (CVal (PData "()" [])) (
      deco "delete_alarm arec.active" (
        EApp (deco "delete_alarm" (EPath [ "delete_alarm" ])) (
          deco "arec.active" (
            ERecordAccess (deco "arec" (EPath [ "arec" ])) "active"
          )
        )
      )
    )
  ].

Definition __fun36 := AnonFunction __branches35.

Definition __exp37 := ERecordAccess (deco "arec" (EPath [ "arec" ])) "active".

Definition __exp38 :=
  ESeq (
    deco "finalise call_alarm arec" (
      EApp (
        EApp (deco "finalise" (EPath [ "finalise" ])) (
          deco "call_alarm" (EPath [ "call_alarm" ])
        )
      ) (deco "arec" (EPath [ "arec" ]))
    )
  ) (deco "arec.active" __exp37).

Definition __exp39 :=
  ESeq (
    deco "Domain.at_exit ...rm arec.active)" (
      EApp (deco "Domain.at_exit" (EPath [ "Domain"; "at_exit" ])) (
        deco "(fun () -> dele...rm arec.active)" (EAnonFun __fun36)
      )
    )
  ) (deco "finalise call_a...ec; arec.active" __exp38).

Definition __fun40 :=
  AnonFun "f" (
    deco "let arec = { ac...ec; arec.active" (
      ELet [
        Binding (PVar "arec") (
          deco "{ active = Atom...e true; f = f }" (
            ERecord [
              Fexpr "active" (
                deco "Atomic.make true" (
                  EApp (deco "Atomic.make" (EPath [ "Atomic"; "make" ])) (
                    deco "true" (EData "true" [])
                  )
                )
              );
              Fexpr "f" (deco "f" (EPath [ "f" ]))
            ]
          )
        )
      ] (deco "Domain.at_exit ...ec; arec.active" __exp39)
    )
  ).

Definition __branches41 :=
  [
    Branch (CVal PAny) (deco "None" (EData "None" []))
  ].

Definition __fun42 := AnonFunction __branches41.

Definition __branches43 :=
  [
    Branch (CVal PAny) (deco "None" (EData "None" []))
  ].

Definition __fun44 := AnonFunction __branches43.

Definition __branches45 :=
  [
    Branch (CVal PAny) (deco "None" (EData "None" []))
  ].

Definition __fun46 := AnonFunction __branches45.

Definition __branches47 := [ Branch (CVal PAny) (deco "()" (EData "()" [])) ].

Definition __fun48 := AnonFunction __branches47.

Definition __branches49 := [ Branch (CVal PAny) (deco "()" (EData "()" [])) ].

Definition __fun50 := AnonFunction __branches49.

Definition __main :=
  MStruct [
    ILet [
      Binding (PVar "eventlog_pause") (deco "() = ()" (EAnonFun __fun1))
    ];
    ILet [
      Binding (PVar "eventlog_resume") (deco "() = ()" (EAnonFun __fun3))
    ];
    IOpen (MPath [ "Printf" ]);
    ILet [
      Binding (PVar "print_stat") (
        deco "c = let st = st... st.heap_chunks" (EAnonFun __fun25)
      )
    ];
    ILet [
      Binding (PVar "allocated_bytes") (
        deco "() = let (mi, p....word_size / 8)" (EAnonFun __fun28)
      )
    ];
    ILetRec __bindings33;
    ILet [
      Binding (PVar "delete_alarm") (
        deco "a = Atomic.set a false" (EAnonFun __fun34)
      )
    ];
    ILet [
      Binding (PVar "create_alarm") (
        deco "f = let arec = ...ec; arec.active" (EAnonFun __fun40)
      )
    ];
    IModule "Memprof" (
      MStruct [
        ILet [
          Binding (PVar "null_tracker") (
            deco "{ alloc_minor =...fun _ -> ()); }" (
              ERecord [
                Fexpr "alloc_minor" (deco "(fun _ -> None)" (EAnonFun __fun42));
                Fexpr "alloc_major" (deco "(fun _ -> None)" (EAnonFun __fun44));
                Fexpr "promote" (deco "(fun _ -> None)" (EAnonFun __fun46));
                Fexpr "dealloc_minor" (deco "(fun _ -> ())" (EAnonFun __fun48));
                Fexpr "dealloc_major" (deco "(fun _ -> ())" (EAnonFun __fun50))
              ]
            )
          )
        ];
        ILet [
          Binding (PVar "start") (
            deco "~sampling_rate ...ck_size tracker" EUnsupported
          )
        ]
      ]
    )
  ].

