(* This file has been generated by Osiris. Do not edit. *)

From osiris Require Import osiris.

Definition __fun0 :=
  AnonFun "n" (
    deco "add n 1L" (
      EApp (EApp (deco "add" (EPath [ "add" ])) (deco "n" (EPath [ "n" ]))) (
        deco "1L" EUnsupported
      )
    )
  ).

Definition __fun1 :=
  AnonFun "n" (
    deco "sub n 1L" (
      EApp (EApp (deco "sub" (EPath [ "sub" ])) (deco "n" (EPath [ "n" ]))) (
        deco "1L" EUnsupported
      )
    )
  ).

Definition __exp2 := EPath [ "n" ].

Definition __exp3 :=
  EApp (deco "neg" (EPath [ "neg" ])) (deco "n" (EPath [ "n" ])).

Definition __fun4 :=
  AnonFun "n" (
    deco "if n >= 0L then n else neg n" (
      EIfThenElse (
        deco "n >= 0L" (
          EOpGe (deco "n" (EPath [ "n" ])) (deco "0L" EUnsupported)
        )
      ) (deco "n" __exp2) (deco "neg n" __exp3)
    )
  ).

Definition __fun5 :=
  AnonFun "n" (
    deco "logxor n (-1L)" (
      EApp (
        EApp (deco "logxor" (EPath [ "logxor" ])) (deco "n" (EPath [ "n" ]))
      ) (deco "(-1L)" EUnsupported)
    )
  ).

Definition __exp6 :=
  EData "Some" [
    deco "(to_int n)" (
      EApp (deco "to_int" (EPath [ "to_int" ])) (deco "n" (EPath [ "n" ]))
    )
  ].

Definition __exp7 := EData "None" [].

Definition __fun8 :=
  AnonFun "n" (
    deco "if n >= 0L && n...nt n) else None" (
      EIfThenElse (
        deco "n >= 0L && n <= max_int" (
          EBoolConj (
            deco "n >= 0L" (
              EOpGe (deco "n" (EPath [ "n" ])) (deco "0L" EUnsupported)
            )
          ) (
            deco "n <= max_int" (
              EOpLe (deco "n" (EPath [ "n" ])) (
                deco "max_int" (EPath [ "max_int" ])
              )
            )
          )
        )
      ) (deco "Some (to_int n)" __exp6) (deco "None" __exp7)
    )
  ).

Definition __exp9 := EAnonFun __fun8.

Definition __fun10 :=
  AnonFun "n" (
    deco "format ""%d"" n" (
      EApp (
        EApp (deco "format" (EPath [ "format" ])) (deco """%d""" (EString "%d"))
      ) (deco "n" (EPath [ "n" ]))
    )
  ).

Definition __branches11 :=
  [
    Branch (CVal (PVar "__osiris_anonymous_arg")) (
      EPath [
        "__osiris_anonymous_arg"
      ]
    );
    Branch (CExc (PXData [ "Failure" ] [ PAny ])) (
      deco "None" (EData "None" [])
    )
  ].

Definition __fun12 :=
  AnonFun "s" (
    deco "try Some (of_st...ilure _ -> None" (
      EMatch (
        deco "Some (of_string s)" (
          EData "Some" [
            deco "(of_string s)" (
              EApp (deco "of_string" (EPath [ "of_string" ])) (
                deco "s" (EPath [ "s" ])
              )
            )
          ]
        )
      ) __branches11
    )
  ).

Definition __branches13 :=
  [
    Branch (CVal (PAlias PAny "y")) (
      deco "Stdlib.compare x y" (
        EApp (
          EApp (deco "Stdlib.compare" (EPath [ "Stdlib"; "compare" ])) (
            deco "x" (EPath [ "x" ])
          )
        ) (deco "y" (EPath [ "y" ]))
      )
    )
  ].

Definition __fun14 := AnonFunction __branches13.

Definition __branches15 :=
  [
    Branch (CVal (PAlias PAny "x")) (EAnonFun __fun14)
  ].

Definition __fun16 := AnonFunction __branches15.

Definition __branches17 :=
  [
    Branch (CVal (PAlias PAny "y")) (
      deco "x = y" (EOpEq (deco "x" (EPath [ "x" ])) (deco "y" (EPath [ "y" ])))
    )
  ].

Definition __fun18 := AnonFunction __branches17.

Definition __branches19 :=
  [
    Branch (CVal (PAlias PAny "x")) (EAnonFun __fun18)
  ].

Definition __fun20 := AnonFunction __branches19.

Definition __fun21 :=
  AnonFun "m" (
    deco "compare (sub n ...(sub m min_int)" (
      EApp (
        EApp (deco "compare" (EPath [ "compare" ])) (
          deco "(sub n min_int)" (
            EApp (
              EApp (deco "sub" (EPath [ "sub" ])) (deco "n" (EPath [ "n" ]))
            ) (deco "min_int" (EPath [ "min_int" ]))
          )
        )
      ) (
        deco "(sub m min_int)" (
          EApp (EApp (deco "sub" (EPath [ "sub" ])) (deco "m" (EPath [ "m" ]))) (
            deco "min_int" (EPath [ "min_int" ])
          )
        )
      )
    )
  ).

Definition __fun22 := AnonFun "n" (EAnonFun __fun21).

Definition __fun23 :=
  AnonFun "m" (
    deco "sub n min_int < sub m min_int" (
      EOpLt (
        deco "sub n min_int" (
          EApp (EApp (deco "sub" (EPath [ "sub" ])) (deco "n" (EPath [ "n" ]))) (
            deco "min_int" (EPath [ "min_int" ])
          )
        )
      ) (
        deco "sub m min_int" (
          EApp (EApp (deco "sub" (EPath [ "sub" ])) (deco "m" (EPath [ "m" ]))) (
            deco "min_int" (EPath [ "min_int" ])
          )
        )
      )
    )
  ).

Definition __fun24 := AnonFun "n" (EAnonFun __fun23).

Definition __exp25 := EPath [ "x" ].

Definition __exp26 := EPath [ "y" ].

Definition __fun27 :=
  AnonFun "y" (
    deco "if x <= y then x else y" (
      EIfThenElse (
        deco "x <= y" (
          EOpLe (deco "x" (EPath [ "x" ])) (deco "y" (EPath [ "y" ]))
        )
      ) (deco "x" __exp25) (deco "y" __exp26)
    )
  ).

Definition __fun28 := AnonFun "x" (EAnonFun __fun27).

Definition __exp29 := EPath [ "x" ].

Definition __exp30 := EPath [ "y" ].

Definition __fun31 :=
  AnonFun "y" (
    deco "if x >= y then x else y" (
      EIfThenElse (
        deco "x >= y" (
          EOpGe (deco "x" (EPath [ "x" ])) (deco "y" (EPath [ "y" ]))
        )
      ) (deco "x" __exp29) (deco "y" __exp30)
    )
  ).

Definition __fun32 := AnonFun "x" (EAnonFun __fun31).

Definition __exp33 := EPath [ "zero" ].

Definition __exp34 := EPath [ "one" ].

Definition __exp35 :=
  EIfThenElse (
    deco "unsigned_lt n d" (
      EApp (
        EApp (deco "unsigned_lt" (EPath [ "unsigned_lt" ])) (
          deco "n" (EPath [ "n" ])
        )
      ) (deco "d" (EPath [ "d" ]))
    )
  ) (deco "zero" __exp33) (deco "one" __exp34).

Definition __exp36 := EPath [ "q" ].

Definition __exp37 :=
  EApp (deco "succ" (EPath [ "succ" ])) (deco "q" (EPath [ "q" ])).

Definition __exp38 :=
  EIfThenElse (
    deco "unsigned_lt r d" (
      EApp (
        EApp (deco "unsigned_lt" (EPath [ "unsigned_lt" ])) (
          deco "r" (EPath [ "r" ])
        )
      ) (deco "d" (EPath [ "d" ]))
    )
  ) (deco "q" __exp36) (deco "succ q" __exp37).

Definition __exp39 :=
  ELet [
    Binding (PVar "r") (
      deco "sub n (mul q d)" (
        EApp (EApp (deco "sub" (EPath [ "sub" ])) (deco "n" (EPath [ "n" ]))) (
          deco "(mul q d)" (
            EApp (
              EApp (deco "mul" (EPath [ "mul" ])) (deco "q" (EPath [ "q" ]))
            ) (deco "d" (EPath [ "d" ]))
          )
        )
      )
    )
  ] (deco "if unsigned_lt ...n q else succ q" __exp38).

Definition __exp40 :=
  ELet [
    Binding (PVar "q") (
      deco "shift_left (div...gical n 1) d) 1" (
        EApp (
          EApp (deco "shift_left" (EPath [ "shift_left" ])) (
            deco "(div (shift_right_logical n 1) d)" (
              EApp (
                EApp (deco "div" (EPath [ "div" ])) (
                  deco "(shift_right_logical n 1)" (
                    EApp (
                      EApp (
                        deco "shift_right_logical" (
                          EPath [
                            "shift_right_logical"
                          ]
                        )
                      ) (deco "n" (EPath [ "n" ]))
                    ) (deco "1" (EInt 1))
                  )
                )
              ) (deco "d" (EPath [ "d" ]))
            )
          )
        ) (deco "1" (EInt 1))
      )
    )
  ] (deco "let r = sub n (...n q else succ q" __exp39).

Definition __fun41 :=
  AnonFun "d" (
    deco "if d < zero the...n q else succ q" (
      EIfThenElse (
        deco "d < zero" (
          EOpLt (deco "d" (EPath [ "d" ])) (deco "zero" (EPath [ "zero" ]))
        )
      ) (deco "if unsigned_lt ...n zero else one" __exp35) (
        deco "let q = shift_l...n q else succ q" __exp40
      )
    )
  ).

Definition __fun42 := AnonFun "n" (EAnonFun __fun41).

Definition __fun43 :=
  AnonFun "d" (
    deco "sub n (mul (unsigned_div n d) d)" (
      EApp (EApp (deco "sub" (EPath [ "sub" ])) (deco "n" (EPath [ "n" ]))) (
        deco "(mul (unsigned_div n d) d)" (
          EApp (
            EApp (deco "mul" (EPath [ "mul" ])) (
              deco "(unsigned_div n d)" (
                EApp (
                  EApp (deco "unsigned_div" (EPath [ "unsigned_div" ])) (
                    deco "n" (EPath [ "n" ])
                  )
                ) (deco "d" (EPath [ "d" ]))
              )
            )
          ) (deco "d" (EPath [ "d" ]))
        )
      )
    )
  ).

Definition __fun44 := AnonFun "n" (EAnonFun __fun43).

Definition __fun45 :=
  AnonFun "x" (
    deco "seeded_hash_param 10 100 seed x" (
      EApp (
        EApp (
          EApp (
            EApp (deco "seeded_hash_param" (EPath [ "seeded_hash_param" ])) (
              deco "10" (EInt 10)
            )
          ) (deco "100" (EInt 100))
        ) (deco "seed" (EPath [ "seed" ]))
      ) (deco "x" (EPath [ "x" ]))
    )
  ).

Definition __fun46 := AnonFun "seed" (EAnonFun __fun45).

Definition __fun47 :=
  AnonFun "x" (
    deco "seeded_hash_param 10 100 0 x" (
      EApp (
        EApp (
          EApp (
            EApp (deco "seeded_hash_param" (EPath [ "seeded_hash_param" ])) (
              deco "10" (EInt 10)
            )
          ) (deco "100" (EInt 100))
        ) (deco "0" (EInt 0))
      ) (deco "x" (EPath [ "x" ]))
    )
  ).

Definition __main :=
  MStruct [
    ILet [
      Binding (PVar "zero") (deco "0L" EUnsupported)
    ];
    ILet [
      Binding (PVar "one") (deco "1L" EUnsupported)
    ];
    ILet [
      Binding (PVar "minus_one") (deco "-1L" EUnsupported)
    ];
    ILet [
      Binding (PVar "succ") (deco "n = add n 1L" (EAnonFun __fun0))
    ];
    ILet [
      Binding (PVar "pred") (deco "n = sub n 1L" (EAnonFun __fun1))
    ];
    ILet [
      Binding (PVar "abs") (
        deco "n = if n >= 0L then n else neg n" (EAnonFun __fun4)
      )
    ];
    ILet [
      Binding (PVar "min_int") (deco "0x8000000000000000L" EUnsupported)
    ];
    ILet [
      Binding (PVar "max_int") (deco "0x7FFFFFFFFFFFFFFFL" EUnsupported)
    ];
    ILet [
      Binding (PVar "lognot") (deco "n = logxor n (-1L)" (EAnonFun __fun5))
    ];
    ILet [
      Binding (PVar "unsigned_to_int") (
        deco "let max_int = o...nt n) else None" (
          ELet [
            Binding (PVar "max_int") (
              deco "of_int Stdlib.max_int" (
                EApp (deco "of_int" (EPath [ "of_int" ])) (
                  deco "Stdlib.max_int" (EPath [ "Stdlib"; "max_int" ])
                )
              )
            )
          ] (deco "fun n -> if n >...nt n) else None" __exp9)
        )
      )
    ];
    ILet [
      Binding (PVar "to_string") (deco "n = format ""%d"" n" (EAnonFun __fun10))
    ];
    ILet [
      Binding (PVar "of_string_opt") (
        deco "s = try Some (o...ilure _ -> None" (EAnonFun __fun12)
      )
    ];
    ILet [
      Binding (PVar "compare") (
        deco "(x: t) (y: t) =...lib.compare x y" (EAnonFun __fun16)
      )
    ];
    ILet [
      Binding (PVar "equal") (deco "(x: t) (y: t) = x = y" (EAnonFun __fun20))
    ];
    ILet [
      Binding (PVar "unsigned_compare") (
        deco "n m = compare (...(sub m min_int)" (EAnonFun __fun22)
      )
    ];
    ILet [
      Binding (PVar "unsigned_lt") (
        deco "n m = sub n min...< sub m min_int" (EAnonFun __fun24)
      )
    ];
    ILet [
      Binding (PVar "min") (
        deco "x y : t = if x <= y then x else y" (EAnonFun __fun28)
      )
    ];
    ILet [
      Binding (PVar "max") (
        deco "x y : t = if x >= y then x else y" (EAnonFun __fun32)
      )
    ];
    ILet [
      Binding (PVar "unsigned_div") (
        deco "n d = if d < ze...n q else succ q" (EAnonFun __fun42)
      )
    ];
    ILet [
      Binding (PVar "unsigned_rem") (
        deco "n d = sub n (mu...ned_div n d) d)" (EAnonFun __fun44)
      )
    ];
    ILet [
      Binding (PVar "seeded_hash") (
        deco "seed x = seeded...m 10 100 seed x" (EAnonFun __fun46)
      )
    ];
    ILet [
      Binding (PVar "hash") (
        deco "x = seeded_hash_param 10 100 0 x" (EAnonFun __fun47)
      )
    ]
  ].

