(* This file has been generated by Osiris. Do not edit. *)

From osiris Require Import osiris.

Definition __exp0 := EPath [ "x" ].

Definition __exp1 :=
  EApp (deco "reraise" (EPath [ "reraise" ])) (deco "e" (EPath [ "e" ])).

Definition __branches2 :=
  [
    Branch (CVal (PVar "x")) (
      deco "unlock m; x" (
        ESeq (
          deco "unlock m" (
            EApp (deco "unlock" (EPath [ "unlock" ])) (deco "m" (EPath [ "m" ]))
          )
        ) (deco "x" __exp0)
      )
    );
    Branch (CExc (PVar "e")) (
      deco "unlock m; reraise e" (
        ESeq (
          deco "unlock m" (
            EApp (deco "unlock" (EPath [ "unlock" ])) (deco "m" (EPath [ "m" ]))
          )
        ) (deco "reraise e" __exp1)
      )
    )
  ].

Definition __exp3 :=
  EMatch (
    deco "f()" (EApp (deco "f" (EPath [ "f" ])) (deco "()" (EData "()" [])))
  ) __branches2.

Definition __fun4 :=
  AnonFun "f" (
    deco "lock m; match f...ck m; reraise e" (
      ESeq (
        deco "lock m" (
          EApp (deco "lock" (EPath [ "lock" ])) (deco "m" (EPath [ "m" ]))
        )
      ) (deco "match f() with ...ck m; reraise e" __exp3)
    )
  ).

Definition __fun5 := AnonFun "m" (EAnonFun __fun4).

Definition __main :=
  MStruct [
    ILet [
      Binding (PVar "protect") (
        deco "m f = lock m; m...ck m; reraise e" (EAnonFun __fun5)
      )
    ]
  ].

