(* This file has been generated by Osiris. Do not edit. *)

From osiris Require Import osiris.

Definition __branches0 :=
  [
    Branch (CVal (PData "()" [])) (
      deco "{ c = []; len = 0; }" (
        ERecord [
          Fexpr "c" (deco "[]" (EData "[]" []));
          Fexpr "len" (deco "0" (EInt 0))
        ]
      )
    )
  ].

Definition __fun1 := AnonFunction __branches0.

Definition __exp2 := EUnsupported.

Definition __fun3 :=
  AnonFun "s" (
    deco "s.c <- []; s.len <- 0" (
      ESeq (deco "s.c <- []" EUnsupported) (deco "s.len <- 0" __exp2)
    )
  ).

Definition __fun4 :=
  AnonFun "s" (
    deco "{ c = s.c; len = s.len; }" (
      ERecord [
        Fexpr "c" (deco "s.c" (ERecordAccess (deco "s" (EPath [ "s" ])) "c"));
        Fexpr "len" (
          deco "s.len" (ERecordAccess (deco "s" (EPath [ "s" ])) "len")
        )
      ]
    )
  ).

Definition __exp5 := EUnsupported.

Definition __fun6 :=
  AnonFun "s" (
    deco "s.c <- x :: s.c...en <- s.len + 1" (
      ESeq (deco "s.c <- x :: s.c" EUnsupported) (
        deco "s.len <- s.len + 1" __exp5
      )
    )
  ).

Definition __fun7 := AnonFun "x" (EAnonFun __fun6).

Definition __exp8 := EPath [ "hd" ].

Definition __exp9 :=
  ESeq (deco "s.len <- s.len - 1" EUnsupported) (deco "hd" __exp8).

Definition __branches10 :=
  [
    Branch (CVal (PData "::" [ PVar "hd"; PVar "tl" ])) (
      deco "s.c <- tl; s.len <- s.len - 1; hd" (
        ESeq (deco "s.c <- tl" EUnsupported) (
          deco "s.len <- s.len - 1; hd" __exp9
        )
      )
    );
    Branch (CVal (PData "[]" [])) (
      deco "raise Empty" (ERaise (deco "Empty" (EXData [ "Empty" ] [])))
    )
  ].

Definition __fun11 :=
  AnonFun "s" (
    deco "match s.c with ... -> raise Empty" (
      EMatch (deco "s.c" (ERecordAccess (deco "s" (EPath [ "s" ])) "c")) __branches10
    )
  ).

Definition __exp12 := EData "Some" [ deco "hd" (EPath [ "hd" ]) ].

Definition __exp13 :=
  ESeq (deco "s.len <- s.len - 1" EUnsupported) (deco "Some hd" __exp12).

Definition __branches14 :=
  [
    Branch (CVal (PData "::" [ PVar "hd"; PVar "tl" ])) (
      deco "s.c <- tl; s.le...en - 1; Some hd" (
        ESeq (deco "s.c <- tl" EUnsupported) (
          deco "s.len <- s.len - 1; Some hd" __exp13
        )
      )
    );
    Branch (CVal (PData "[]" [])) (deco "None" (EData "None" []))
  ].

Definition __fun15 :=
  AnonFun "s" (
    deco "match s.c with ...hd | [] -> None" (
      EMatch (deco "s.c" (ERecordAccess (deco "s" (EPath [ "s" ])) "c")) __branches14
    )
  ).

Definition __exp16 := EUnsupported.

Definition __branches17 :=
  [
    Branch (CVal (PData "::" [ PVar "_hd"; PVar "tl" ])) (
      deco "s.c <- tl; s.len <- s.len - 1" (
        ESeq (deco "s.c <- tl" EUnsupported) (deco "s.len <- s.len - 1" __exp16)
      )
    );
    Branch (CVal (PData "[]" [])) (
      deco "raise Empty" (ERaise (deco "Empty" (EXData [ "Empty" ] [])))
    )
  ].

Definition __fun18 :=
  AnonFun "s" (
    deco "match s.c with ... -> raise Empty" (
      EMatch (deco "s.c" (ERecordAccess (deco "s" (EPath [ "s" ])) "c")) __branches17
    )
  ).

Definition __branches19 :=
  [
    Branch (CVal (PData "::" [ PVar "hd"; PAny ])) (deco "hd" (EPath [ "hd" ]));
    Branch (CVal (PData "[]" [])) (
      deco "raise Empty" (ERaise (deco "Empty" (EXData [ "Empty" ] [])))
    )
  ].

Definition __fun20 :=
  AnonFun "s" (
    deco "match s.c with ... -> raise Empty" (
      EMatch (deco "s.c" (ERecordAccess (deco "s" (EPath [ "s" ])) "c")) __branches19
    )
  ).

Definition __branches21 :=
  [
    Branch (CVal (PData "::" [ PVar "hd"; PAny ])) (
      deco "Some hd" (EData "Some" [ deco "hd" (EPath [ "hd" ]) ])
    );
    Branch (CVal (PData "[]" [])) (deco "None" (EData "None" []))
  ].

Definition __fun22 :=
  AnonFun "s" (
    deco "match s.c with ...hd | [] -> None" (
      EMatch (deco "s.c" (ERecordAccess (deco "s" (EPath [ "s" ])) "c")) __branches21
    )
  ).

Definition __fun23 :=
  AnonFun "s" (
    deco "(s.c = [])" (
      EOpEq (deco "s.c" (ERecordAccess (deco "s" (EPath [ "s" ])) "c")) (
        deco "[]" (EData "[]" [])
      )
    )
  ).

Definition __fun24 :=
  AnonFun "s" (deco "s.len" (ERecordAccess (deco "s" (EPath [ "s" ])) "len")).

Definition __fun25 :=
  AnonFun "s" (
    deco "List.iter f s.c" (
      EApp (
        EApp (deco "List.iter" (EPath [ "List"; "iter" ])) (
          deco "f" (EPath [ "f" ])
        )
      ) (deco "s.c" (ERecordAccess (deco "s" (EPath [ "s" ])) "c"))
    )
  ).

Definition __fun26 := AnonFun "f" (EAnonFun __fun25).

Definition __fun27 :=
  AnonFun "s" (
    deco "List.fold_left f acc s.c" (
      EApp (
        EApp (
          EApp (deco "List.fold_left" (EPath [ "List"; "fold_left" ])) (
            deco "f" (EPath [ "f" ])
          )
        ) (deco "acc" (EPath [ "acc" ]))
      ) (deco "s.c" (ERecordAccess (deco "s" (EPath [ "s" ])) "c"))
    )
  ).

Definition __fun28 := AnonFun "acc" (EAnonFun __fun27).

Definition __fun29 := AnonFun "f" (EAnonFun __fun28).

Definition __fun30 :=
  AnonFun "s" (
    deco "List.to_seq s.c" (
      EApp (deco "List.to_seq" (EPath [ "List"; "to_seq" ])) (
        deco "s.c" (ERecordAccess (deco "s" (EPath [ "s" ])) "c")
      )
    )
  ).

Definition __fun31 :=
  AnonFun "x" (
    deco "push x q" (
      EApp (EApp (deco "push" (EPath [ "push" ])) (deco "x" (EPath [ "x" ]))) (
        deco "q" (EPath [ "q" ])
      )
    )
  ).

Definition __fun32 :=
  AnonFun "i" (
    deco "Seq.iter (fun x -> push x q) i" (
      EApp (
        EApp (deco "Seq.iter" (EPath [ "Seq"; "iter" ])) (
          deco "(fun x -> push x q)" (EAnonFun __fun31)
        )
      ) (deco "i" (EPath [ "i" ]))
    )
  ).

Definition __fun33 := AnonFun "q" (EAnonFun __fun32).

Definition __exp34 := EPath [ "s" ].

Definition __exp35 :=
  ESeq (
    deco "add_seq s g" (
      EApp (
        EApp (deco "add_seq" (EPath [ "add_seq" ])) (deco "s" (EPath [ "s" ]))
      ) (deco "g" (EPath [ "g" ]))
    )
  ) (deco "s" __exp34).

Definition __fun36 :=
  AnonFun "g" (
    deco "let s = create(... add_seq s g; s" (
      ELet [
        Binding (PVar "s") (
          deco "create()" (
            EApp (deco "create" (EPath [ "create" ])) (
              deco "()" (EData "()" [])
            )
          )
        )
      ] (deco "add_seq s g; s" __exp35)
    )
  ).

Definition __main :=
  MStruct [
    IExtend [
      "Empty"
    ];
    ILet [
      Binding (PVar "create") (
        deco "() = { c = []; len = 0; }" (EAnonFun __fun1)
      )
    ];
    ILet [
      Binding (PVar "clear") (
        deco "s = s.c <- []; s.len <- 0" (EAnonFun __fun3)
      )
    ];
    ILet [
      Binding (PVar "copy") (
        deco "s = { c = s.c; len = s.len; }" (EAnonFun __fun4)
      )
    ];
    ILet [
      Binding (PVar "push") (
        deco "x s = s.c <- x ...en <- s.len + 1" (EAnonFun __fun7)
      )
    ];
    ILet [
      Binding (PVar "pop") (
        deco "s = match s.c w... -> raise Empty" (EAnonFun __fun11)
      )
    ];
    ILet [
      Binding (PVar "pop_opt") (
        deco "s = match s.c w...hd | [] -> None" (EAnonFun __fun15)
      )
    ];
    ILet [
      Binding (PVar "drop") (
        deco "s = match s.c w... -> raise Empty" (EAnonFun __fun18)
      )
    ];
    ILet [
      Binding (PVar "top") (
        deco "s = match s.c w... -> raise Empty" (EAnonFun __fun20)
      )
    ];
    ILet [
      Binding (PVar "top_opt") (
        deco "s = match s.c w...hd | [] -> None" (EAnonFun __fun22)
      )
    ];
    ILet [
      Binding (PVar "is_empty") (deco "s = (s.c = [])" (EAnonFun __fun23))
    ];
    ILet [
      Binding (PVar "length") (deco "s = s.len" (EAnonFun __fun24))
    ];
    ILet [
      Binding (PVar "iter") (deco "f s = List.iter f s.c" (EAnonFun __fun26))
    ];
    ILet [
      Binding (PVar "fold") (
        deco "f acc s = List...._left f acc s.c" (EAnonFun __fun29)
      )
    ];
    ILet [
      Binding (PVar "to_seq") (deco "s = List.to_seq s.c" (EAnonFun __fun30))
    ];
    ILet [
      Binding (PVar "add_seq") (
        deco "q i = Seq.iter ... -> push x q) i" (EAnonFun __fun33)
      )
    ];
    ILet [
      Binding (PVar "of_seq") (
        deco "g = let s = cre... add_seq s g; s" (EAnonFun __fun36)
      )
    ]
  ].

