(* This file has been generated by Osiris. Do not edit. *)

From osiris Require Import osiris.

Definition __branches0 :=
  [
    Branch (CVal (PData "()" [])) (deco "Nil" (EData "Nil" []))
  ].

Definition __fun1 := AnonFunction __branches0.

Definition __branches2 :=
  [
    Branch (CVal (PData "()" [])) (
      deco "Cons (x, empty)" (
        EData "Cons" [
          deco "x" (EPath [ "x" ]);
          deco "empty" (EPath [ "empty" ])
        ]
      )
    )
  ].

Definition __fun3 := AnonFunction __branches2.

Definition __fun4 := AnonFun "x" (EAnonFun __fun3).

Definition __branches5 :=
  [
    Branch (CVal (PData "()" [])) (
      deco "Cons (x, next)" (
        EData "Cons" [
          deco "x" (EPath [ "x" ]);
          deco "next" (EPath [ "next" ])
        ]
      )
    )
  ].

Definition __fun6 := AnonFunction __branches5.

Definition __fun7 := AnonFun "next" (EAnonFun __fun6).

Definition __fun8 := AnonFun "x" (EAnonFun __fun7).

Definition __branches9 :=
  [
    Branch (CVal (PData "Nil" [])) (
      deco "seq2()" (
        EApp (deco "seq2" (EPath [ "seq2" ])) (deco "()" (EData "()" []))
      )
    );
    Branch (CVal (PData "Cons" [ PVar "x"; PVar "next" ])) (
      deco "Cons (x, append next seq2)" (
        EData "Cons" [
          deco "x" (EPath [ "x" ]);
          deco "append next seq2" (
            EApp (
              EApp (deco "append" (EPath [ "append" ])) (
                deco "next" (EPath [ "next" ])
              )
            ) (deco "seq2" (EPath [ "seq2" ]))
          )
        ]
      )
    )
  ].

Definition __branches10 :=
  [
    Branch (CVal (PData "()" [])) (
      deco "match seq1() wi...pend next seq2)" (
        EMatch (
          deco "seq1()" (
            EApp (deco "seq1" (EPath [ "seq1" ])) (deco "()" (EData "()" []))
          )
        ) __branches9
      )
    )
  ].

Definition __fun11 := AnonFunction __branches10.

Definition __fun12 := AnonFun "seq2" (EAnonFun __fun11).

Definition __bindings13 :=
  [
    RecBinding "append" (AnonFun "seq1" (EAnonFun __fun12))
  ].

Definition __branches14 :=
  [
    Branch (CVal (PData "Nil" [])) (deco "Nil" (EData "Nil" []));
    Branch (CVal (PData "Cons" [ PVar "x"; PVar "next" ])) (
      deco "Cons (f x, map f next)" (
        EData "Cons" [
          deco "f x" (
            EApp (deco "f" (EPath [ "f" ])) (deco "x" (EPath [ "x" ]))
          );
          deco "map f next" (
            EApp (
              EApp (deco "map" (EPath [ "map" ])) (deco "f" (EPath [ "f" ]))
            ) (deco "next" (EPath [ "next" ]))
          )
        ]
      )
    )
  ].

Definition __branches15 :=
  [
    Branch (CVal (PData "()" [])) (
      deco "match seq() wit... x, map f next)" (
        EMatch (
          deco "seq()" (
            EApp (deco "seq" (EPath [ "seq" ])) (deco "()" (EData "()" []))
          )
        ) __branches14
      )
    )
  ].

Definition __fun16 := AnonFunction __branches15.

Definition __fun17 := AnonFun "seq" (EAnonFun __fun16).

Definition __bindings18 :=
  [
    RecBinding "map" (AnonFun "f" (EAnonFun __fun17))
  ].

Definition __branches19 :=
  [
    Branch (CVal (PData "None" [])) (
      deco "filter_map f next ()" (
        EApp (
          EApp (
            EApp (deco "filter_map" (EPath [ "filter_map" ])) (
              deco "f" (EPath [ "f" ])
            )
          ) (deco "next" (EPath [ "next" ]))
        ) (deco "()" (EData "()" []))
      )
    );
    Branch (CVal (PData "Some" [ PVar "y" ])) (
      deco "Cons (y, filter_map f next)" (
        EData "Cons" [
          deco "y" (EPath [ "y" ]);
          deco "filter_map f next" (
            EApp (
              EApp (deco "filter_map" (EPath [ "filter_map" ])) (
                deco "f" (EPath [ "f" ])
              )
            ) (deco "next" (EPath [ "next" ]))
          )
        ]
      )
    )
  ].

Definition __branches20 :=
  [
    Branch (CVal (PData "Nil" [])) (deco "Nil" (EData "Nil" []));
    Branch (CVal (PData "Cons" [ PVar "x"; PVar "next" ])) (
      deco "match f x with ...ter_map f next)" (
        EMatch (
          deco "f x" (
            EApp (deco "f" (EPath [ "f" ])) (deco "x" (EPath [ "x" ]))
          )
        ) __branches19
      )
    )
  ].

Definition __branches21 :=
  [
    Branch (CVal (PData "()" [])) (
      deco "match seq() wit...ter_map f next)" (
        EMatch (
          deco "seq()" (
            EApp (deco "seq" (EPath [ "seq" ])) (deco "()" (EData "()" []))
          )
        ) __branches20
      )
    )
  ].

Definition __fun22 := AnonFunction __branches21.

Definition __fun23 := AnonFun "seq" (EAnonFun __fun22).

Definition __bindings24 :=
  [
    RecBinding "filter_map" (AnonFun "f" (EAnonFun __fun23))
  ].

Definition __exp25 :=
  EData "Cons" [
    deco "x" (EPath [ "x" ]);
    deco "filter f next" (
      EApp (
        EApp (deco "filter" (EPath [ "filter" ])) (deco "f" (EPath [ "f" ]))
      ) (deco "next" (EPath [ "next" ]))
    )
  ].

Definition __exp26 :=
  EApp (
    EApp (EApp (deco "filter" (EPath [ "filter" ])) (deco "f" (EPath [ "f" ]))) (
      deco "next" (EPath [ "next" ])
    )
  ) (deco "()" (EData "()" [])).

Definition __branches27 :=
  [
    Branch (CVal (PData "Nil" [])) (deco "Nil" (EData "Nil" []));
    Branch (CVal (PData "Cons" [ PVar "x"; PVar "next" ])) (
      deco "if f x then Con...ilter f next ()" (
        EIfThenElse (
          deco "f x" (
            EApp (deco "f" (EPath [ "f" ])) (deco "x" (EPath [ "x" ]))
          )
        ) (deco "Cons (x, filter f next)" __exp25) (
          deco "filter f next ()" __exp26
        )
      )
    )
  ].

Definition __branches28 :=
  [
    Branch (CVal (PData "()" [])) (
      deco "match seq() wit...ilter f next ()" (
        EMatch (
          deco "seq()" (
            EApp (deco "seq" (EPath [ "seq" ])) (deco "()" (EData "()" []))
          )
        ) __branches27
      )
    )
  ].

Definition __fun29 := AnonFunction __branches28.

Definition __fun30 := AnonFun "seq" (EAnonFun __fun29).

Definition __bindings31 :=
  [
    RecBinding "filter" (AnonFun "f" (EAnonFun __fun30))
  ].

Definition __branches32 :=
  [
    Branch (CVal (PData "Nil" [])) (deco "Nil" (EData "Nil" []));
    Branch (CVal (PData "Cons" [ PVar "x"; PVar "next" ])) (
      deco "append x (concat next) ()" (
        EApp (
          EApp (
            EApp (deco "append" (EPath [ "append" ])) (deco "x" (EPath [ "x" ]))
          ) (
            deco "(concat next)" (
              EApp (deco "concat" (EPath [ "concat" ])) (
                deco "next" (EPath [ "next" ])
              )
            )
          )
        ) (deco "()" (EData "()" []))
      )
    )
  ].

Definition __branches33 :=
  [
    Branch (CVal (PData "()" [])) (
      deco "match seq () wi...concat next) ()" (
        EMatch (
          deco "seq ()" (
            EApp (deco "seq" (EPath [ "seq" ])) (deco "()" (EData "()" []))
          )
        ) __branches32
      )
    )
  ].

Definition __fun34 := AnonFunction __branches33.

Definition __bindings35 :=
  [
    RecBinding "concat" (AnonFun "seq" (EAnonFun __fun34))
  ].

Definition __branches36 :=
  [
    Branch (CVal (PData "Nil" [])) (deco "Nil" (EData "Nil" []));
    Branch (CVal (PData "Cons" [ PVar "x"; PVar "next" ])) (
      deco "append (f x) (flat_map f next) ()" (
        EApp (
          EApp (
            EApp (deco "append" (EPath [ "append" ])) (
              deco "(f x)" (
                EApp (deco "f" (EPath [ "f" ])) (deco "x" (EPath [ "x" ]))
              )
            )
          ) (
            deco "(flat_map f next)" (
              EApp (
                EApp (deco "flat_map" (EPath [ "flat_map" ])) (
                  deco "f" (EPath [ "f" ])
                )
              ) (deco "next" (EPath [ "next" ]))
            )
          )
        ) (deco "()" (EData "()" []))
      )
    )
  ].

Definition __branches37 :=
  [
    Branch (CVal (PData "()" [])) (
      deco "match seq () wi..._map f next) ()" (
        EMatch (
          deco "seq ()" (
            EApp (deco "seq" (EPath [ "seq" ])) (deco "()" (EData "()" []))
          )
        ) __branches36
      )
    )
  ].

Definition __fun38 := AnonFunction __branches37.

Definition __fun39 := AnonFun "seq" (EAnonFun __fun38).

Definition __bindings40 :=
  [
    RecBinding "flat_map" (AnonFun "f" (EAnonFun __fun39))
  ].

Definition __exp41 :=
  EApp (
    EApp (
      EApp (deco "fold_left" (EPath [ "fold_left" ])) (deco "f" (EPath [ "f" ]))
    ) (deco "acc" (EPath [ "acc" ]))
  ) (deco "next" (EPath [ "next" ])).

Definition __branches42 :=
  [
    Branch (CVal (PData "Nil" [])) (deco "acc" (EPath [ "acc" ]));
    Branch (CVal (PData "Cons" [ PVar "x"; PVar "next" ])) (
      deco "let acc = f acc...left f acc next" (
        ELet [
          Binding (PVar "acc") (
            deco "f acc x" (
              EApp (
                EApp (deco "f" (EPath [ "f" ])) (deco "acc" (EPath [ "acc" ]))
              ) (deco "x" (EPath [ "x" ]))
            )
          )
        ] (deco "fold_left f acc next" __exp41)
      )
    )
  ].

Definition __fun43 :=
  AnonFun "seq" (
    deco "match seq () wi...left f acc next" (
      EMatch (
        deco "seq ()" (
          EApp (deco "seq" (EPath [ "seq" ])) (deco "()" (EData "()" []))
        )
      ) __branches42
    )
  ).

Definition __fun44 := AnonFun "acc" (EAnonFun __fun43).

Definition __bindings45 :=
  [
    RecBinding "fold_left" (AnonFun "f" (EAnonFun __fun44))
  ].

Definition __exp46 :=
  EApp (EApp (deco "iter" (EPath [ "iter" ])) (deco "f" (EPath [ "f" ]))) (
    deco "next" (EPath [ "next" ])
  ).

Definition __branches47 :=
  [
    Branch (CVal (PData "Nil" [])) (deco "()" (EData "()" []));
    Branch (CVal (PData "Cons" [ PVar "x"; PVar "next" ])) (
      deco "f x; iter f next" (
        ESeq (
          deco "f x" (
            EApp (deco "f" (EPath [ "f" ])) (deco "x" (EPath [ "x" ]))
          )
        ) (deco "iter f next" __exp46)
      )
    )
  ].

Definition __fun48 :=
  AnonFun "seq" (
    deco "match seq () wi... x; iter f next" (
      EMatch (
        deco "seq ()" (
          EApp (deco "seq" (EPath [ "seq" ])) (deco "()" (EData "()" []))
        )
      ) __branches47
    )
  ).

Definition __bindings49 :=
  [
    RecBinding "iter" (AnonFun "f" (EAnonFun __fun48))
  ].

Definition __branches50 :=
  [
    Branch (CVal (PData "None" [])) (deco "Nil" (EData "Nil" []));
    Branch (CVal (PData "Some" [ PTuple [ PVar "x"; PVar "u'" ] ])) (
      deco "Cons (x, unfold f u')" (
        EData "Cons" [
          deco "x" (EPath [ "x" ]);
          deco "unfold f u'" (
            EApp (
              EApp (deco "unfold" (EPath [ "unfold" ])) (
                deco "f" (EPath [ "f" ])
              )
            ) (deco "u'" (EPath [ "u'" ]))
          )
        ]
      )
    )
  ].

Definition __branches51 :=
  [
    Branch (CVal (PData "()" [])) (
      deco "match f u with ...x, unfold f u')" (
        EMatch (
          deco "f u" (
            EApp (deco "f" (EPath [ "f" ])) (deco "u" (EPath [ "u" ]))
          )
        ) __branches50
      )
    )
  ].

Definition __fun52 := AnonFunction __branches51.

Definition __fun53 := AnonFun "u" (EAnonFun __fun52).

Definition __bindings54 :=
  [
    RecBinding "unfold" (AnonFun "f" (EAnonFun __fun53))
  ].

Definition __branches55 :=
  [
    Branch (CVal (PData "Nil" [])) (deco "true" (EData "true" []));
    Branch (CVal (PData "Cons" [ PAny; PAny ])) (
      deco "false" (EData "false" [])
    )
  ].

Definition __fun56 :=
  AnonFun "xs" (
    deco "match xs() with...(_, _) -> false" (
      EMatch (
        deco "xs()" (
          EApp (deco "xs" (EPath [ "xs" ])) (deco "()" (EData "()" []))
        )
      ) __branches55
    )
  ).

Definition __branches57 :=
  [
    Branch (CVal (PData "Cons" [ PVar "x"; PVar "xs" ])) (
      deco "Some (x, xs)" (
        EData "Some" [
          deco "(x, xs)" (
            ETuple [
              deco "x" (EPath [ "x" ]);
              deco "xs" (EPath [ "xs" ])
            ]
          )
        ]
      )
    );
    Branch (CVal (PData "Nil" [])) (deco "None" (EData "None" []))
  ].

Definition __fun58 :=
  AnonFun "xs" (
    deco "match xs() with...) | Nil -> None" (
      EMatch (
        deco "xs()" (
          EApp (deco "xs" (EPath [ "xs" ])) (deco "()" (EData "()" []))
        )
      ) __branches57
    )
  ).

Definition __branches59 :=
  [
    Branch (CVal (PData "Nil" [])) (deco "accu" (EPath [ "accu" ]));
    Branch (CVal (PData "Cons" [ PAny; PVar "xs" ])) (
      deco "length_aux (accu + 1) xs" (
        EApp (
          EApp (deco "length_aux" (EPath [ "length_aux" ])) (
            deco "(accu + 1)" (
              EIntAdd (deco "accu" (EPath [ "accu" ])) (deco "1" (EInt 1))
            )
          )
        ) (deco "xs" (EPath [ "xs" ]))
      )
    )
  ].

Definition __fun60 :=
  AnonFun "xs" (
    deco "match xs() with...x (accu + 1) xs" (
      EMatch (
        deco "xs()" (
          EApp (deco "xs" (EPath [ "xs" ])) (deco "()" (EData "()" []))
        )
      ) __branches59
    )
  ).

Definition __bindings61 :=
  [
    RecBinding "length_aux" (AnonFun "accu" (EAnonFun __fun60))
  ].

Definition __fun62 :=
  AnonFun "xs" (
    deco "length_aux 0 xs" (
      EApp (
        EApp (deco "length_aux" (EPath [ "length_aux" ])) (deco "0" (EInt 0))
      ) (deco "xs" (EPath [ "xs" ]))
    )
  ).

Definition __exp63 :=
  EApp (
    EApp (
      EApp (deco "iteri_aux" (EPath [ "iteri_aux" ])) (deco "f" (EPath [ "f" ]))
    ) (deco "(i+1)" (EIntAdd (deco "i" (EPath [ "i" ])) (deco "1" (EInt 1))))
  ) (deco "xs" (EPath [ "xs" ])).

Definition __branches64 :=
  [
    Branch (CVal (PData "Nil" [])) (deco "()" (EData "()" []));
    Branch (CVal (PData "Cons" [ PVar "x"; PVar "xs" ])) (
      deco "f i x; iteri_aux f (i+1) xs" (
        ESeq (
          deco "f i x" (
            EApp (EApp (deco "f" (EPath [ "f" ])) (deco "i" (EPath [ "i" ]))) (
              deco "x" (EPath [ "x" ])
            )
          )
        ) (deco "iteri_aux f (i+1) xs" __exp63)
      )
    )
  ].

Definition __fun65 :=
  AnonFun "xs" (
    deco "match xs() with..._aux f (i+1) xs" (
      EMatch (
        deco "xs()" (
          EApp (deco "xs" (EPath [ "xs" ])) (deco "()" (EData "()" []))
        )
      ) __branches64
    )
  ).

Definition __fun66 := AnonFun "i" (EAnonFun __fun65).

Definition __bindings67 :=
  [
    RecBinding "iteri_aux" (AnonFun "f" (EAnonFun __fun66))
  ].

Definition __fun68 :=
  AnonFun "xs" (
    deco "iteri_aux f 0 xs" (
      EApp (
        EApp (
          EApp (deco "iteri_aux" (EPath [ "iteri_aux" ])) (
            deco "f" (EPath [ "f" ])
          )
        ) (deco "0" (EInt 0))
      ) (deco "xs" (EPath [ "xs" ]))
    )
  ).

Definition __fun69 := AnonFun "f" (EAnonFun __fun68).

Definition __exp70 :=
  EApp (
    EApp (
      EApp (
        EApp (deco "fold_lefti_aux" (EPath [ "fold_lefti_aux" ])) (
          deco "f" (EPath [ "f" ])
        )
      ) (deco "accu" (EPath [ "accu" ]))
    ) (deco "(i+1)" (EIntAdd (deco "i" (EPath [ "i" ])) (deco "1" (EInt 1))))
  ) (deco "xs" (EPath [ "xs" ])).

Definition __branches71 :=
  [
    Branch (CVal (PData "Nil" [])) (deco "accu" (EPath [ "accu" ]));
    Branch (CVal (PData "Cons" [ PVar "x"; PVar "xs" ])) (
      deco "let accu = f ac...f accu (i+1) xs" (
        ELet [
          Binding (PVar "accu") (
            deco "f accu i x" (
              EApp (
                EApp (
                  EApp (deco "f" (EPath [ "f" ])) (
                    deco "accu" (EPath [ "accu" ])
                  )
                ) (deco "i" (EPath [ "i" ]))
              ) (deco "x" (EPath [ "x" ]))
            )
          )
        ] (deco "fold_lefti_aux f accu (i+1) xs" __exp70)
      )
    )
  ].

Definition __fun72 :=
  AnonFun "xs" (
    deco "match xs() with...f accu (i+1) xs" (
      EMatch (
        deco "xs()" (
          EApp (deco "xs" (EPath [ "xs" ])) (deco "()" (EData "()" []))
        )
      ) __branches71
    )
  ).

Definition __fun73 := AnonFun "i" (EAnonFun __fun72).

Definition __fun74 := AnonFun "accu" (EAnonFun __fun73).

Definition __bindings75 :=
  [
    RecBinding "fold_lefti_aux" (AnonFun "f" (EAnonFun __fun74))
  ].

Definition __fun76 :=
  AnonFun "xs" (
    deco "fold_lefti_aux f accu 0 xs" (
      EApp (
        EApp (
          EApp (
            EApp (deco "fold_lefti_aux" (EPath [ "fold_lefti_aux" ])) (
              deco "f" (EPath [ "f" ])
            )
          ) (deco "accu" (EPath [ "accu" ]))
        ) (deco "0" (EInt 0))
      ) (deco "xs" (EPath [ "xs" ]))
    )
  ).

Definition __fun77 := AnonFun "accu" (EAnonFun __fun76).

Definition __fun78 := AnonFun "f" (EAnonFun __fun77).

Definition __branches79 :=
  [
    Branch (CVal (PData "Nil" [])) (deco "true" (EData "true" []));
    Branch (CVal (PData "Cons" [ PVar "x"; PVar "xs" ])) (
      deco "p x && for_all p xs" (
        EBoolConj (
          deco "p x" (
            EApp (deco "p" (EPath [ "p" ])) (deco "x" (EPath [ "x" ]))
          )
        ) (
          deco "for_all p xs" (
            EApp (
              EApp (deco "for_all" (EPath [ "for_all" ])) (
                deco "p" (EPath [ "p" ])
              )
            ) (deco "xs" (EPath [ "xs" ]))
          )
        )
      )
    )
  ].

Definition __fun80 :=
  AnonFun "xs" (
    deco "match xs() with...&& for_all p xs" (
      EMatch (
        deco "xs()" (
          EApp (deco "xs" (EPath [ "xs" ])) (deco "()" (EData "()" []))
        )
      ) __branches79
    )
  ).

Definition __bindings81 :=
  [
    RecBinding "for_all" (AnonFun "p" (EAnonFun __fun80))
  ].

Definition __branches82 :=
  [
    Branch (CVal (PData "Nil" [])) (deco "false" (EData "false" []));
    Branch (CVal (PData "Cons" [ PVar "x"; PVar "xs" ])) (
      deco "p x || exists p xs" (
        EBoolDisj (
          deco "p x" (
            EApp (deco "p" (EPath [ "p" ])) (deco "x" (EPath [ "x" ]))
          )
        ) (
          deco "exists p xs" (
            EApp (
              EApp (deco "exists" (EPath [ "exists" ])) (
                deco "p" (EPath [ "p" ])
              )
            ) (deco "xs" (EPath [ "xs" ]))
          )
        )
      )
    )
  ].

Definition __fun83 :=
  AnonFun "xs" (
    deco "match xs() with... || exists p xs" (
      EMatch (
        deco "xs()" (
          EApp (deco "xs" (EPath [ "xs" ])) (deco "()" (EData "()" []))
        )
      ) __branches82
    )
  ).

Definition __bindings84 :=
  [
    RecBinding "exists" (AnonFun "p" (EAnonFun __fun83))
  ].

Definition __exp85 := EData "Some" [ deco "x" (EPath [ "x" ]) ].

Definition __exp86 :=
  EApp (EApp (deco "find" (EPath [ "find" ])) (deco "p" (EPath [ "p" ]))) (
    deco "xs" (EPath [ "xs" ])
  ).

Definition __branches87 :=
  [
    Branch (CVal (PData "Nil" [])) (deco "None" (EData "None" []));
    Branch (CVal (PData "Cons" [ PVar "x"; PVar "xs" ])) (
      deco "if p x then Some x else find p xs" (
        EIfThenElse (
          deco "p x" (
            EApp (deco "p" (EPath [ "p" ])) (deco "x" (EPath [ "x" ]))
          )
        ) (deco "Some x" __exp85) (deco "find p xs" __exp86)
      )
    )
  ].

Definition __fun88 :=
  AnonFun "xs" (
    deco "match xs() with... else find p xs" (
      EMatch (
        deco "xs()" (
          EApp (deco "xs" (EPath [ "xs" ])) (deco "()" (EData "()" []))
        )
      ) __branches87
    )
  ).

Definition __bindings89 :=
  [
    RecBinding "find" (AnonFun "p" (EAnonFun __fun88))
  ].

Definition __exp90 := EData "Some" [ deco "i" (EPath [ "i" ]) ].

Definition __exp91 :=
  EApp (
    EApp (deco "aux" (EPath [ "aux" ])) (
      deco "(i+1)" (EIntAdd (deco "i" (EPath [ "i" ])) (deco "1" (EInt 1)))
    )
  ) (deco "xs" (EPath [ "xs" ])).

Definition __branches92 :=
  [
    Branch (CVal (PData "Nil" [])) (deco "None" (EData "None" []));
    Branch (CVal (PData "Cons" [ PVar "x"; PVar "xs" ])) (
      deco "if p x then Som...se aux (i+1) xs" (
        EIfThenElse (
          deco "p x" (
            EApp (deco "p" (EPath [ "p" ])) (deco "x" (EPath [ "x" ]))
          )
        ) (deco "Some i" __exp90) (deco "aux (i+1) xs" __exp91)
      )
    )
  ].

Definition __fun93 :=
  AnonFun "xs" (
    deco "match xs() with...se aux (i+1) xs" (
      EMatch (
        deco "xs()" (
          EApp (deco "xs" (EPath [ "xs" ])) (deco "()" (EData "()" []))
        )
      ) __branches92
    )
  ).

Definition __bindings94 :=
  [
    RecBinding "aux" (AnonFun "i" (EAnonFun __fun93))
  ].

Definition __exp95 :=
  EApp (EApp (deco "aux" (EPath [ "aux" ])) (deco "0" (EInt 0))) (
    deco "xs" (EPath [ "xs" ])
  ).

Definition __fun96 :=
  AnonFun "xs" (
    deco "let rec aux i x... xs in aux 0 xs" (
      ELetRec __bindings94 (deco "aux 0 xs" __exp95)
    )
  ).

Definition __fun97 := AnonFun "p" (EAnonFun __fun96).

Definition __branches98 :=
  [
    Branch (CVal (PData "None" [])) (
      deco "find_map f xs" (
        EApp (
          EApp (deco "find_map" (EPath [ "find_map" ])) (
            deco "f" (EPath [ "f" ])
          )
        ) (deco "xs" (EPath [ "xs" ]))
      )
    );
    Branch (CVal (PAlias (PData "Some" [ PAny ]) "result")) (
      deco "result" (EPath [ "result" ])
    )
  ].

Definition __branches99 :=
  [
    Branch (CVal (PData "Nil" [])) (deco "None" (EData "None" []));
    Branch (CVal (PData "Cons" [ PVar "x"; PVar "xs" ])) (
      deco "match f x with ...esult -> result" (
        EMatch (
          deco "f x" (
            EApp (deco "f" (EPath [ "f" ])) (deco "x" (EPath [ "x" ]))
          )
        ) __branches98
      )
    )
  ].

Definition __fun100 :=
  AnonFun "xs" (
    deco "match xs() with...esult -> result" (
      EMatch (
        deco "xs()" (
          EApp (deco "xs" (EPath [ "xs" ])) (deco "()" (EData "()" []))
        )
      ) __branches99
    )
  ).

Definition __bindings101 :=
  [
    RecBinding "find_map" (AnonFun "f" (EAnonFun __fun100))
  ].

Definition __branches102 :=
  [
    Branch (CVal (PData "None" [])) (
      deco "aux (i+1) xs" (
        EApp (
          EApp (deco "aux" (EPath [ "aux" ])) (
            deco "(i+1)" (
              EIntAdd (deco "i" (EPath [ "i" ])) (deco "1" (EInt 1))
            )
          )
        ) (deco "xs" (EPath [ "xs" ]))
      )
    );
    Branch (CVal (PAlias (PData "Some" [ PAny ]) "result")) (
      deco "result" (EPath [ "result" ])
    )
  ].

Definition __branches103 :=
  [
    Branch (CVal (PData "Nil" [])) (deco "None" (EData "None" []));
    Branch (CVal (PData "Cons" [ PVar "x"; PVar "xs" ])) (
      deco "match f i x wit...esult -> result" (
        EMatch (
          deco "f i x" (
            EApp (EApp (deco "f" (EPath [ "f" ])) (deco "i" (EPath [ "i" ]))) (
              deco "x" (EPath [ "x" ])
            )
          )
        ) __branches102
      )
    )
  ].

Definition __fun104 :=
  AnonFun "xs" (
    deco "match xs() with...esult -> result" (
      EMatch (
        deco "xs()" (
          EApp (deco "xs" (EPath [ "xs" ])) (deco "()" (EData "()" []))
        )
      ) __branches103
    )
  ).

Definition __bindings105 :=
  [
    RecBinding "aux" (AnonFun "i" (EAnonFun __fun104))
  ].

Definition __exp106 :=
  EApp (EApp (deco "aux" (EPath [ "aux" ])) (deco "0" (EInt 0))) (
    deco "xs" (EPath [ "xs" ])
  ).

Definition __fun107 :=
  AnonFun "xs" (
    deco "let rec aux i x...ult in aux 0 xs" (
      ELetRec __bindings105 (deco "aux 0 xs" __exp106)
    )
  ).

Definition __fun108 := AnonFun "f" (EAnonFun __fun107).

Definition __exp109 :=
  EApp (
    EApp (EApp (deco "iter2" (EPath [ "iter2" ])) (deco "f" (EPath [ "f" ]))) (
      deco "xs" (EPath [ "xs" ])
    )
  ) (deco "ys" (EPath [ "ys" ])).

Definition __branches110 :=
  [
    Branch (CVal (PData "Nil" [])) (deco "()" (EData "()" []));
    Branch (CVal (PData "Cons" [ PVar "y"; PVar "ys" ])) (
      deco "f x y; iter2 f xs ys" (
        ESeq (
          deco "f x y" (
            EApp (EApp (deco "f" (EPath [ "f" ])) (deco "x" (EPath [ "x" ]))) (
              deco "y" (EPath [ "y" ])
            )
          )
        ) (deco "iter2 f xs ys" __exp109)
      )
    )
  ].

Definition __branches111 :=
  [
    Branch (CVal (PData "Nil" [])) (deco "()" (EData "()" []));
    Branch (CVal (PData "Cons" [ PVar "x"; PVar "xs" ])) (
      deco "match ys() with...; iter2 f xs ys" (
        EMatch (
          deco "ys()" (
            EApp (deco "ys" (EPath [ "ys" ])) (deco "()" (EData "()" []))
          )
        ) __branches110
      )
    )
  ].

Definition __fun112 :=
  AnonFun "ys" (
    deco "match xs() with...; iter2 f xs ys" (
      EMatch (
        deco "xs()" (
          EApp (deco "xs" (EPath [ "xs" ])) (deco "()" (EData "()" []))
        )
      ) __branches111
    )
  ).

Definition __fun113 := AnonFun "xs" (EAnonFun __fun112).

Definition __bindings114 :=
  [
    RecBinding "iter2" (AnonFun "f" (EAnonFun __fun113))
  ].

Definition __exp115 :=
  EApp (
    EApp (
      EApp (
        EApp (deco "fold_left2" (EPath [ "fold_left2" ])) (
          deco "f" (EPath [ "f" ])
        )
      ) (deco "accu" (EPath [ "accu" ]))
    ) (deco "xs" (EPath [ "xs" ]))
  ) (deco "ys" (EPath [ "ys" ])).

Definition __branches116 :=
  [
    Branch (CVal (PData "Nil" [])) (deco "accu" (EPath [ "accu" ]));
    Branch (CVal (PData "Cons" [ PVar "y"; PVar "ys" ])) (
      deco "let accu = f ac...t2 f accu xs ys" (
        ELet [
          Binding (PVar "accu") (
            deco "f accu x y" (
              EApp (
                EApp (
                  EApp (deco "f" (EPath [ "f" ])) (
                    deco "accu" (EPath [ "accu" ])
                  )
                ) (deco "x" (EPath [ "x" ]))
              ) (deco "y" (EPath [ "y" ]))
            )
          )
        ] (deco "fold_left2 f accu xs ys" __exp115)
      )
    )
  ].

Definition __branches117 :=
  [
    Branch (CVal (PData "Nil" [])) (deco "accu" (EPath [ "accu" ]));
    Branch (CVal (PData "Cons" [ PVar "x"; PVar "xs" ])) (
      deco "match ys() with...t2 f accu xs ys" (
        EMatch (
          deco "ys()" (
            EApp (deco "ys" (EPath [ "ys" ])) (deco "()" (EData "()" []))
          )
        ) __branches116
      )
    )
  ].

Definition __fun118 :=
  AnonFun "ys" (
    deco "match xs() with...t2 f accu xs ys" (
      EMatch (
        deco "xs()" (
          EApp (deco "xs" (EPath [ "xs" ])) (deco "()" (EData "()" []))
        )
      ) __branches117
    )
  ).

Definition __fun119 := AnonFun "xs" (EAnonFun __fun118).

Definition __fun120 := AnonFun "accu" (EAnonFun __fun119).

Definition __bindings121 :=
  [
    RecBinding "fold_left2" (AnonFun "f" (EAnonFun __fun120))
  ].

Definition __branches122 :=
  [
    Branch (CVal (PData "Nil" [])) (deco "true" (EData "true" []));
    Branch (CVal (PData "Cons" [ PVar "y"; PVar "ys" ])) (
      deco "f x y && for_all2 f xs ys" (
        EBoolConj (
          deco "f x y" (
            EApp (EApp (deco "f" (EPath [ "f" ])) (deco "x" (EPath [ "x" ]))) (
              deco "y" (EPath [ "y" ])
            )
          )
        ) (
          deco "for_all2 f xs ys" (
            EApp (
              EApp (
                EApp (deco "for_all2" (EPath [ "for_all2" ])) (
                  deco "f" (EPath [ "f" ])
                )
              ) (deco "xs" (EPath [ "xs" ]))
            ) (deco "ys" (EPath [ "ys" ]))
          )
        )
      )
    )
  ].

Definition __branches123 :=
  [
    Branch (CVal (PData "Nil" [])) (deco "true" (EData "true" []));
    Branch (CVal (PData "Cons" [ PVar "x"; PVar "xs" ])) (
      deco "match ys() with...or_all2 f xs ys" (
        EMatch (
          deco "ys()" (
            EApp (deco "ys" (EPath [ "ys" ])) (deco "()" (EData "()" []))
          )
        ) __branches122
      )
    )
  ].

Definition __fun124 :=
  AnonFun "ys" (
    deco "match xs() with...or_all2 f xs ys" (
      EMatch (
        deco "xs()" (
          EApp (deco "xs" (EPath [ "xs" ])) (deco "()" (EData "()" []))
        )
      ) __branches123
    )
  ).

Definition __fun125 := AnonFun "xs" (EAnonFun __fun124).

Definition __bindings126 :=
  [
    RecBinding "for_all2" (AnonFun "f" (EAnonFun __fun125))
  ].

Definition __branches127 :=
  [
    Branch (CVal (PData "Nil" [])) (deco "false" (EData "false" []));
    Branch (CVal (PData "Cons" [ PVar "y"; PVar "ys" ])) (
      deco "f x y || exists2 f xs ys" (
        EBoolDisj (
          deco "f x y" (
            EApp (EApp (deco "f" (EPath [ "f" ])) (deco "x" (EPath [ "x" ]))) (
              deco "y" (EPath [ "y" ])
            )
          )
        ) (
          deco "exists2 f xs ys" (
            EApp (
              EApp (
                EApp (deco "exists2" (EPath [ "exists2" ])) (
                  deco "f" (EPath [ "f" ])
                )
              ) (deco "xs" (EPath [ "xs" ]))
            ) (deco "ys" (EPath [ "ys" ]))
          )
        )
      )
    )
  ].

Definition __branches128 :=
  [
    Branch (CVal (PData "Nil" [])) (deco "false" (EData "false" []));
    Branch (CVal (PData "Cons" [ PVar "x"; PVar "xs" ])) (
      deco "match ys() with...exists2 f xs ys" (
        EMatch (
          deco "ys()" (
            EApp (deco "ys" (EPath [ "ys" ])) (deco "()" (EData "()" []))
          )
        ) __branches127
      )
    )
  ].

Definition __fun129 :=
  AnonFun "ys" (
    deco "match xs() with...exists2 f xs ys" (
      EMatch (
        deco "xs()" (
          EApp (deco "xs" (EPath [ "xs" ])) (deco "()" (EData "()" []))
        )
      ) __branches128
    )
  ).

Definition __fun130 := AnonFun "xs" (EAnonFun __fun129).

Definition __bindings131 :=
  [
    RecBinding "exists2" (AnonFun "f" (EAnonFun __fun130))
  ].

Definition __branches132 :=
  [
    Branch (CVal (PTuple [ PData "Nil" []; PData "Nil" [] ])) (
      deco "true" (EData "true" [])
    );
    Branch (
      CVal (
        PTuple [
          PData "Cons" [
            PVar "x";
            PVar "xs"
          ];
          PData "Cons" [
            PVar "y";
            PVar "ys"
          ]
        ]
      )
    ) (
      deco "eq x y && equal eq xs ys" (
        EBoolConj (
          deco "eq x y" (
            EApp (EApp (deco "eq" (EPath [ "eq" ])) (deco "x" (EPath [ "x" ]))) (
              deco "y" (EPath [ "y" ])
            )
          )
        ) (
          deco "equal eq xs ys" (
            EApp (
              EApp (
                EApp (deco "equal" (EPath [ "equal" ])) (
                  deco "eq" (EPath [ "eq" ])
                )
              ) (deco "xs" (EPath [ "xs" ]))
            ) (deco "ys" (EPath [ "ys" ]))
          )
        )
      )
    );
    Branch (
      COr (CVal (PTuple [ PData "Nil" []; PData "Cons" [ PAny; PAny ] ])) (
        CVal (PTuple [ PData "Cons" [ PAny; PAny ]; PData "Nil" [] ])
      )
    ) (deco "false" (EData "false" []))
  ].

Definition __fun133 :=
  AnonFun "ys" (
    deco "match xs(), ys(...), Nil -> false" (
      EMatch (
        deco "xs(), ys()" (
          ETuple [
            deco "xs()" (
              EApp (deco "xs" (EPath [ "xs" ])) (deco "()" (EData "()" []))
            );
            deco "ys()" (
              EApp (deco "ys" (EPath [ "ys" ])) (deco "()" (EData "()" []))
            )
          ]
        )
      ) __branches132
    )
  ).

Definition __fun134 := AnonFun "xs" (EAnonFun __fun133).

Definition __bindings135 :=
  [
    RecBinding "equal" (AnonFun "eq" (EAnonFun __fun134))
  ].

Definition __exp136 := EPath [ "c" ].

Definition __exp137 :=
  EApp (
    EApp (
      EApp (deco "compare" (EPath [ "compare" ])) (deco "cmp" (EPath [ "cmp" ]))
    ) (deco "xs" (EPath [ "xs" ]))
  ) (deco "ys" (EPath [ "ys" ])).

Definition __exp138 :=
  EIfThenElse (
    deco "c <> 0" (EOpNe (deco "c" (EPath [ "c" ])) (deco "0" (EInt 0)))
  ) (deco "c" __exp136) (deco "compare cmp xs ys" __exp137).

Definition __branches139 :=
  [
    Branch (CVal (PTuple [ PData "Nil" []; PData "Nil" [] ])) (
      deco "0" (EInt 0)
    );
    Branch (
      CVal (
        PTuple [
          PData "Cons" [
            PVar "x";
            PVar "xs"
          ];
          PData "Cons" [
            PVar "y";
            PVar "ys"
          ]
        ]
      )
    ) (
      deco "let c = cmp x y...mpare cmp xs ys" (
        ELet [
          Binding (PVar "c") (
            deco "cmp x y" (
              EApp (
                EApp (deco "cmp" (EPath [ "cmp" ])) (deco "x" (EPath [ "x" ]))
              ) (deco "y" (EPath [ "y" ]))
            )
          )
        ] (deco "if c <> 0 then ...mpare cmp xs ys" __exp138)
      )
    );
    Branch (CVal (PTuple [ PData "Nil" []; PData "Cons" [ PAny; PAny ] ])) (
      deco "-1" (EInt -1)
    );
    Branch (CVal (PTuple [ PData "Cons" [ PAny; PAny ]; PData "Nil" [] ])) (
      deco "+1" (EInt 1)
    )
  ].

Definition __fun140 :=
  AnonFun "ys" (
    deco "match xs(), ys(..., _), Nil -> +1" (
      EMatch (
        deco "xs(), ys()" (
          ETuple [
            deco "xs()" (
              EApp (deco "xs" (EPath [ "xs" ])) (deco "()" (EData "()" []))
            );
            deco "ys()" (
              EApp (deco "ys" (EPath [ "ys" ])) (deco "()" (EData "()" []))
            )
          ]
        )
      ) __branches139
    )
  ).

Definition __fun141 := AnonFun "xs" (EAnonFun __fun140).

Definition __bindings142 :=
  [
    RecBinding "compare" (AnonFun "cmp" (EAnonFun __fun141))
  ].

Definition __exp143 :=
  EData "Cons" [
    deco "f i" (EApp (deco "f" (EPath [ "f" ])) (deco "i" (EPath [ "i" ])));
    deco "init_aux f (i + 1) j" (
      EApp (
        EApp (
          EApp (deco "init_aux" (EPath [ "init_aux" ])) (
            deco "f" (EPath [ "f" ])
          )
        ) (
          deco "(i + 1)" (
            EIntAdd (deco "i" (EPath [ "i" ])) (deco "1" (EInt 1))
          )
        )
      ) (deco "j" (EPath [ "j" ]))
    )
  ].

Definition __exp144 := EData "Nil" [].

Definition __branches145 :=
  [
    Branch (CVal (PData "()" [])) (
      deco "if i < j then b...j) end else Nil" (
        EIfThenElse (
          deco "i < j" (
            EOpLt (deco "i" (EPath [ "i" ])) (deco "j" (EPath [ "j" ]))
          )
        ) (deco "begin Cons (f i... (i + 1) j) end" __exp143) (
          deco "Nil" __exp144
        )
      )
    )
  ].

Definition __fun146 := AnonFunction __branches145.

Definition __fun147 := AnonFun "j" (EAnonFun __fun146).

Definition __fun148 := AnonFun "i" (EAnonFun __fun147).

Definition __bindings149 :=
  [
    RecBinding "init_aux" (AnonFun "f" (EAnonFun __fun148))
  ].

Definition __exp150 :=
  EApp (deco "invalid_arg" (EPath [ "invalid_arg" ])) (
    deco """Seq.init""" (EString "Seq.init")
  ).

Definition __exp151 :=
  EApp (
    EApp (
      EApp (deco "init_aux" (EPath [ "init_aux" ])) (deco "f" (EPath [ "f" ]))
    ) (deco "0" (EInt 0))
  ) (deco "n" (EPath [ "n" ])).

Definition __fun152 :=
  AnonFun "f" (
    deco "if n < 0 then i... init_aux f 0 n" (
      EIfThenElse (
        deco "n < 0" (EOpLt (deco "n" (EPath [ "n" ])) (deco "0" (EInt 0)))
      ) (deco "invalid_arg ""Seq.init""" __exp150) (
        deco "init_aux f 0 n" __exp151
      )
    )
  ).

Definition __fun153 := AnonFun "n" (EAnonFun __fun152).

Definition __branches154 :=
  [
    Branch (CVal (PData "()" [])) (
      deco "Cons (x, repeat x)" (
        EData "Cons" [
          deco "x" (EPath [ "x" ]);
          deco "repeat x" (
            EApp (deco "repeat" (EPath [ "repeat" ])) (deco "x" (EPath [ "x" ]))
          )
        ]
      )
    )
  ].

Definition __fun155 := AnonFunction __branches154.

Definition __bindings156 :=
  [
    RecBinding "repeat" (AnonFun "x" (EAnonFun __fun155))
  ].

Definition __branches157 :=
  [
    Branch (CVal (PData "()" [])) (
      deco "Cons (f(), forever f)" (
        EData "Cons" [
          deco "f()" (
            EApp (deco "f" (EPath [ "f" ])) (deco "()" (EData "()" []))
          );
          deco "forever f" (
            EApp (deco "forever" (EPath [ "forever" ])) (
              deco "f" (EPath [ "f" ])
            )
          )
        ]
      )
    )
  ].

Definition __fun158 := AnonFunction __branches157.

Definition __bindings159 :=
  [
    RecBinding "forever" (AnonFun "f" (EAnonFun __fun158))
  ].

Definition __branches160 :=
  [
    Branch (CVal (PData "()" [])) (
      deco "append xs (cycle_nonempty xs) ()" (
        EApp (
          EApp (
            EApp (deco "append" (EPath [ "append" ])) (
              deco "xs" (EPath [ "xs" ])
            )
          ) (
            deco "(cycle_nonempty xs)" (
              EApp (deco "cycle_nonempty" (EPath [ "cycle_nonempty" ])) (
                deco "xs" (EPath [ "xs" ])
              )
            )
          )
        ) (deco "()" (EData "()" []))
      )
    )
  ].

Definition __fun161 := AnonFunction __branches160.

Definition __bindings162 :=
  [
    RecBinding "cycle_nonempty" (AnonFun "xs" (EAnonFun __fun161))
  ].

Definition __branches163 :=
  [
    Branch (CVal (PData "Nil" [])) (deco "Nil" (EData "Nil" []));
    Branch (CVal (PData "Cons" [ PVar "x"; PVar "xs'" ])) (
      deco "Cons (x, append...e_nonempty xs))" (
        EData "Cons" [
          deco "x" (EPath [ "x" ]);
          deco "append xs' (cycle_nonempty xs)" (
            EApp (
              EApp (deco "append" (EPath [ "append" ])) (
                deco "xs'" (EPath [ "xs'" ])
              )
            ) (
              deco "(cycle_nonempty xs)" (
                EApp (deco "cycle_nonempty" (EPath [ "cycle_nonempty" ])) (
                  deco "xs" (EPath [ "xs" ])
                )
              )
            )
          )
        ]
      )
    )
  ].

Definition __branches164 :=
  [
    Branch (CVal (PData "()" [])) (
      deco "match xs() with...e_nonempty xs))" (
        EMatch (
          deco "xs()" (
            EApp (deco "xs" (EPath [ "xs" ])) (deco "()" (EData "()" []))
          )
        ) __branches163
      )
    )
  ].

Definition __fun165 := AnonFunction __branches164.

Definition __fun166 := AnonFun "xs" (EAnonFun __fun165).

Definition __exp167 :=
  EData "Cons" [
    deco "y" (EPath [ "y" ]);
    deco "iterate1 f y" (
      EApp (
        EApp (deco "iterate1" (EPath [ "iterate1" ])) (deco "f" (EPath [ "f" ]))
      ) (deco "y" (EPath [ "y" ]))
    )
  ].

Definition __branches168 :=
  [
    Branch (CVal (PData "()" [])) (
      deco "let y = f x in ..., iterate1 f y)" (
        ELet [
          Binding (PVar "y") (
            deco "f x" (
              EApp (deco "f" (EPath [ "f" ])) (deco "x" (EPath [ "x" ]))
            )
          )
        ] (deco "Cons (y, iterate1 f y)" __exp167)
      )
    )
  ].

Definition __fun169 := AnonFunction __branches168.

Definition __fun170 := AnonFun "x" (EAnonFun __fun169).

Definition __bindings171 :=
  [
    RecBinding "iterate1" (AnonFun "f" (EAnonFun __fun170))
  ].

Definition __fun172 :=
  AnonFun "x" (
    deco "cons x (iterate1 f x)" (
      EApp (EApp (deco "cons" (EPath [ "cons" ])) (deco "x" (EPath [ "x" ]))) (
        deco "(iterate1 f x)" (
          EApp (
            EApp (deco "iterate1" (EPath [ "iterate1" ])) (
              deco "f" (EPath [ "f" ])
            )
          ) (deco "x" (EPath [ "x" ]))
        )
      )
    )
  ).

Definition __fun173 := AnonFun "f" (EAnonFun __fun172).

Definition __branches174 :=
  [
    Branch (CVal (PData "Nil" [])) (deco "Nil" (EData "Nil" []));
    Branch (CVal (PData "Cons" [ PVar "x"; PVar "xs" ])) (
      deco "Cons (f i x, mapi_aux f (i+1) xs)" (
        EData "Cons" [
          deco "f i x" (
            EApp (EApp (deco "f" (EPath [ "f" ])) (deco "i" (EPath [ "i" ]))) (
              deco "x" (EPath [ "x" ])
            )
          );
          deco "mapi_aux f (i+1) xs" (
            EApp (
              EApp (
                EApp (deco "mapi_aux" (EPath [ "mapi_aux" ])) (
                  deco "f" (EPath [ "f" ])
                )
              ) (
                deco "(i+1)" (
                  EIntAdd (deco "i" (EPath [ "i" ])) (deco "1" (EInt 1))
                )
              )
            ) (deco "xs" (EPath [ "xs" ]))
          )
        ]
      )
    )
  ].

Definition __branches175 :=
  [
    Branch (CVal (PData "()" [])) (
      deco "match xs() with...aux f (i+1) xs)" (
        EMatch (
          deco "xs()" (
            EApp (deco "xs" (EPath [ "xs" ])) (deco "()" (EData "()" []))
          )
        ) __branches174
      )
    )
  ].

Definition __fun176 := AnonFunction __branches175.

Definition __fun177 := AnonFun "xs" (EAnonFun __fun176).

Definition __fun178 := AnonFun "i" (EAnonFun __fun177).

Definition __bindings179 :=
  [
    RecBinding "mapi_aux" (AnonFun "f" (EAnonFun __fun178))
  ].

Definition __fun180 :=
  AnonFun "xs" (
    deco "mapi_aux f 0 xs" (
      EApp (
        EApp (
          EApp (deco "mapi_aux" (EPath [ "mapi_aux" ])) (
            deco "f" (EPath [ "f" ])
          )
        ) (deco "0" (EInt 0))
      ) (deco "xs" (EPath [ "xs" ]))
    )
  ).

Definition __fun181 := AnonFun "f" (EAnonFun __fun180).

Definition __exp182 :=
  EData "Cons" [
    deco "s" (EPath [ "s" ]);
    deco "tail_scan f s xs" (
      EApp (
        EApp (
          EApp (deco "tail_scan" (EPath [ "tail_scan" ])) (
            deco "f" (EPath [ "f" ])
          )
        ) (deco "s" (EPath [ "s" ]))
      ) (deco "xs" (EPath [ "xs" ]))
    )
  ].

Definition __branches183 :=
  [
    Branch (CVal (PData "Nil" [])) (deco "Nil" (EData "Nil" []));
    Branch (CVal (PData "Cons" [ PVar "x"; PVar "xs" ])) (
      deco "let s = f s x i...il_scan f s xs)" (
        ELet [
          Binding (PVar "s") (
            deco "f s x" (
              EApp (EApp (deco "f" (EPath [ "f" ])) (deco "s" (EPath [ "s" ]))) (
                deco "x" (EPath [ "x" ])
              )
            )
          )
        ] (deco "Cons (s, tail_scan f s xs)" __exp182)
      )
    )
  ].

Definition __branches184 :=
  [
    Branch (CVal (PData "()" [])) (
      deco "match xs() with...il_scan f s xs)" (
        EMatch (
          deco "xs()" (
            EApp (deco "xs" (EPath [ "xs" ])) (deco "()" (EData "()" []))
          )
        ) __branches183
      )
    )
  ].

Definition __fun185 := AnonFunction __branches184.

Definition __fun186 := AnonFun "xs" (EAnonFun __fun185).

Definition __fun187 := AnonFun "s" (EAnonFun __fun186).

Definition __bindings188 :=
  [
    RecBinding "tail_scan" (AnonFun "f" (EAnonFun __fun187))
  ].

Definition __fun189 :=
  AnonFun "xs" (
    deco "cons s (tail_scan f s xs)" (
      EApp (EApp (deco "cons" (EPath [ "cons" ])) (deco "s" (EPath [ "s" ]))) (
        deco "(tail_scan f s xs)" (
          EApp (
            EApp (
              EApp (deco "tail_scan" (EPath [ "tail_scan" ])) (
                deco "f" (EPath [ "f" ])
              )
            ) (deco "s" (EPath [ "s" ]))
          ) (deco "xs" (EPath [ "xs" ]))
        )
      )
    )
  ).

Definition __fun190 := AnonFun "s" (EAnonFun __fun189).

Definition __fun191 := AnonFun "f" (EAnonFun __fun190).

Definition __exp192 := EPath [ "empty" ].

Definition __branches193 :=
  [
    Branch (CVal (PData "Nil" [])) (deco "Nil" (EData "Nil" []));
    Branch (CVal (PData "Cons" [ PVar "x"; PVar "xs" ])) (
      deco "Cons (x, take_aux (n-1) xs)" (
        EData "Cons" [
          deco "x" (EPath [ "x" ]);
          deco "take_aux (n-1) xs" (
            EApp (
              EApp (deco "take_aux" (EPath [ "take_aux" ])) (
                deco "(n-1)" (
                  EIntSub (deco "n" (EPath [ "n" ])) (deco "1" (EInt 1))
                )
              )
            ) (deco "xs" (EPath [ "xs" ]))
          )
        ]
      )
    )
  ].

Definition __branches194 :=
  [
    Branch (CVal (PData "()" [])) (
      deco "match xs() with...e_aux (n-1) xs)" (
        EMatch (
          deco "xs()" (
            EApp (deco "xs" (EPath [ "xs" ])) (deco "()" (EData "()" []))
          )
        ) __branches193
      )
    )
  ].

Definition __fun195 := AnonFunction __branches194.

Definition __exp196 := EAnonFun __fun195.

Definition __fun197 :=
  AnonFun "xs" (
    deco "if n = 0 then e...e_aux (n-1) xs)" (
      EIfThenElse (
        deco "n = 0" (EOpEq (deco "n" (EPath [ "n" ])) (deco "0" (EInt 0)))
      ) (deco "empty" __exp192) (
        deco "fun () -> match...e_aux (n-1) xs)" __exp196
      )
    )
  ).

Definition __bindings198 :=
  [
    RecBinding "take_aux" (AnonFun "n" (EAnonFun __fun197))
  ].

Definition __exp199 :=
  EApp (deco "invalid_arg" (EPath [ "invalid_arg" ])) (
    deco """Seq.take""" (EString "Seq.take")
  ).

Definition __exp200 :=
  EApp (
    EApp (deco "take_aux" (EPath [ "take_aux" ])) (deco "n" (EPath [ "n" ]))
  ) (deco "xs" (EPath [ "xs" ])).

Definition __fun201 :=
  AnonFun "xs" (
    deco "if n < 0 then i...; take_aux n xs" (
      ESeq (
        deco "if n < 0 then i..._arg ""Seq.take""" (
          EIfThen (
            deco "n < 0" (EOpLt (deco "n" (EPath [ "n" ])) (deco "0" (EInt 0)))
          ) (deco "invalid_arg ""Seq.take""" __exp199)
        )
      ) (deco "take_aux n xs" __exp200)
    )
  ).

Definition __fun202 := AnonFun "n" (EAnonFun __fun201).

Definition __exp203 :=
  EApp (deco "xs" (EPath [ "xs" ])) (deco "()" (EData "()" [])).

Definition __exp204 :=
  EApp (
    EApp (deco "force_drop" (EPath [ "force_drop" ])) (deco "n" (EPath [ "n" ]))
  ) (deco "xs" (EPath [ "xs" ])).

Definition __exp205 :=
  EIfThenElse (
    deco "n = 0" (EOpEq (deco "n" (EPath [ "n" ])) (deco "0" (EInt 0)))
  ) (deco "xs()" __exp203) (deco "force_drop n xs" __exp204).

Definition __branches206 :=
  [
    Branch (CVal (PData "Nil" [])) (deco "Nil" (EData "Nil" []));
    Branch (CVal (PData "Cons" [ PAny; PVar "xs" ])) (
      deco "let n = n - 1 i...force_drop n xs" (
        ELet [
          Binding (PVar "n") (
            deco "n - 1" (
              EIntSub (deco "n" (EPath [ "n" ])) (deco "1" (EInt 1))
            )
          )
        ] (deco "if n = 0 then x...force_drop n xs" __exp205)
      )
    )
  ].

Definition __fun207 :=
  AnonFun "xs" (
    deco "match xs() with...force_drop n xs" (
      EMatch (
        deco "xs()" (
          EApp (deco "xs" (EPath [ "xs" ])) (deco "()" (EData "()" []))
        )
      ) __branches206
    )
  ).

Definition __bindings208 :=
  [
    RecBinding "force_drop" (AnonFun "n" (EAnonFun __fun207))
  ].

Definition __exp209 :=
  EApp (deco "invalid_arg" (EPath [ "invalid_arg" ])) (
    deco """Seq.drop""" (EString "Seq.drop")
  ).

Definition __exp210 := EPath [ "xs" ].

Definition __branches211 :=
  [
    Branch (CVal (PData "()" [])) (
      deco "force_drop n xs" (
        EApp (
          EApp (deco "force_drop" (EPath [ "force_drop" ])) (
            deco "n" (EPath [ "n" ])
          )
        ) (deco "xs" (EPath [ "xs" ]))
      )
    )
  ].

Definition __fun212 := AnonFunction __branches211.

Definition __exp213 := EAnonFun __fun212.

Definition __exp214 :=
  EIfThenElse (
    deco "n = 0" (EOpEq (deco "n" (EPath [ "n" ])) (deco "0" (EInt 0)))
  ) (deco "xs" __exp210) (deco "fun () -> force_drop n xs" __exp213).

Definition __fun215 :=
  AnonFun "xs" (
    deco "if n < 0 then i...force_drop n xs" (
      EIfThenElse (
        deco "n < 0" (EOpLt (deco "n" (EPath [ "n" ])) (deco "0" (EInt 0)))
      ) (deco "invalid_arg ""Seq.drop""" __exp209) (
        deco "if n = 0 then x...force_drop n xs" __exp214
      )
    )
  ).

Definition __fun216 := AnonFun "n" (EAnonFun __fun215).

Definition __exp217 :=
  EData "Cons" [
    deco "x" (EPath [ "x" ]);
    deco "take_while p xs" (
      EApp (
        EApp (deco "take_while" (EPath [ "take_while" ])) (
          deco "p" (EPath [ "p" ])
        )
      ) (deco "xs" (EPath [ "xs" ]))
    )
  ].

Definition __exp218 := EData "Nil" [].

Definition __branches219 :=
  [
    Branch (CVal (PData "Nil" [])) (deco "Nil" (EData "Nil" []));
    Branch (CVal (PData "Cons" [ PVar "x"; PVar "xs" ])) (
      deco "if p x then Con... p xs) else Nil" (
        EIfThenElse (
          deco "p x" (
            EApp (deco "p" (EPath [ "p" ])) (deco "x" (EPath [ "x" ]))
          )
        ) (deco "Cons (x, take_while p xs)" __exp217) (deco "Nil" __exp218)
      )
    )
  ].

Definition __branches220 :=
  [
    Branch (CVal (PData "()" [])) (
      deco "match xs() with... p xs) else Nil" (
        EMatch (
          deco "xs()" (
            EApp (deco "xs" (EPath [ "xs" ])) (deco "()" (EData "()" []))
          )
        ) __branches219
      )
    )
  ].

Definition __fun221 := AnonFunction __branches220.

Definition __fun222 := AnonFun "xs" (EAnonFun __fun221).

Definition __bindings223 :=
  [
    RecBinding "take_while" (AnonFun "p" (EAnonFun __fun222))
  ].

Definition __exp224 :=
  EApp (
    EApp (
      EApp (deco "drop_while" (EPath [ "drop_while" ])) (
        deco "p" (EPath [ "p" ])
      )
    ) (deco "xs" (EPath [ "xs" ]))
  ) (deco "()" (EData "()" [])).

Definition __exp225 := EPath [ "node" ].

Definition __branches226 :=
  [
    Branch (CVal (PData "Nil" [])) (deco "Nil" (EData "Nil" []));
    Branch (CVal (PAlias (PData "Cons" [ PVar "x"; PVar "xs" ]) "node")) (
      deco "if p x then dro...xs () else node" (
        EIfThenElse (
          deco "p x" (
            EApp (deco "p" (EPath [ "p" ])) (deco "x" (EPath [ "x" ]))
          )
        ) (deco "drop_while p xs ()" __exp224) (deco "node" __exp225)
      )
    )
  ].

Definition __branches227 :=
  [
    Branch (CVal (PData "()" [])) (
      deco "match xs() with...xs () else node" (
        EMatch (
          deco "xs()" (
            EApp (deco "xs" (EPath [ "xs" ])) (deco "()" (EData "()" []))
          )
        ) __branches226
      )
    )
  ].

Definition __fun228 := AnonFunction __branches227.

Definition __fun229 := AnonFun "xs" (EAnonFun __fun228).

Definition __bindings230 :=
  [
    RecBinding "drop_while" (AnonFun "p" (EAnonFun __fun229))
  ].

Definition __branches231 :=
  [
    Branch (CVal (PData "Nil" [])) (deco "Nil" (EData "Nil" []));
    Branch (CVal (PData "Cons" [ PVar "x"; PVar "xs" ])) (
      deco "Cons (cons x (t...ile (eq x) xs))" (
        EData "Cons" [
          deco "cons x (take_while (eq x) xs)" (
            EApp (
              EApp (deco "cons" (EPath [ "cons" ])) (deco "x" (EPath [ "x" ]))
            ) (
              deco "(take_while (eq x) xs)" (
                EApp (
                  EApp (deco "take_while" (EPath [ "take_while" ])) (
                    deco "(eq x)" (
                      EApp (deco "eq" (EPath [ "eq" ])) (
                        deco "x" (EPath [ "x" ])
                      )
                    )
                  )
                ) (deco "xs" (EPath [ "xs" ]))
              )
            )
          );
          deco "group eq (drop_while (eq x) xs)" (
            EApp (
              EApp (deco "group" (EPath [ "group" ])) (
                deco "eq" (EPath [ "eq" ])
              )
            ) (
              deco "(drop_while (eq x) xs)" (
                EApp (
                  EApp (deco "drop_while" (EPath [ "drop_while" ])) (
                    deco "(eq x)" (
                      EApp (deco "eq" (EPath [ "eq" ])) (
                        deco "x" (EPath [ "x" ])
                      )
                    )
                  )
                ) (deco "xs" (EPath [ "xs" ]))
              )
            )
          )
        ]
      )
    )
  ].

Definition __branches232 :=
  [
    Branch (CVal (PData "()" [])) (
      deco "match xs() with...ile (eq x) xs))" (
        EMatch (
          deco "xs()" (
            EApp (deco "xs" (EPath [ "xs" ])) (deco "()" (EData "()" []))
          )
        ) __branches231
      )
    )
  ].

Definition __fun233 := AnonFunction __branches232.

Definition __fun234 := AnonFun "xs" (EAnonFun __fun233).

Definition __bindings235 :=
  [
    RecBinding "group" (AnonFun "eq" (EAnonFun __fun234))
  ].

Definition __branches236 :=
  [
    Branch (CVal (PData "()" [])) (
      deco "Lazy.force s" (
        EApp (deco "Lazy.force" (EPath [ "Lazy"; "force" ])) (
          deco "s" (EPath [ "s" ])
        )
      )
    )
  ].

Definition __fun237 := AnonFunction __branches236.

Definition __branches238 :=
  [
    Branch (CVal (PAlias PAny "s")) (
      deco "fun () -> Lazy.force s" (EAnonFun __fun237)
    )
  ].

Definition __fun239 := AnonFunction __branches238.

Definition __branches240 :=
  [
    Branch (CVal (PAlias PAny "s")) (
      deco "from_lazy (to_lazy s)" (
        EApp (deco "from_lazy" (EPath [ "from_lazy" ])) (
          deco "(to_lazy s)" (
            EApp (deco "to_lazy" (EPath [ "to_lazy" ])) (
              deco "s" (EPath [ "s" ])
            )
          )
        )
      )
    )
  ].

Definition __fun241 := AnonFunction __branches240.

Definition __branches242 :=
  [
    Branch (CVal (PData "()" [])) (
      deco "raise Forced_twice" (
        ERaise (deco "Forced_twice" (EXData [ "Forced_twice" ] []))
      )
    )
  ].

Definition __fun243 := AnonFunction __branches242.

Definition __exp244 :=
  EApp (deco "f" (EPath [ "f" ])) (deco "()" (EData "()" [])).

Definition __branches245 :=
  [
    Branch (CVal (PData "()" [])) (
      deco "let f = Atomic.... failure in f()" (
        ELet [
          Binding (PVar "f") (
            deco "Atomic.exchange action failure" (
              EApp (
                EApp (deco "Atomic.exchange" (EPath [ "Atomic"; "exchange" ])) (
                  deco "action" (EPath [ "action" ])
                )
              ) (deco "failure" (EPath [ "failure" ]))
            )
          )
        ] (deco "f()" __exp244)
      )
    )
  ].

Definition __fun246 := AnonFunction __branches245.

Definition __exp247 := EAnonFun __fun246.

Definition __branches248 :=
  [
    Branch (CVal (PAlias PAny "f")) (
      deco "let action = At... failure in f()" (
        ELet [
          Binding (PVar "action") (
            deco "Atomic.make f" (
              EApp (deco "Atomic.make" (EPath [ "Atomic"; "make" ])) (
                deco "f" (EPath [ "f" ])
              )
            )
          )
        ] (deco "fun () -> (* Ge... failure in f()" __exp247)
      )
    )
  ].

Definition __fun249 := AnonFunction __branches248.

Definition __branches250 :=
  [
    Branch (CVal (PData "Nil" [])) (deco "Nil" (EData "Nil" []));
    Branch (CVal (PData "Cons" [ PVar "x"; PVar "xs" ])) (
      deco "Cons (x, memoize xs)" (
        EData "Cons" [
          deco "x" (EPath [ "x" ]);
          deco "memoize xs" (
            EApp (deco "memoize" (EPath [ "memoize" ])) (
              deco "xs" (EPath [ "xs" ])
            )
          )
        ]
      )
    )
  ].

Definition __branches251 :=
  [
    Branch (CVal (PData "()" [])) (
      deco "match xs() with...(x, memoize xs)" (
        EMatch (
          deco "xs()" (
            EApp (deco "xs" (EPath [ "xs" ])) (deco "()" (EData "()" []))
          )
        ) __branches250
      )
    )
  ].

Definition __fun252 := AnonFunction __branches251.

Definition __bindings253 :=
  [
    RecBinding "memoize" (
      AnonFun "xs" (
        deco "Suspension.memo..., memoize xs) )" (
          EApp (deco "Suspension.memoize" (EPath [ "Suspension"; "memoize" ])) (
            deco "(fun () -> matc..., memoize xs) )" (EAnonFun __fun252)
          )
        )
      )
    )
  ].

Definition __branches254 :=
  [
    Branch (CVal (PData "Nil" [])) (deco "Nil" (EData "Nil" []));
    Branch (CVal (PData "Cons" [ PVar "x"; PVar "xs" ])) (
      deco "Cons (x, once xs)" (
        EData "Cons" [
          deco "x" (EPath [ "x" ]);
          deco "once xs" (
            EApp (deco "once" (EPath [ "once" ])) (deco "xs" (EPath [ "xs" ]))
          )
        ]
      )
    )
  ].

Definition __branches255 :=
  [
    Branch (CVal (PData "()" [])) (
      deco "match xs() with...ns (x, once xs)" (
        EMatch (
          deco "xs()" (
            EApp (deco "xs" (EPath [ "xs" ])) (deco "()" (EData "()" []))
          )
        ) __branches254
      )
    )
  ].

Definition __fun256 := AnonFunction __branches255.

Definition __bindings257 :=
  [
    RecBinding "once" (
      AnonFun "xs" (
        deco "Suspension.once... (x, once xs) )" (
          EApp (deco "Suspension.once" (EPath [ "Suspension"; "once" ])) (
            deco "(fun () -> matc... (x, once xs) )" (EAnonFun __fun256)
          )
        )
      )
    )
  ].

Definition __branches258 :=
  [
    Branch (CVal (PData "Nil" [])) (deco "Nil" (EData "Nil" []));
    Branch (CVal (PData "Cons" [ PVar "y"; PVar "ys" ])) (
      deco "Cons ((x, y), zip xs ys)" (
        EData "Cons" [
          deco "(x, y)" (
            ETuple [
              deco "x" (EPath [ "x" ]);
              deco "y" (EPath [ "y" ])
            ]
          );
          deco "zip xs ys" (
            EApp (
              EApp (deco "zip" (EPath [ "zip" ])) (deco "xs" (EPath [ "xs" ]))
            ) (deco "ys" (EPath [ "ys" ]))
          )
        ]
      )
    )
  ].

Definition __branches259 :=
  [
    Branch (CVal (PData "Nil" [])) (deco "Nil" (EData "Nil" []));
    Branch (CVal (PData "Cons" [ PVar "x"; PVar "xs" ])) (
      deco "match ys() with... y), zip xs ys)" (
        EMatch (
          deco "ys()" (
            EApp (deco "ys" (EPath [ "ys" ])) (deco "()" (EData "()" []))
          )
        ) __branches258
      )
    )
  ].

Definition __branches260 :=
  [
    Branch (CVal (PData "()" [])) (
      deco "match xs() with... y), zip xs ys)" (
        EMatch (
          deco "xs()" (
            EApp (deco "xs" (EPath [ "xs" ])) (deco "()" (EData "()" []))
          )
        ) __branches259
      )
    )
  ].

Definition __fun261 := AnonFunction __branches260.

Definition __fun262 := AnonFun "ys" (EAnonFun __fun261).

Definition __bindings263 :=
  [
    RecBinding "zip" (AnonFun "xs" (EAnonFun __fun262))
  ].

Definition __branches264 :=
  [
    Branch (CVal (PData "Nil" [])) (deco "Nil" (EData "Nil" []));
    Branch (CVal (PData "Cons" [ PVar "y"; PVar "ys" ])) (
      deco "Cons (f x y, map2 f xs ys)" (
        EData "Cons" [
          deco "f x y" (
            EApp (EApp (deco "f" (EPath [ "f" ])) (deco "x" (EPath [ "x" ]))) (
              deco "y" (EPath [ "y" ])
            )
          );
          deco "map2 f xs ys" (
            EApp (
              EApp (
                EApp (deco "map2" (EPath [ "map2" ])) (deco "f" (EPath [ "f" ]))
              ) (deco "xs" (EPath [ "xs" ]))
            ) (deco "ys" (EPath [ "ys" ]))
          )
        ]
      )
    )
  ].

Definition __branches265 :=
  [
    Branch (CVal (PData "Nil" [])) (deco "Nil" (EData "Nil" []));
    Branch (CVal (PData "Cons" [ PVar "x"; PVar "xs" ])) (
      deco "match ys() with..., map2 f xs ys)" (
        EMatch (
          deco "ys()" (
            EApp (deco "ys" (EPath [ "ys" ])) (deco "()" (EData "()" []))
          )
        ) __branches264
      )
    )
  ].

Definition __branches266 :=
  [
    Branch (CVal (PData "()" [])) (
      deco "match xs() with..., map2 f xs ys)" (
        EMatch (
          deco "xs()" (
            EApp (deco "xs" (EPath [ "xs" ])) (deco "()" (EData "()" []))
          )
        ) __branches265
      )
    )
  ].

Definition __fun267 := AnonFunction __branches266.

Definition __fun268 := AnonFun "ys" (EAnonFun __fun267).

Definition __fun269 := AnonFun "xs" (EAnonFun __fun268).

Definition __bindings270 :=
  [
    RecBinding "map2" (AnonFun "f" (EAnonFun __fun269))
  ].

Definition __branches271 :=
  [
    Branch (CVal (PData "Nil" [])) (
      deco "ys()" (
        EApp (deco "ys" (EPath [ "ys" ])) (deco "()" (EData "()" []))
      )
    );
    Branch (CVal (PData "Cons" [ PVar "x"; PVar "xs" ])) (
      deco "Cons (x, interleave ys xs)" (
        EData "Cons" [
          deco "x" (EPath [ "x" ]);
          deco "interleave ys xs" (
            EApp (
              EApp (deco "interleave" (EPath [ "interleave" ])) (
                deco "ys" (EPath [ "ys" ])
              )
            ) (deco "xs" (EPath [ "xs" ]))
          )
        ]
      )
    )
  ].

Definition __branches272 :=
  [
    Branch (CVal (PData "()" [])) (
      deco "match xs() with...terleave ys xs)" (
        EMatch (
          deco "xs()" (
            EApp (deco "xs" (EPath [ "xs" ])) (deco "()" (EData "()" []))
          )
        ) __branches271
      )
    )
  ].

Definition __fun273 := AnonFunction __branches272.

Definition __fun274 := AnonFun "ys" (EAnonFun __fun273).

Definition __bindings275 :=
  [
    RecBinding "interleave" (AnonFun "xs" (EAnonFun __fun274))
  ].

Definition __branches276 :=
  [
    Branch (CVal (PData "Nil" [])) (
      deco "Cons (x, xs)" (
        EData "Cons" [
          deco "x" (EPath [ "x" ]);
          deco "xs" (EPath [ "xs" ])
        ]
      )
    );
    Branch (CVal (PData "Cons" [ PVar "y"; PVar "ys" ])) (
      deco "sorted_merge1 cmp x xs y ys" (
        EApp (
          EApp (
            EApp (
              EApp (
                EApp (deco "sorted_merge1" (EPath [ "sorted_merge1" ])) (
                  deco "cmp" (EPath [ "cmp" ])
                )
              ) (deco "x" (EPath [ "x" ]))
            ) (deco "xs" (EPath [ "xs" ]))
          ) (deco "y" (EPath [ "y" ]))
        ) (deco "ys" (EPath [ "ys" ]))
      )
    )
  ].

Definition __branches277 :=
  [
    Branch (CVal (PData "()" [])) (
      deco "match ys() with...1 cmp x xs y ys" (
        EMatch (
          deco "ys()" (
            EApp (deco "ys" (EPath [ "ys" ])) (deco "()" (EData "()" []))
          )
        ) __branches276
      )
    )
  ].

Definition __fun278 := AnonFunction __branches277.

Definition __fun279 := AnonFun "ys" (EAnonFun __fun278).

Definition __fun280 := AnonFun "xs" (EAnonFun __fun279).

Definition __fun281 := AnonFun "x" (EAnonFun __fun280).

Definition __branches282 :=
  [
    Branch (CVal (PData "Nil" [])) (
      deco "Cons (y, ys)" (
        EData "Cons" [
          deco "y" (EPath [ "y" ]);
          deco "ys" (EPath [ "ys" ])
        ]
      )
    );
    Branch (CVal (PData "Cons" [ PVar "x"; PVar "xs" ])) (
      deco "sorted_merge1 cmp x xs y ys" (
        EApp (
          EApp (
            EApp (
              EApp (
                EApp (deco "sorted_merge1" (EPath [ "sorted_merge1" ])) (
                  deco "cmp" (EPath [ "cmp" ])
                )
              ) (deco "x" (EPath [ "x" ]))
            ) (deco "xs" (EPath [ "xs" ]))
          ) (deco "y" (EPath [ "y" ]))
        ) (deco "ys" (EPath [ "ys" ]))
      )
    )
  ].

Definition __branches283 :=
  [
    Branch (CVal (PData "()" [])) (
      deco "match xs() with...1 cmp x xs y ys" (
        EMatch (
          deco "xs()" (
            EApp (deco "xs" (EPath [ "xs" ])) (deco "()" (EData "()" []))
          )
        ) __branches282
      )
    )
  ].

Definition __fun284 := AnonFunction __branches283.

Definition __fun285 := AnonFun "ys" (EAnonFun __fun284).

Definition __fun286 := AnonFun "y" (EAnonFun __fun285).

Definition __fun287 := AnonFun "xs" (EAnonFun __fun286).

Definition __exp288 :=
  EData "Cons" [
    deco "x" (EPath [ "x" ]);
    deco "sorted_merge1r cmp xs y ys" (
      EApp (
        EApp (
          EApp (
            EApp (deco "sorted_merge1r" (EPath [ "sorted_merge1r" ])) (
              deco "cmp" (EPath [ "cmp" ])
            )
          ) (deco "xs" (EPath [ "xs" ]))
        ) (deco "y" (EPath [ "y" ]))
      ) (deco "ys" (EPath [ "ys" ]))
    )
  ].

Definition __exp289 :=
  EData "Cons" [
    deco "y" (EPath [ "y" ]);
    deco "sorted_merge1l cmp x xs ys" (
      EApp (
        EApp (
          EApp (
            EApp (deco "sorted_merge1l" (EPath [ "sorted_merge1l" ])) (
              deco "cmp" (EPath [ "cmp" ])
            )
          ) (deco "x" (EPath [ "x" ]))
        ) (deco "xs" (EPath [ "xs" ]))
      ) (deco "ys" (EPath [ "ys" ]))
    )
  ].

Definition __fun290 :=
  AnonFun "ys" (
    deco "if cmp x y <= 0...1l cmp x xs ys)" (
      EIfThenElse (
        deco "cmp x y <= 0" (
          EOpLe (
            deco "cmp x y" (
              EApp (
                EApp (deco "cmp" (EPath [ "cmp" ])) (deco "x" (EPath [ "x" ]))
              ) (deco "y" (EPath [ "y" ]))
            )
          ) (deco "0" (EInt 0))
        )
      ) (deco "Cons (x, sorted...1r cmp xs y ys)" __exp288) (
        deco "Cons (y, sorted...1l cmp x xs ys)" __exp289
      )
    )
  ).

Definition __fun291 := AnonFun "y" (EAnonFun __fun290).

Definition __fun292 := AnonFun "xs" (EAnonFun __fun291).

Definition __fun293 := AnonFun "x" (EAnonFun __fun292).

Definition __bindings294 :=
  [
    RecBinding "sorted_merge1l" (AnonFun "cmp" (EAnonFun __fun281));
    RecBinding "sorted_merge1r" (AnonFun "cmp" (EAnonFun __fun287));
    RecBinding "sorted_merge1" (AnonFun "cmp" (EAnonFun __fun293))
  ].

Definition __branches295 :=
  [
    Branch (CVal (PTuple [ PData "Nil" []; PData "Nil" [] ])) (
      deco "Nil" (EData "Nil" [])
    );
    Branch (
      COr (CVal (PTuple [ PData "Nil" []; PVar "c" ])) (
        CVal (PTuple [ PVar "c"; PData "Nil" [] ])
      )
    ) (deco "c" (EPath [ "c" ]));
    Branch (
      CVal (
        PTuple [
          PData "Cons" [
            PVar "x";
            PVar "xs"
          ];
          PData "Cons" [
            PVar "y";
            PVar "ys"
          ]
        ]
      )
    ) (
      deco "sorted_merge1 cmp x xs y ys" (
        EApp (
          EApp (
            EApp (
              EApp (
                EApp (deco "sorted_merge1" (EPath [ "sorted_merge1" ])) (
                  deco "cmp" (EPath [ "cmp" ])
                )
              ) (deco "x" (EPath [ "x" ]))
            ) (deco "xs" (EPath [ "xs" ]))
          ) (deco "y" (EPath [ "y" ]))
        ) (deco "ys" (EPath [ "ys" ]))
      )
    )
  ].

Definition __branches296 :=
  [
    Branch (CVal (PData "()" [])) (
      deco "match xs(), ys(...1 cmp x xs y ys" (
        EMatch (
          deco "xs(), ys()" (
            ETuple [
              deco "xs()" (
                EApp (deco "xs" (EPath [ "xs" ])) (deco "()" (EData "()" []))
              );
              deco "ys()" (
                EApp (deco "ys" (EPath [ "ys" ])) (deco "()" (EData "()" []))
              )
            ]
          )
        ) __branches295
      )
    )
  ].

Definition __fun297 := AnonFunction __branches296.

Definition __fun298 := AnonFun "ys" (EAnonFun __fun297).

Definition __fun299 := AnonFun "xs" (EAnonFun __fun298).

Definition __fun300 := AnonFun "cmp" (EAnonFun __fun299).

Definition __branches301 :=
  [
    Branch (CVal (PData "Nil" [])) (deco "Nil" (EData "Nil" []));
    Branch (CVal (PData "Cons" [ PTuple [ PVar "x"; PAny ]; PVar "xys" ])) (
      deco "Cons (x, map_fst xys)" (
        EData "Cons" [
          deco "x" (EPath [ "x" ]);
          deco "map_fst xys" (
            EApp (deco "map_fst" (EPath [ "map_fst" ])) (
              deco "xys" (EPath [ "xys" ])
            )
          )
        ]
      )
    )
  ].

Definition __branches302 :=
  [
    Branch (CVal (PData "()" [])) (
      deco "match xys() wit...x, map_fst xys)" (
        EMatch (
          deco "xys()" (
            EApp (deco "xys" (EPath [ "xys" ])) (deco "()" (EData "()" []))
          )
        ) __branches301
      )
    )
  ].

Definition __fun303 := AnonFunction __branches302.

Definition __bindings304 :=
  [
    RecBinding "map_fst" (AnonFun "xys" (EAnonFun __fun303))
  ].

Definition __branches305 :=
  [
    Branch (CVal (PData "Nil" [])) (deco "Nil" (EData "Nil" []));
    Branch (CVal (PData "Cons" [ PTuple [ PAny; PVar "y" ]; PVar "xys" ])) (
      deco "Cons (y, map_snd xys)" (
        EData "Cons" [
          deco "y" (EPath [ "y" ]);
          deco "map_snd xys" (
            EApp (deco "map_snd" (EPath [ "map_snd" ])) (
              deco "xys" (EPath [ "xys" ])
            )
          )
        ]
      )
    )
  ].

Definition __branches306 :=
  [
    Branch (CVal (PData "()" [])) (
      deco "match xys() wit...y, map_snd xys)" (
        EMatch (
          deco "xys()" (
            EApp (deco "xys" (EPath [ "xys" ])) (deco "()" (EData "()" []))
          )
        ) __branches305
      )
    )
  ].

Definition __fun307 := AnonFunction __branches306.

Definition __bindings308 :=
  [
    RecBinding "map_snd" (AnonFun "xys" (EAnonFun __fun307))
  ].

Definition __fun309 :=
  AnonFun "xys" (
    deco "map_fst xys, map_snd xys" (
      ETuple [
        deco "map_fst xys" (
          EApp (deco "map_fst" (EPath [ "map_fst" ])) (
            deco "xys" (EPath [ "xys" ])
          )
        );
        deco "map_snd xys" (
          EApp (deco "map_snd" (EPath [ "map_snd" ])) (
            deco "xys" (EPath [ "xys" ])
          )
        )
      ]
    )
  ).

Definition __branches310 :=
  [
    Branch (CVal (PData "Left" [ PVar "y" ])) (
      deco "Cons (y, filter..._left_map f xs)" (
        EData "Cons" [
          deco "y" (EPath [ "y" ]);
          deco "filter_map_find_left_map f xs" (
            EApp (
              EApp (
                deco "filter_map_find_left_map" (
                  EPath [
                    "filter_map_find_left_map"
                  ]
                )
              ) (deco "f" (EPath [ "f" ]))
            ) (deco "xs" (EPath [ "xs" ]))
          )
        ]
      )
    );
    Branch (CVal (PData "Right" [ PAny ])) (
      deco "filter_map_find_left_map f xs ()" (
        EApp (
          EApp (
            EApp (
              deco "filter_map_find_left_map" (
                EPath [
                  "filter_map_find_left_map"
                ]
              )
            ) (deco "f" (EPath [ "f" ]))
          ) (deco "xs" (EPath [ "xs" ]))
        ) (deco "()" (EData "()" []))
      )
    )
  ].

Definition __branches311 :=
  [
    Branch (CVal (PData "Nil" [])) (deco "Nil" (EData "Nil" []));
    Branch (CVal (PData "Cons" [ PVar "x"; PVar "xs" ])) (
      deco "match f x with ...eft_map f xs ()" (
        EMatch (
          deco "f x" (
            EApp (deco "f" (EPath [ "f" ])) (deco "x" (EPath [ "x" ]))
          )
        ) __branches310
      )
    )
  ].

Definition __branches312 :=
  [
    Branch (CVal (PData "()" [])) (
      deco "match xs() with...eft_map f xs ()" (
        EMatch (
          deco "xs()" (
            EApp (deco "xs" (EPath [ "xs" ])) (deco "()" (EData "()" []))
          )
        ) __branches311
      )
    )
  ].

Definition __fun313 := AnonFunction __branches312.

Definition __fun314 := AnonFun "xs" (EAnonFun __fun313).

Definition __bindings315 :=
  [
    RecBinding "filter_map_find_left_map" (AnonFun "f" (EAnonFun __fun314))
  ].

Definition __branches316 :=
  [
    Branch (CVal (PData "Left" [ PAny ])) (
      deco "filter_map_find_right_map f xs ()" (
        EApp (
          EApp (
            EApp (
              deco "filter_map_find_right_map" (
                EPath [
                  "filter_map_find_right_map"
                ]
              )
            ) (deco "f" (EPath [ "f" ]))
          ) (deco "xs" (EPath [ "xs" ]))
        ) (deco "()" (EData "()" []))
      )
    );
    Branch (CVal (PData "Right" [ PVar "z" ])) (
      deco "Cons (z, filter...right_map f xs)" (
        EData "Cons" [
          deco "z" (EPath [ "z" ]);
          deco "filter_map_find_right_map f xs" (
            EApp (
              EApp (
                deco "filter_map_find_right_map" (
                  EPath [
                    "filter_map_find_right_map"
                  ]
                )
              ) (deco "f" (EPath [ "f" ]))
            ) (deco "xs" (EPath [ "xs" ]))
          )
        ]
      )
    )
  ].

Definition __branches317 :=
  [
    Branch (CVal (PData "Nil" [])) (deco "Nil" (EData "Nil" []));
    Branch (CVal (PData "Cons" [ PVar "x"; PVar "xs" ])) (
      deco "match f x with ...right_map f xs)" (
        EMatch (
          deco "f x" (
            EApp (deco "f" (EPath [ "f" ])) (deco "x" (EPath [ "x" ]))
          )
        ) __branches316
      )
    )
  ].

Definition __branches318 :=
  [
    Branch (CVal (PData "()" [])) (
      deco "match xs() with...right_map f xs)" (
        EMatch (
          deco "xs()" (
            EApp (deco "xs" (EPath [ "xs" ])) (deco "()" (EData "()" []))
          )
        ) __branches317
      )
    )
  ].

Definition __fun319 := AnonFunction __branches318.

Definition __fun320 := AnonFun "xs" (EAnonFun __fun319).

Definition __bindings321 :=
  [
    RecBinding "filter_map_find_right_map" (AnonFun "f" (EAnonFun __fun320))
  ].

Definition __fun322 :=
  AnonFun "xs" (
    deco "filter_map_find..._right_map f xs" (
      ETuple [
        deco "filter_map_find_left_map f xs" (
          EApp (
            EApp (
              deco "filter_map_find_left_map" (
                EPath [
                  "filter_map_find_left_map"
                ]
              )
            ) (deco "f" (EPath [ "f" ]))
          ) (deco "xs" (EPath [ "xs" ]))
        );
        deco "filter_map_find_right_map f xs" (
          EApp (
            EApp (
              deco "filter_map_find_right_map" (
                EPath [
                  "filter_map_find_right_map"
                ]
              )
            ) (deco "f" (EPath [ "f" ]))
          ) (deco "xs" (EPath [ "xs" ]))
        )
      ]
    )
  ).

Definition __fun323 := AnonFun "f" (EAnonFun __fun322).

Definition __fun324 :=
  AnonFun "x" (
    deco "not (p x)" (
      EBoolNeg (
        deco "(p x)" (
          EApp (deco "p" (EPath [ "p" ])) (deco "x" (EPath [ "x" ]))
        )
      )
    )
  ).

Definition __fun325 :=
  AnonFun "xs" (
    deco "filter p xs, fi...> not (p x)) xs" (
      ETuple [
        deco "filter p xs" (
          EApp (
            EApp (deco "filter" (EPath [ "filter" ])) (deco "p" (EPath [ "p" ]))
          ) (deco "xs" (EPath [ "xs" ]))
        );
        deco "filter (fun x -> not (p x)) xs" (
          EApp (
            EApp (deco "filter" (EPath [ "filter" ])) (
              deco "(fun x -> not (p x))" (EAnonFun __fun324)
            )
          ) (deco "xs" (EPath [ "xs" ]))
        )
      ]
    )
  ).

Definition __fun326 := AnonFun "p" (EAnonFun __fun325).

Definition __fun327 :=
  AnonFun "xss" (
    deco "unzip (filter_map uncons xss)" (
      EApp (deco "unzip" (EPath [ "unzip" ])) (
        deco "(filter_map uncons xss)" (
          EApp (
            EApp (deco "filter_map" (EPath [ "filter_map" ])) (
              deco "uncons" (EPath [ "uncons" ])
            )
          ) (deco "xss" (EPath [ "xss" ]))
        )
      )
    )
  ).

Definition __exp328 := EData "Nil" [].

Definition __exp329 :=
  ESeq (
    deco "assert (is_empty tails)" (
      EAssert (
        deco "(is_empty tails)" (
          EApp (deco "is_empty" (EPath [ "is_empty" ])) (
            deco "tails" (EPath [ "tails" ])
          )
        )
      )
    )
  ) (deco "Nil" __exp328).

Definition __exp330 :=
  EData "Cons" [
    deco "heads" (EPath [ "heads" ]);
    deco "transpose tails" (
      EApp (deco "transpose" (EPath [ "transpose" ])) (
        deco "tails" (EPath [ "tails" ])
      )
    )
  ].

Definition __exp331 :=
  EIfThenElse (
    deco "is_empty heads" (
      EApp (deco "is_empty" (EPath [ "is_empty" ])) (
        deco "heads" (EPath [ "heads" ])
      )
    )
  ) (deco "begin assert (i...tails); Nil end" __exp329) (
    deco "Cons (heads, transpose tails)" __exp330
  ).

Definition __branches332 :=
  [
    Branch (CVal (PData "()" [])) (
      deco "let heads, tail...ranspose tails)" (
        ELet [
          Binding (PTuple [ PVar "heads"; PVar "tails" ]) (
            deco "peel xss" (
              EApp (deco "peel" (EPath [ "peel" ])) (
                deco "xss" (EPath [ "xss" ])
              )
            )
          )
        ] (deco "if is_empty hea...ranspose tails)" __exp331)
      )
    )
  ].

Definition __fun333 := AnonFunction __branches332.

Definition __bindings334 :=
  [
    RecBinding "transpose" (AnonFun "xss" (EAnonFun __fun333))
  ].

Definition __exp335 :=
  EData "Cons" [
    deco "cons x heads" (
      EApp (EApp (deco "cons" (EPath [ "cons" ])) (deco "x" (EPath [ "x" ]))) (
        deco "heads" (EPath [ "heads" ])
      )
    );
    deco "diagonals (cons xs tails) xss" (
      EApp (
        EApp (deco "diagonals" (EPath [ "diagonals" ])) (
          deco "(cons xs tails)" (
            EApp (
              EApp (deco "cons" (EPath [ "cons" ])) (deco "xs" (EPath [ "xs" ]))
            ) (deco "tails" (EPath [ "tails" ]))
          )
        )
      ) (deco "xss" (EPath [ "xss" ]))
    )
  ].

Definition __exp336 :=
  EData "Cons" [
    deco "heads" (EPath [ "heads" ]);
    deco "diagonals tails xss" (
      EApp (
        EApp (deco "diagonals" (EPath [ "diagonals" ])) (
          deco "tails" (EPath [ "tails" ])
        )
      ) (deco "xss" (EPath [ "xss" ]))
    )
  ].

Definition __branches337 :=
  [
    Branch (CVal (PData "Cons" [ PVar "x"; PVar "xs" ])) (
      deco "let heads, tail... xs tails) xss)" (
        ELet [
          Binding (PTuple [ PVar "heads"; PVar "tails" ]) (
            deco "peel remainders" (
              EApp (deco "peel" (EPath [ "peel" ])) (
                deco "remainders" (EPath [ "remainders" ])
              )
            )
          )
        ] (deco "Cons (cons x he... xs tails) xss)" __exp335)
      )
    );
    Branch (CVal (PData "Nil" [])) (
      deco "let heads, tail...nals tails xss)" (
        ELet [
          Binding (PTuple [ PVar "heads"; PVar "tails" ]) (
            deco "peel remainders" (
              EApp (deco "peel" (EPath [ "peel" ])) (
                deco "remainders" (EPath [ "remainders" ])
              )
            )
          )
        ] (deco "Cons (heads, diagonals tails xss)" __exp336)
      )
    )
  ].

Definition __branches338 :=
  [
    Branch (CVal (PData "Cons" [ PVar "xs"; PVar "xss" ])) (
      deco "begin match xs(... tails xss) end" (
        EMatch (
          deco "xs()" (
            EApp (deco "xs" (EPath [ "xs" ])) (deco "()" (EData "()" []))
          )
        ) __branches337
      )
    );
    Branch (CVal (PData "Nil" [])) (
      deco "transpose remainders ()" (
        EApp (
          EApp (deco "transpose" (EPath [ "transpose" ])) (
            deco "remainders" (EPath [ "remainders" ])
          )
        ) (deco "()" (EData "()" []))
      )
    )
  ].

Definition __branches339 :=
  [
    Branch (CVal (PData "()" [])) (
      deco "match xss() wit...e remainders ()" (
        EMatch (
          deco "xss()" (
            EApp (deco "xss" (EPath [ "xss" ])) (deco "()" (EData "()" []))
          )
        ) __branches338
      )
    )
  ].

Definition __fun340 := AnonFunction __branches339.

Definition __fun341 := AnonFun "xss" (EAnonFun __fun340).

Definition __bindings342 :=
  [
    RecBinding "diagonals" (AnonFun "remainders" (EAnonFun __fun341))
  ].

Definition __fun343 :=
  AnonFun "xss" (
    deco "diagonals empty xss" (
      EApp (
        EApp (deco "diagonals" (EPath [ "diagonals" ])) (
          deco "empty" (EPath [ "empty" ])
        )
      ) (deco "xss" (EPath [ "xss" ]))
    )
  ).

Definition __fun344 :=
  AnonFun "y" (
    deco "f x y" (
      EApp (EApp (deco "f" (EPath [ "f" ])) (deco "x" (EPath [ "x" ]))) (
        deco "y" (EPath [ "y" ])
      )
    )
  ).

Definition __fun345 :=
  AnonFun "x" (
    deco "map (fun y -> f x y ) ys" (
      EApp (
        EApp (deco "map" (EPath [ "map" ])) (
          deco "(fun y -> f x y )" (EAnonFun __fun344)
        )
      ) (deco "ys" (EPath [ "ys" ]))
    )
  ).

Definition __fun346 :=
  AnonFun "ys" (
    deco "concat (diagona... y ) ys ) xs ))" (
      EApp (deco "concat" (EPath [ "concat" ])) (
        deco "(diagonals ( ma... y ) ys ) xs ))" (
          EApp (deco "diagonals" (EPath [ "diagonals" ])) (
            deco "( map (fun x ->...x y ) ys ) xs )" (
              EApp (
                EApp (deco "map" (EPath [ "map" ])) (
                  deco "(fun x -> map (...-> f x y ) ys )" (EAnonFun __fun345)
                )
              ) (deco "xs" (EPath [ "xs" ]))
            )
          )
        )
      )
    )
  ).

Definition __fun347 := AnonFun "xs" (EAnonFun __fun346).

Definition __fun348 := AnonFun "f" (EAnonFun __fun347).

Definition __fun349 :=
  AnonFun "y" (
    deco "(x, y)" (
      ETuple [
        deco "x" (EPath [ "x" ]);
        deco "y" (EPath [ "y" ])
      ]
    )
  ).

Definition __fun350 := AnonFun "x" (EAnonFun __fun349).

Definition __fun351 :=
  AnonFun "ys" (
    deco "map_product (fu...> (x, y)) xs ys" (
      EApp (
        EApp (
          EApp (deco "map_product" (EPath [ "map_product" ])) (
            deco "(fun x y -> (x, y))" (EAnonFun __fun350)
          )
        ) (deco "xs" (EPath [ "xs" ]))
      ) (deco "ys" (EPath [ "ys" ]))
    )
  ).

Definition __fun352 := AnonFun "xs" (EAnonFun __fun351).

Definition __branches353 :=
  [
    Branch (CVal (PData "None" [])) (deco "Nil" (EData "Nil" []));
    Branch (CVal (PData "Some" [ PVar "x" ])) (
      deco "Cons (x, c)" (
        EData "Cons" [
          deco "x" (EPath [ "x" ]);
          deco "c" (EPath [ "c" ])
        ]
      )
    )
  ].

Definition __branches354 :=
  [
    Branch (CVal (PData "()" [])) (
      deco "match it() with... -> Cons (x, c)" (
        EMatch (
          deco "it()" (
            EApp (deco "it" (EPath [ "it" ])) (deco "()" (EData "()" []))
          )
        ) __branches353
      )
    )
  ].

Definition __bindings355 := [ RecBinding "c" (AnonFunction __branches354) ].

Definition __exp356 := EPath [ "c" ].

Definition __fun357 :=
  AnonFun "it" (
    deco "let rec c () = ...ons (x, c) in c" (
      ELetRec __bindings355 (deco "c" __exp356)
    )
  ).

Definition __exp358 := EData "Some" [ deco "x" (EPath [ "x" ]) ].

Definition __branches359 :=
  [
    Branch (CVal (PData "Nil" [])) (deco "None" (EData "None" []));
    Branch (CVal (PData "Cons" [ PVar "x"; PVar "xs" ])) (
      deco "s := xs; Some x" (
        ESeq (
          deco "s := xs" (
            EStore (deco "s" (EPath [ "s" ])) (deco "xs" (EPath [ "xs" ]))
          )
        ) (deco "Some x" __exp358)
      )
    )
  ].

Definition __branches360 :=
  [
    Branch (CVal (PData "()" [])) (
      deco "match (!s)() wi...s := xs; Some x" (
        EMatch (
          deco "(!s)()" (
            EApp (deco "(!s)" (ELoad (deco "s" (EPath [ "s" ])))) (
              deco "()" (EData "()" [])
            )
          )
        ) __branches359
      )
    )
  ].

Definition __fun361 := AnonFunction __branches360.

Definition __exp362 := EAnonFun __fun361.

Definition __fun363 :=
  AnonFun "xs" (
    deco "let s = ref xs ...s := xs; Some x" (
      ELet [
        Binding (PVar "s") (deco "ref xs" (ERef (deco "xs" (EPath [ "xs" ]))))
      ] (deco "fun () -> match...s := xs; Some x" __exp362)
    )
  ).

Definition __branches364 :=
  [
    Branch (CVal (PData "()" [])) (
      deco "Cons (i, ints (i + 1))" (
        EData "Cons" [
          deco "i" (EPath [ "i" ]);
          deco "ints (i + 1)" (
            EApp (deco "ints" (EPath [ "ints" ])) (
              deco "(i + 1)" (
                EIntAdd (deco "i" (EPath [ "i" ])) (deco "1" (EInt 1))
              )
            )
          )
        ]
      )
    )
  ].

Definition __fun365 := AnonFunction __branches364.

Definition __bindings366 :=
  [
    RecBinding "ints" (AnonFun "i" (EAnonFun __fun365))
  ].

Definition __main :=
  MStruct [
    ILet [
      Binding (PVar "empty") (deco "() = Nil" (EAnonFun __fun1))
    ];
    ILet [
      Binding (PVar "return") (deco "x () = Cons (x, empty)" (EAnonFun __fun4))
    ];
    ILet [
      Binding (PVar "cons") (
        deco "x next () = Cons (x, next)" (EAnonFun __fun8)
      )
    ];
    ILetRec __bindings13;
    ILetRec __bindings18;
    ILetRec __bindings24;
    ILetRec __bindings31;
    ILetRec __bindings35;
    ILetRec __bindings40;
    ILet [
      Binding (PVar "concat_map") (deco "flat_map" (EPath [ "flat_map" ]))
    ];
    ILetRec __bindings45;
    ILetRec __bindings49;
    ILetRec __bindings54;
    ILet [
      Binding (PVar "is_empty") (
        deco "xs = match xs()...(_, _) -> false" (EAnonFun __fun56)
      )
    ];
    ILet [
      Binding (PVar "uncons") (
        deco "xs = match xs()...) | Nil -> None" (EAnonFun __fun58)
      )
    ];
    ILetRec __bindings61;
    ILet [
      Binding (PVar "length") (deco "xs = length_aux 0 xs" (EAnonFun __fun62))
    ];
    ILetRec __bindings67;
    ILet [
      Binding (PVar "iteri") (deco "f xs = iteri_aux f 0 xs" (EAnonFun __fun69))
    ];
    ILetRec __bindings75;
    ILet [
      Binding (PVar "fold_lefti") (
        deco "f accu xs = fol...aux f accu 0 xs" (EAnonFun __fun78)
      )
    ];
    ILetRec __bindings81;
    ILetRec __bindings84;
    ILetRec __bindings89;
    ILet [
      Binding (PVar "find_index") (
        deco "p xs = let rec ... xs in aux 0 xs" (EAnonFun __fun97)
      )
    ];
    ILetRec __bindings101;
    ILet [
      Binding (PVar "find_mapi") (
        deco "f xs = let rec ...ult in aux 0 xs" (EAnonFun __fun108)
      )
    ];
    ILetRec __bindings114;
    ILetRec __bindings121;
    ILetRec __bindings126;
    ILetRec __bindings131;
    ILetRec __bindings135;
    ILetRec __bindings142;
    ILetRec __bindings149;
    ILet [
      Binding (PVar "init") (
        deco "n f = if n < 0 ... init_aux f 0 n" (EAnonFun __fun153)
      )
    ];
    ILetRec __bindings156;
    ILetRec __bindings159;
    ILetRec __bindings162;
    ILet [
      Binding (PVar "cycle") (
        deco "xs () = match x...e_nonempty xs))" (EAnonFun __fun166)
      )
    ];
    ILetRec __bindings171;
    ILet [
      Binding (PVar "iterate") (
        deco "f x = cons x (iterate1 f x)" (EAnonFun __fun173)
      )
    ];
    ILetRec __bindings179;
    ILet [
      Binding (PVar "mapi") (deco "f xs = mapi_aux f 0 xs" (EAnonFun __fun181))
    ];
    ILetRec __bindings188;
    ILet [
      Binding (PVar "scan") (
        deco "f s xs = cons s...il_scan f s xs)" (EAnonFun __fun191)
      )
    ];
    ILetRec __bindings198;
    ILet [
      Binding (PVar "take") (
        deco "n xs = if n < 0...; take_aux n xs" (EAnonFun __fun202)
      )
    ];
    ILetRec __bindings208;
    ILet [
      Binding (PVar "drop") (
        deco "n xs = if n < 0...force_drop n xs" (EAnonFun __fun216)
      )
    ];
    ILetRec __bindings223;
    ILetRec __bindings230;
    ILetRec __bindings235;
    IExtend [
      "Forced_twice"
    ];
    IModule "Suspension" (
      MStruct [
        ILet [
          Binding (PAlias PAny "to_lazy") (
            deco "Lazy.from_fun" (EPath [ "Lazy"; "from_fun" ])
          )
        ];
        ILet [
          Binding (PVar "from_lazy") (
            deco "(s : 'a Lazy.t)...-> Lazy.force s" (EAnonFun __fun239)
          )
        ];
        ILet [
          Binding (PVar "memoize") (
            deco "(s : 'a suspens...azy (to_lazy s)" (EAnonFun __fun241)
          )
        ];
        ILet [
          Binding (PAlias PAny "failure") (
            deco "fun () -> (* A ...se Forced_twice" (EAnonFun __fun243)
          )
        ];
        ILet [
          Binding (PVar "once") (
            deco "(f : 'a suspens... failure in f()" (EAnonFun __fun249)
          )
        ]
      ]
    );
    ILetRec __bindings253;
    ILetRec __bindings257;
    ILetRec __bindings263;
    ILetRec __bindings270;
    ILetRec __bindings275;
    ILetRec __bindings294;
    ILet [
      Binding (PVar "sorted_merge") (
        deco "cmp xs ys () = ...1 cmp x xs y ys" (EAnonFun __fun300)
      )
    ];
    ILetRec __bindings304;
    ILetRec __bindings308;
    ILet [
      Binding (PVar "unzip") (
        deco "xys = map_fst xys, map_snd xys" (EAnonFun __fun309)
      )
    ];
    ILet [
      Binding (PVar "split") (deco "unzip" (EPath [ "unzip" ]))
    ];
    ILetRec __bindings315;
    ILetRec __bindings321;
    ILet [
      Binding (PVar "partition_map") (
        deco "f xs = filter_m..._right_map f xs" (EAnonFun __fun323)
      )
    ];
    ILet [
      Binding (PVar "partition") (
        deco "p xs = filter p...> not (p x)) xs" (EAnonFun __fun326)
      )
    ];
    ILet [
      Binding (PVar "peel") (
        deco "xss = unzip (fi...map uncons xss)" (EAnonFun __fun327)
      )
    ];
    ILetRec __bindings334;
    ILetRec __bindings342;
    ILet [
      Binding (PVar "diagonals") (
        deco "xss = diagonals empty xss" (EAnonFun __fun343)
      )
    ];
    ILet [
      Binding (PVar "map_product") (
        deco "f xs ys = conca... y ) ys ) xs ))" (EAnonFun __fun348)
      )
    ];
    ILet [
      Binding (PVar "product") (
        deco "xs ys = map_pro...> (x, y)) xs ys" (EAnonFun __fun352)
      )
    ];
    ILet [
      Binding (PVar "of_dispenser") (
        deco "it = let rec c ...ons (x, c) in c" (EAnonFun __fun357)
      )
    ];
    ILet [
      Binding (PVar "to_dispenser") (
        deco "xs = let s = re...s := xs; Some x" (EAnonFun __fun363)
      )
    ];
    ILetRec __bindings366
  ].

