(* This file has been generated by Osiris. Do not edit. *)

From osiris Require Import osiris.

Definition __exp0 :=
  EApp (deco "invalid_arg" (EPath [ "invalid_arg" ])) (
    deco """Semaphore.Coun... initial value""" (
      EString "Semaphore.Counting.init: wrong initial value"
    )
  ).

Definition __exp1 :=
  ERecord [
    Fexpr "mut" (
      deco "Mutex.create()" (
        EApp (deco "Mutex.create" (EPath [ "Mutex"; "create" ])) (
          deco "()" (EData "()" [])
        )
      )
    );
    Fexpr "v" (deco "v" (EPath [ "v" ]));
    Fexpr "nonzero" (
      deco "Condition.create()" (
        EApp (deco "Condition.create" (EPath [ "Condition"; "create" ])) (
          deco "()" (EData "()" [])
        )
      )
    )
  ].

Definition __fun2 :=
  AnonFun "v" (
    deco "if v < 0 then i...tion.create() }" (
      ESeq (
        deco "if v < 0 then i... initial value""" (
          EIfThen (
            deco "v < 0" (EOpLt (deco "v" (EPath [ "v" ])) (deco "0" (EInt 0)))
          ) (deco "invalid_arg ""Se... initial value""" __exp0)
        )
      ) (deco "{ mut = Mutex.c...tion.create() }" __exp1)
    )
  ).

Definition __exp3 :=
  EApp (deco "Mutex.unlock" (EPath [ "Mutex"; "unlock" ])) (
    deco "s.mut" (ERecordAccess (deco "s" (EPath [ "s" ])) "mut")
  ).

Definition __exp4 :=
  ESeq (
    deco "Condition.signal s.nonzero" (
      EApp (deco "Condition.signal" (EPath [ "Condition"; "signal" ])) (
        deco "s.nonzero" (ERecordAccess (deco "s" (EPath [ "s" ])) "nonzero")
      )
    )
  ) (deco "Mutex.unlock s.mut" __exp3).

Definition __exp5 :=
  ESeq (deco "s.v <- s.v + 1" EUnsupported) (
    deco "Condition.signa...ex.unlock s.mut" __exp4
  ).

Definition __exp6 :=
  ERaise (
    deco "(Sys_error ""Sem...ase: overflow"")" (
      EXData [
        "Sys_error"
      ] [
        deco """Semaphore.Coun...ease: overflow""" (
          EString "Semaphore.Counting.release: overflow"
        )
      ]
    )
  ).

Definition __exp7 :=
  ESeq (
    deco "Mutex.unlock s.mut" (
      EApp (deco "Mutex.unlock" (EPath [ "Mutex"; "unlock" ])) (
        deco "s.mut" (ERecordAccess (deco "s" (EPath [ "s" ])) "mut")
      )
    )
  ) (deco "raise (Sys_erro...ase: overflow"")" __exp6).

Definition __exp8 :=
  EIfThenElse (
    deco "s.v < max_int" (
      EOpLt (deco "s.v" (ERecordAccess (deco "s" (EPath [ "s" ])) "v")) (
        deco "max_int" (EPath [ "max_int" ])
      )
    )
  ) (deco "begin s.v <- s....nlock s.mut end" __exp5) (
    deco "begin Mutex.unl... overflow"") end" __exp7
  ).

Definition __fun9 :=
  AnonFun "s" (
    deco "Mutex.lock s.mu... overflow"") end" (
      ESeq (
        deco "Mutex.lock s.mut" (
          EApp (deco "Mutex.lock" (EPath [ "Mutex"; "lock" ])) (
            deco "s.mut" (ERecordAccess (deco "s" (EPath [ "s" ])) "mut")
          )
        )
      ) (deco "if s.v < max_in... overflow"") end" __exp8)
    )
  ).

Definition __exp10 :=
  EApp (
    EApp (deco "Condition.wait" (EPath [ "Condition"; "wait" ])) (
      deco "s.nonzero" (ERecordAccess (deco "s" (EPath [ "s" ])) "nonzero")
    )
  ) (deco "s.mut" (ERecordAccess (deco "s" (EPath [ "s" ])) "mut")).

Definition __exp11 :=
  EApp (deco "Mutex.unlock" (EPath [ "Mutex"; "unlock" ])) (
    deco "s.mut" (ERecordAccess (deco "s" (EPath [ "s" ])) "mut")
  ).

Definition __exp12 :=
  ESeq (deco "s.v <- s.v - 1" EUnsupported) (deco "Mutex.unlock s.mut" __exp11).

Definition __exp13 :=
  ESeq (
    deco "while s.v = 0 d...zero s.mut done" (
      EWhile (
        deco "s.v = 0" (
          EOpEq (deco "s.v" (ERecordAccess (deco "s" (EPath [ "s" ])) "v")) (
            deco "0" (EInt 0)
          )
        )
      ) (deco "Condition.wait s.nonzero s.mut" __exp10)
    )
  ) (deco "s.v <- s.v - 1;...ex.unlock s.mut" __exp12).

Definition __fun14 :=
  AnonFun "s" (
    deco "Mutex.lock s.mu...ex.unlock s.mut" (
      ESeq (
        deco "Mutex.lock s.mut" (
          EApp (deco "Mutex.lock" (EPath [ "Mutex"; "lock" ])) (
            deco "s.mut" (ERecordAccess (deco "s" (EPath [ "s" ])) "mut")
          )
        )
      ) (deco "while s.v = 0 d...ex.unlock s.mut" __exp13)
    )
  ).

Definition __exp15 := EData "false" [].

Definition __exp16 := EData "true" [].

Definition __exp17 :=
  ESeq (deco "s.v <- s.v - 1" EUnsupported) (deco "true" __exp16).

Definition __exp18 := EPath [ "ret" ].

Definition __exp19 :=
  ESeq (
    deco "Mutex.unlock s.mut" (
      EApp (deco "Mutex.unlock" (EPath [ "Mutex"; "unlock" ])) (
        deco "s.mut" (ERecordAccess (deco "s" (EPath [ "s" ])) "mut")
      )
    )
  ) (deco "ret" __exp18).

Definition __exp20 :=
  ELet [
    Binding (PVar "ret") (
      deco "if s.v = 0 then... s.v - 1; true)" (
        EIfThenElse (
          deco "s.v = 0" (
            EOpEq (deco "s.v" (ERecordAccess (deco "s" (EPath [ "s" ])) "v")) (
              deco "0" (EInt 0)
            )
          )
        ) (deco "false" __exp15) (deco "(s.v <- s.v - 1; true)" __exp17)
      )
    )
  ] (deco "Mutex.unlock s.mut; ret" __exp19).

Definition __fun21 :=
  AnonFun "s" (
    deco "Mutex.lock s.mu...lock s.mut; ret" (
      ESeq (
        deco "Mutex.lock s.mut" (
          EApp (deco "Mutex.lock" (EPath [ "Mutex"; "lock" ])) (
            deco "s.mut" (ERecordAccess (deco "s" (EPath [ "s" ])) "mut")
          )
        )
      ) (deco "let ret = if s....lock s.mut; ret" __exp20)
    )
  ).

Definition __fun22 :=
  AnonFun "s" (deco "s.v" (ERecordAccess (deco "s" (EPath [ "s" ])) "v")).

Definition __exp23 := EInt 1.

Definition __exp24 := EInt 0.

Definition __fun25 :=
  AnonFun "b" (
    deco "{ mut = Mutex.c...tion.create() }" (
      ERecord [
        Fexpr "mut" (
          deco "Mutex.create()" (
            EApp (deco "Mutex.create" (EPath [ "Mutex"; "create" ])) (
              deco "()" (EData "()" [])
            )
          )
        );
        Fexpr "v" (
          deco "if b then 1 else 0" (
            EIfThenElse (deco "b" (EPath [ "b" ])) (deco "1" __exp23) (
              deco "0" __exp24
            )
          )
        );
        Fexpr "nonzero" (
          deco "Condition.create()" (
            EApp (deco "Condition.create" (EPath [ "Condition"; "create" ])) (
              deco "()" (EData "()" [])
            )
          )
        )
      ]
    )
  ).

Definition __exp26 :=
  EApp (deco "Mutex.unlock" (EPath [ "Mutex"; "unlock" ])) (
    deco "s.mut" (ERecordAccess (deco "s" (EPath [ "s" ])) "mut")
  ).

Definition __exp27 :=
  ESeq (
    deco "Condition.signal s.nonzero" (
      EApp (deco "Condition.signal" (EPath [ "Condition"; "signal" ])) (
        deco "s.nonzero" (ERecordAccess (deco "s" (EPath [ "s" ])) "nonzero")
      )
    )
  ) (deco "Mutex.unlock s.mut" __exp26).

Definition __exp28 :=
  ESeq (deco "s.v <- 1" EUnsupported) (
    deco "Condition.signa...ex.unlock s.mut" __exp27
  ).

Definition __fun29 :=
  AnonFun "s" (
    deco "Mutex.lock s.mu...ex.unlock s.mut" (
      ESeq (
        deco "Mutex.lock s.mut" (
          EApp (deco "Mutex.lock" (EPath [ "Mutex"; "lock" ])) (
            deco "s.mut" (ERecordAccess (deco "s" (EPath [ "s" ])) "mut")
          )
        )
      ) (deco "s.v <- 1; Condi...ex.unlock s.mut" __exp28)
    )
  ).

Definition __exp30 :=
  EApp (
    EApp (deco "Condition.wait" (EPath [ "Condition"; "wait" ])) (
      deco "s.nonzero" (ERecordAccess (deco "s" (EPath [ "s" ])) "nonzero")
    )
  ) (deco "s.mut" (ERecordAccess (deco "s" (EPath [ "s" ])) "mut")).

Definition __exp31 :=
  EApp (deco "Mutex.unlock" (EPath [ "Mutex"; "unlock" ])) (
    deco "s.mut" (ERecordAccess (deco "s" (EPath [ "s" ])) "mut")
  ).

Definition __exp32 :=
  ESeq (deco "s.v <- 0" EUnsupported) (deco "Mutex.unlock s.mut" __exp31).

Definition __exp33 :=
  ESeq (
    deco "while s.v = 0 d...zero s.mut done" (
      EWhile (
        deco "s.v = 0" (
          EOpEq (deco "s.v" (ERecordAccess (deco "s" (EPath [ "s" ])) "v")) (
            deco "0" (EInt 0)
          )
        )
      ) (deco "Condition.wait s.nonzero s.mut" __exp30)
    )
  ) (deco "s.v <- 0; Mutex.unlock s.mut" __exp32).

Definition __fun34 :=
  AnonFun "s" (
    deco "Mutex.lock s.mu...ex.unlock s.mut" (
      ESeq (
        deco "Mutex.lock s.mut" (
          EApp (deco "Mutex.lock" (EPath [ "Mutex"; "lock" ])) (
            deco "s.mut" (ERecordAccess (deco "s" (EPath [ "s" ])) "mut")
          )
        )
      ) (deco "while s.v = 0 d...ex.unlock s.mut" __exp33)
    )
  ).

Definition __exp35 := EData "false" [].

Definition __exp36 := EData "true" [].

Definition __exp37 := ESeq (deco "s.v <- 0" EUnsupported) (deco "true" __exp36).

Definition __exp38 := EPath [ "ret" ].

Definition __exp39 :=
  ESeq (
    deco "Mutex.unlock s.mut" (
      EApp (deco "Mutex.unlock" (EPath [ "Mutex"; "unlock" ])) (
        deco "s.mut" (ERecordAccess (deco "s" (EPath [ "s" ])) "mut")
      )
    )
  ) (deco "ret" __exp38).

Definition __exp40 :=
  ELet [
    Binding (PVar "ret") (
      deco "if s.v = 0 then...s.v <- 0; true)" (
        EIfThenElse (
          deco "s.v = 0" (
            EOpEq (deco "s.v" (ERecordAccess (deco "s" (EPath [ "s" ])) "v")) (
              deco "0" (EInt 0)
            )
          )
        ) (deco "false" __exp35) (deco "(s.v <- 0; true)" __exp37)
      )
    )
  ] (deco "Mutex.unlock s.mut; ret" __exp39).

Definition __fun41 :=
  AnonFun "s" (
    deco "Mutex.lock s.mu...lock s.mut; ret" (
      ESeq (
        deco "Mutex.lock s.mut" (
          EApp (deco "Mutex.lock" (EPath [ "Mutex"; "lock" ])) (
            deco "s.mut" (ERecordAccess (deco "s" (EPath [ "s" ])) "mut")
          )
        )
      ) (deco "let ret = if s....lock s.mut; ret" __exp40)
    )
  ).

Definition __main :=
  MStruct [
    IModule "Counting" (
      MStruct [
        ILet [
          Binding (PVar "make") (
            deco "v = if v < 0 th...tion.create() }" (EAnonFun __fun2)
          )
        ];
        ILet [
          Binding (PVar "release") (
            deco "s = Mutex.lock ... overflow"") end" (EAnonFun __fun9)
          )
        ];
        ILet [
          Binding (PVar "acquire") (
            deco "s = Mutex.lock ...ex.unlock s.mut" (EAnonFun __fun14)
          )
        ];
        ILet [
          Binding (PVar "try_acquire") (
            deco "s = Mutex.lock ...lock s.mut; ret" (EAnonFun __fun21)
          )
        ];
        ILet [
          Binding (PVar "get_value") (deco "s = s.v" (EAnonFun __fun22))
        ]
      ]
    );
    IModule "Binary" (
      MStruct [
        ILet [
          Binding (PVar "make") (
            deco "b = { mut = Mut...tion.create() }" (EAnonFun __fun25)
          )
        ];
        ILet [
          Binding (PVar "release") (
            deco "s = Mutex.lock ...ex.unlock s.mut" (EAnonFun __fun29)
          )
        ];
        ILet [
          Binding (PVar "acquire") (
            deco "s = Mutex.lock ...ex.unlock s.mut" (EAnonFun __fun34)
          )
        ];
        ILet [
          Binding (PVar "try_acquire") (
            deco "s = Mutex.lock ...lock s.mut; ret" (EAnonFun __fun41)
          )
        ]
      ]
    )
  ].

