(* This file has been generated by Osiris. Do not edit. *)

From osiris Require Import osiris.

Definition __branches0 :=
  [
    Branch (CVal (PData "()" [])) (deco "true" (EData "true" []))
  ].

Definition __fun1 := AnonFunction __branches0.

Definition __branches2 := [ Branch (CVal (PData "()" [])) (EAnonFun __fun1) ].

Definition __fun3 := AnonFunction __branches2.

Definition __branches4 := [ Branch (CVal (PData "()" [])) (deco "0" (EInt 0)) ].

Definition __fun5 := AnonFunction __branches4.

Definition __branches6 := [ Branch (CVal (PData "()" [])) (EAnonFun __fun5) ].

Definition __fun7 := AnonFunction __branches6.

Definition __branches8 :=
  [
    Branch (CVal (PData "()" [])) (deco """()""" (EString "()"))
  ].

Definition __fun9 := AnonFunction __branches8.

Definition __main :=
  MStruct [
    ILet [
      Binding (PVar "equal") (deco "() () = true" (EAnonFun __fun3))
    ];
    ILet [
      Binding (PVar "compare") (deco "() () = 0" (EAnonFun __fun7))
    ];
    ILet [
      Binding (PVar "to_string") (deco "() = ""()""" (EAnonFun __fun9))
    ]
  ].

