(* This file has been generated by Osiris. Do not edit. *)

From osiris Require Import osiris.

Definition __fun0 :=
  AnonFun "i" (
    deco "format_int ""%X""...e scalar value""" (
      EApp (
        EApp (deco "^" (EPath [ "^" ])) (
          deco "format_int ""%X"" i" (
            EApp (
              EApp (deco "format_int" (EPath [ "format_int" ])) (
                deco """%X""" (EString "%X")
              )
            ) (deco "i" (EPath [ "i" ]))
          )
        )
      ) (
        deco """ is not an Unicode scalar value""" (
          EString " is not an Unicode scalar value"
        )
      )
    )
  ).

Definition __fun1 :=
  AnonFun "u" (
    deco """U+"" ^ format_i...tin1 character""" (
      EApp (EApp (deco "^" (EPath [ "^" ])) (deco """U+""" (EString "U+"))) (
        deco "format_int ""%04...tin1 character""" (
          EApp (
            EApp (deco "^" (EPath [ "^" ])) (
              deco "format_int ""%04X"" u" (
                EApp (
                  EApp (deco "format_int" (EPath [ "format_int" ])) (
                    deco """%04X""" (EString "%04X")
                  )
                ) (deco "u" (EPath [ "u" ]))
              )
            )
          ) (
            deco """ is not a latin1 character""" (
              EString " is not a latin1 character"
            )
          )
        )
      )
    )
  ).

Definition __exp2 := EPath [ "hi_bound" ].

Definition __exp3 :=
  EApp (deco "invalid_arg" (EPath [ "invalid_arg" ])) (
    deco "err_no_succ" (EPath [ "err_no_succ" ])
  ).

Definition __exp4 := EIntAdd (deco "u" (EPath [ "u" ])) (deco "1" (EInt 1)).

Definition __exp5 :=
  EIfThenElse (
    deco "u = max" (
      EOpEq (deco "u" (EPath [ "u" ])) (deco "max" (EPath [ "max" ]))
    )
  ) (deco "invalid_arg err_no_succ" __exp3) (deco "u + 1" __exp4).

Definition __fun6 :=
  AnonFun "u" (
    deco "if u = lo_bound...succ else u + 1" (
      EIfThenElse (
        deco "u = lo_bound" (
          EOpEq (deco "u" (EPath [ "u" ])) (
            deco "lo_bound" (EPath [ "lo_bound" ])
          )
        )
      ) (deco "hi_bound" __exp2) (
        deco "if u = max then...succ else u + 1" __exp5
      )
    )
  ).

Definition __exp7 := EPath [ "lo_bound" ].

Definition __exp8 :=
  EApp (deco "invalid_arg" (EPath [ "invalid_arg" ])) (
    deco "err_no_pred" (EPath [ "err_no_pred" ])
  ).

Definition __exp9 := EIntSub (deco "u" (EPath [ "u" ])) (deco "1" (EInt 1)).

Definition __exp10 :=
  EIfThenElse (
    deco "u = min" (
      EOpEq (deco "u" (EPath [ "u" ])) (deco "min" (EPath [ "min" ]))
    )
  ) (deco "invalid_arg err_no_pred" __exp8) (deco "u - 1" __exp9).

Definition __fun11 :=
  AnonFun "u" (
    deco "if u = hi_bound...pred else u - 1" (
      EIfThenElse (
        deco "u = hi_bound" (
          EOpEq (deco "u" (EPath [ "u" ])) (
            deco "hi_bound" (EPath [ "hi_bound" ])
          )
        )
      ) (deco "lo_bound" __exp7) (
        deco "if u = min then...pred else u - 1" __exp10
      )
    )
  ).

Definition __fun12 :=
  AnonFun "i" (
    deco "(min <= i && i ... i && i <= max)" (
      EBoolDisj (
        deco "(min <= i && i <= lo_bound)" (
          EBoolConj (
            deco "min <= i" (
              EOpLe (deco "min" (EPath [ "min" ])) (deco "i" (EPath [ "i" ]))
            )
          ) (
            deco "i <= lo_bound" (
              EOpLe (deco "i" (EPath [ "i" ])) (
                deco "lo_bound" (EPath [ "lo_bound" ])
              )
            )
          )
        )
      ) (
        deco "(hi_bound <= i && i <= max)" (
          EBoolConj (
            deco "hi_bound <= i" (
              EOpLe (deco "hi_bound" (EPath [ "hi_bound" ])) (
                deco "i" (EPath [ "i" ])
              )
            )
          ) (
            deco "i <= max" (
              EOpLe (deco "i" (EPath [ "i" ])) (deco "max" (EPath [ "max" ]))
            )
          )
        )
      )
    )
  ).

Definition __exp13 := EPath [ "i" ].

Definition __exp14 :=
  EApp (deco "invalid_arg" (EPath [ "invalid_arg" ])) (
    deco "(err_not_sv i)" (
      EApp (deco "err_not_sv" (EPath [ "err_not_sv" ])) (
        deco "i" (EPath [ "i" ])
      )
    )
  ).

Definition __fun15 :=
  AnonFun "i" (
    deco "if is_valid i t... (err_not_sv i)" (
      EIfThenElse (
        deco "is_valid i" (
          EApp (deco "is_valid" (EPath [ "is_valid" ])) (
            deco "i" (EPath [ "i" ])
          )
        )
      ) (deco "i" __exp13) (deco "invalid_arg (err_not_sv i)" __exp14)
    )
  ).

Definition __fun16 :=
  AnonFun "u" (
    deco "u < 256" (EOpLt (deco "u" (EPath [ "u" ])) (deco "256" (EInt 256)))
  ).

Definition __fun17 :=
  AnonFun "c" (
    deco "Char.code c" (
      EApp (deco "Char.code" (EPath [ "Char"; "code" ])) (
        deco "c" (EPath [ "c" ])
      )
    )
  ).

Definition __exp18 :=
  EApp (deco "invalid_arg" (EPath [ "invalid_arg" ])) (
    deco "(err_not_latin1 u)" (
      EApp (deco "err_not_latin1" (EPath [ "err_not_latin1" ])) (
        deco "u" (EPath [ "u" ])
      )
    )
  ).

Definition __exp19 :=
  EApp (deco "Char.unsafe_chr" (EPath [ "Char"; "unsafe_chr" ])) (
    deco "u" (EPath [ "u" ])
  ).

Definition __fun20 :=
  AnonFun "u" (
    deco "if u > 255 then...ar.unsafe_chr u" (
      EIfThenElse (
        deco "u > 255" (
          EOpGt (deco "u" (EPath [ "u" ])) (deco "255" (EInt 255))
        )
      ) (deco "invalid_arg (err_not_latin1 u)" __exp18) (
        deco "Char.unsafe_chr u" __exp19
      )
    )
  ).

Definition __fun21 :=
  AnonFun "d" (
    deco "(d lsr valid_bit) = 1" (
      EOpEq (
        deco "(d lsr valid_bit)" (
          EIntLsr (deco "d" (EPath [ "d" ])) (
            deco "valid_bit" (EPath [ "valid_bit" ])
          )
        )
      ) (deco "1" (EInt 1))
    )
  ).

Definition __fun22 :=
  AnonFun "d" (
    deco "(d lsr decode_bits) land 0b111" (
      EIntLand (
        deco "(d lsr decode_bits)" (
          EIntLsr (deco "d" (EPath [ "d" ])) (
            deco "decode_bits" (EPath [ "decode_bits" ])
          )
        )
      ) (deco "0b111" (EInt 7))
    )
  ).

Definition __fun23 :=
  AnonFun "d" (
    deco "unsafe_of_int (d land 0xFFFFFF)" (
      EApp (deco "unsafe_of_int" (EPath [ "unsafe_of_int" ])) (
        deco "(d land 0xFFFFFF)" (
          EIntLand (deco "d" (EPath [ "d" ])) (deco "0xFFFFFF" (EInt 16777215))
        )
      )
    )
  ).

Definition __fun24 :=
  AnonFun "u" (
    deco "((8 lor n) lsl ... lor (to_int u)" (
      EIntLor (
        deco "((8 lor n) lsl decode_bits)" (
          EIntLsl (
            deco "(8 lor n)" (
              EIntLor (deco "8" (EInt 8)) (deco "n" (EPath [ "n" ]))
            )
          ) (deco "decode_bits" (EPath [ "decode_bits" ]))
        )
      ) (
        deco "(to_int u)" (
          EApp (deco "to_int" (EPath [ "to_int" ])) (deco "u" (EPath [ "u" ]))
        )
      )
    )
  ).

Definition __fun25 := AnonFun "n" (EAnonFun __fun24).

Definition __fun26 :=
  AnonFun "n" (
    deco "(n lsl decode_bits) lor rep" (
      EIntLor (
        deco "(n lsl decode_bits)" (
          EIntLsl (deco "n" (EPath [ "n" ])) (
            deco "decode_bits" (EPath [ "decode_bits" ])
          )
        )
      ) (deco "rep" (EPath [ "rep" ]))
    )
  ).

Definition __branches27 :=
  [
    Branch (CVal (PVar "u")) EUnsupported;
    Branch (CVal (PVar "u")) EUnsupported;
    Branch (CVal (PVar "u")) EUnsupported;
    Branch (CVal (PVar "u")) EUnsupported;
    Branch (CVal (PVar "u")) EUnsupported;
    Branch (CVal PAny) (deco "assert false" EAssertFalse)
  ].

Definition __fun28 :=
  AnonFun "u" (
    deco "match to_int u ...-> assert false" (
      EMatch (
        deco "to_int u" (
          EApp (deco "to_int" (EPath [ "to_int" ])) (deco "u" (EPath [ "u" ]))
        )
      ) __branches27
    )
  ).

Definition __branches29 :=
  [
    Branch (CVal (PVar "u")) EUnsupported;
    Branch (CVal (PVar "u")) EUnsupported;
    Branch (CVal (PVar "u")) EUnsupported;
    Branch (CVal PAny) (deco "assert false" EAssertFalse)
  ].

Definition __fun30 :=
  AnonFun "u" (
    deco "match to_int u ...-> assert false" (
      EMatch (
        deco "to_int u" (
          EApp (deco "to_int" (EPath [ "to_int" ])) (deco "u" (EPath [ "u" ]))
        )
      ) __branches29
    )
  ).

Definition __main :=
  MStruct [
    ILet [
      Binding (PVar "err_no_pred") (
        deco """U+0000 has no predecessor""" (
          EString "U+0000 has no predecessor"
        )
      )
    ];
    ILet [
      Binding (PVar "err_no_succ") (
        deco """U+10FFFF has no successor""" (
          EString "U+10FFFF has no successor"
        )
      )
    ];
    ILet [
      Binding (PVar "err_not_sv") (
        deco "i = format_int ...e scalar value""" (EAnonFun __fun0)
      )
    ];
    ILet [
      Binding (PVar "err_not_latin1") (
        deco "u = ""U+"" ^ form...tin1 character""" (EAnonFun __fun1)
      )
    ];
    ILet [
      Binding (PVar "min") (deco "0x0000" (EInt 0))
    ];
    ILet [
      Binding (PVar "max") (deco "0x10FFFF" (EInt 1114111))
    ];
    ILet [
      Binding (PVar "lo_bound") (deco "0xD7FF" (EInt 55295))
    ];
    ILet [
      Binding (PVar "hi_bound") (deco "0xE000" (EInt 57344))
    ];
    ILet [
      Binding (PVar "bom") (deco "0xFEFF" (EInt 65279))
    ];
    ILet [
      Binding (PVar "rep") (deco "0xFFFD" (EInt 65533))
    ];
    ILet [
      Binding (PVar "succ") (
        deco "u = if u = lo_b...succ else u + 1" (EAnonFun __fun6)
      )
    ];
    ILet [
      Binding (PVar "pred") (
        deco "u = if u = hi_b...pred else u - 1" (EAnonFun __fun11)
      )
    ];
    ILet [
      Binding (PVar "is_valid") (
        deco "i = (min <= i &... i && i <= max)" (EAnonFun __fun12)
      )
    ];
    ILet [
      Binding (PVar "of_int") (
        deco "i = if is_valid... (err_not_sv i)" (EAnonFun __fun15)
      )
    ];
    ILet [
      Binding (PVar "is_char") (deco "u = u < 256" (EAnonFun __fun16))
    ];
    ILet [
      Binding (PVar "of_char") (deco "c = Char.code c" (EAnonFun __fun17))
    ];
    ILet [
      Binding (PVar "to_char") (
        deco "u = if u > 255 ...ar.unsafe_chr u" (EAnonFun __fun20)
      )
    ];
    ILet [
      Binding (PVar "unsafe_to_char") (
        deco "Char.unsafe_chr" (EPath [ "Char"; "unsafe_chr" ])
      )
    ];
    ILet [
      Binding (PAlias PAny "equal") (deco "( = )" (EPath [ "=" ]))
    ];
    ILet [
      Binding (PAlias PAny "compare") (
        deco "Stdlib.compare" (EPath [ "Stdlib"; "compare" ])
      )
    ];
    ILet [
      Binding (PVar "hash") (deco "to_int" (EPath [ "to_int" ]))
    ];
    ILet [
      Binding (PVar "valid_bit") (deco "27" (EInt 27))
    ];
    ILet [
      Binding (PVar "decode_bits") (deco "24" (EInt 24))
    ];
    ILet [
      Binding (PVar "utf_decode_is_valid") (
        deco "d = (d lsr valid_bit) = 1" (EAnonFun __fun21)
      )
    ];
    ILet [
      Binding (PVar "utf_decode_length") (
        deco "d = (d lsr deco...its) land 0b111" (EAnonFun __fun22)
      )
    ];
    ILet [
      Binding (PVar "utf_decode_uchar") (
        deco "d = unsafe_of_i... land 0xFFFFFF)" (EAnonFun __fun23)
      )
    ];
    ILet [
      Binding (PVar "utf_decode") (
        deco "n u = ((8 lor n... lor (to_int u)" (EAnonFun __fun25)
      )
    ];
    ILet [
      Binding (PVar "utf_decode_invalid") (
        deco "n = (n lsl decode_bits) lor rep" (EAnonFun __fun26)
      )
    ];
    ILet [
      Binding (PVar "utf_8_byte_length") (
        deco "u = match to_in...-> assert false" (EAnonFun __fun28)
      )
    ];
    ILet [
      Binding (PVar "utf_16_byte_length") (
        deco "u = match to_in...-> assert false" (EAnonFun __fun30)
      )
    ]
  ].

